sul-dlss/happy-heron

Gemfile, Gemfile.lock, package.json, yarn.lock
=> Upgrade to webpacker 5

app/components/add_files_component.html.erb, app/components/add_files_component.rb, app/components/agreement_component.html.erb, app/components/agreement_component.rb, app/components/buttons_component.html.erb, app/components/buttons_component.rb, app/components/collection_component.html.erb, app/components/collection_component.rb, app/components/contributors_component.html.erb, app/components/contributors_component.rb, app/components/dates_component.html.erb, app/components/dates_component.rb, app/components/description_component.html.erb, app/components/description_component.rb, app/components/embargo_component.html.erb, app/components/embargo_component.rb, app/components/license_component.html.erb, app/components/license_component.rb, app/components/title_component.html.erb, app/components/title_component.rb, app/components/work_form_component.html.erb, app/components/work_form_component.rb, app/controllers/works_controller.rb, app/javascript/stylesheets/editor.scss, app/javascript/stylesheets/main.scss, app/views/layouts/editor.html.erb, app/views/welcome/show.html.erb, app/views/works/new.html.erb, config/routes.rb
This just sets up a skeleton of the form.
=> Add basic motion form

app/components/add_files_component.html.erb, app/components/add_files_component.rb, app/components/agreement_component.html.erb, app/components/agreement_component.rb, app/components/buttons_component.html.erb, app/components/buttons_component.rb, app/components/dates_component.html.erb, app/components/dates_component.rb, app/components/description_component.html.erb, app/components/description_component.rb, app/components/embargo_component.html.erb, app/components/embargo_component.rb, app/components/license_component.html.erb, app/components/license_component.rb, app/components/title_component.html.erb, app/components/title_component.rb, app/components/work_form_component.html.erb, app/components/work_form_component.rb, app/components/work_type_component.html.erb, app/components/work_type_component.rb, app/controllers/works_controller.rb, app/models/work.rb, app/views/works/new.html.erb, app/views/works/show.html.erb, config/routes.rb, db/migrate/20200911170014_create_works.rb, db/migrate/20200913005756_create_active_storage_tables.active_storage.rb, db/schema.rb
=> Allow work objects to be created

Gemfile, Gemfile.lock, app/components/deposit_progress_component.html.erb, app/components/deposit_progress_component.rb, app/components/title_component.html.erb, app/components/title_component.rb, app/components/work_form_component.html.erb, app/javascript/modules/validate-forms.js, app/javascript/packs/application.js, app/javascript/stylesheets/depositProgress.scss, app/javascript/stylesheets/editor.scss, app/javascript/stylesheets/main.scss
This helps illustrate that motion is working to solve the kind of problems we want it to.
=> Create a deposit progress component

yarn.lock
=> Ran yarn upgrade to fix security warning

yarn.lock
=> Upgrade bootstrap to 5.0.0-alpha2

app/views/welcome/show.html.erb, app/views/works/new.html.erb
=> Update sr-only to visually-hidden-focusable

README.md
To make the documentation clearer.
N/A
README
=> Clarify sorbet pre-commit in README

config/deploy.rb, config/deploy/prod.rb, config/deploy/stage.rb
To allow cap deployments to h2-stage/prod
via cap
DevOpsDocs pending
=> Deploy to stage/prod

README.md
Clarify pre-commit hook instructions.
Locally.
README.
=> Clarification on pre-commit hook.

app/views/layouts/application.html.erb, spec/requests/home_page_spec.rb
Fixes #23 -- sets the html head title
request spec
=> update html head title to SDR

app/models/collection.rb, app/models/contributor.rb, app/models/notification.rb, app/models/related_link.rb, app/models/related_work.rb, app/models/role_term.rb, app/models/work.rb
Fixes #148.
Mike and I discussed whether or not to add tests to these validations.  They are straight ActiveRecord code, but that doesn't always mean our code does what we meant it to.   We decided to see how the coverage looked after this commit.
=> add model validations for presence

app/jobs/deposit_job.rb, app/services/description_generator.rb, app/services/request_generator.rb, sorbet/rails-rbi/typed_params.rbi, spec/services/request_generator_spec.rb
Add description to cocina model when depositing.
Unit
NA
=> Add description when depositing

config/webpacker.yml, spec/requests/collections_spec.rb
=> Fix collections spec 

.rubocop.yml, app/models/work.rb, app/models/work_type.rb, spec/factories/works.rb
=> Validate work types are in the allowed set

app/components/license_component.html.erb, app/models/license.rb, app/models/work.rb, spec/factories/works.rb, spec/features/create_new_work_spec.rb
=> Validate license types

config/settings.yml
This makes it easier to get started.
I've turned it to false in production: https://github.com/sul-dlss/shared_configs/blob/sul-h2-prod/config/settings/production.yml
=> Turn the allow deposit feature flag to true by default

.rubocop.yml, .rubocop_todo.yml, app/components/works/contributor_row_component.html.erb, app/components/works/contributor_row_component.rb, app/components/works/contributors_component.html.erb, app/components/works/work_form_component.html.erb, app/controllers/works_controller.rb, app/javascript/controllers/nested_form_controller.js, app/javascript/stylesheets/editor.scss, app/javascript/stylesheets/main.scss, app/javascript/stylesheets/palette.scss, app/models/work.rb, app/views/works/show.html.erb, spec/components/works/contributors_component_spec.rb, spec/components/works/work_form_component_spec.rb, spec/requests/works_spec.rb
=> Add contributors to works

app/controllers/works_controller.rb, app/javascript/controllers/work_type_controller.js, app/javascript/packs/application.js, app/javascript/stylesheets/main.scss, app/javascript/stylesheets/palette.scss, app/javascript/stylesheets/toggle.scss, app/models/work_type.rb, app/views/dashboards/show.html.erb, package.json, spec/features/create_new_work_spec.rb, spec/requests/works_spec.rb, yarn.lock
=> Select a work type

app/components/works/contributor_row_component.html.erb
Previously the class was incorrect and not rendering.
=> Set the role term class

app/components/works/license_component.html.erb, app/javascript/stylesheets/editor.scss, spec/components/works/license_component_spec.rb, spec/components/works/work_form_component_spec.rb
=> Update text on license field component to match the mockup

app/components/works/description_component.html.erb, app/components/works/description_component.rb, app/components/works/work_form_component.html.erb, app/controllers/works_controller.rb, app/forms/work_form.rb, app/models/work.rb, app/models/work_type.rb, db/migrate/20201023212141_make_subtype_and_citation_optional.rb, db/structure.sql, spec/components/works/description_component_spec.rb, spec/components/works/work_form_component_spec.rb, spec/factories/works.rb, spec/features/create_new_work_spec.rb, spec/features/user_return_location_spec.rb, spec/requests/collections_spec.rb, spec/requests/works_spec.rb
=> Display subtypes on the form 

spec/jobs/deposit_job_spec.rb, spec/jobs/deposit_status_job_spec.rb, spec/models/collection_spec.rb, spec/models/notification_spec.rb, spec/models/related_link_spec.rb, spec/models/related_work_spec.rb, spec/models/user_spec.rb, spec/services/request_generator_spec.rb
=> Make tests faster by not persisting unless necessary

app/components/works/add_files_component.html.erb, app/components/works/file_row_component.html.erb, app/components/works/file_row_component.rb, app/controllers/works_controller.rb, app/forms/work_form.rb, app/javascript/controllers/dropzone_controller.js, app/javascript/stylesheets/dropzone.scss, app/javascript/stylesheets/dropzoneKeyframes.scss, app/javascript/stylesheets/editor.scss, app/models/attached_file.rb, app/models/work.rb, app/views/works/show.html.erb, db/migrate/20201026222437_create_attached_files.rb, db/structure.sql, spec/components/works/add_files_component_spec.rb, spec/factories/attached_files.rb, spec/factories/works.rb, spec/forms/work_form_spec.rb, spec/models/attached_file_spec.rb, spec/models/work_spec.rb, spec/requests/works_spec.rb
Fixes #119 
Fixes #120 
Fixes #51
=> Make the upload look like the mockups

app/controllers/application_controller.rb, app/controllers/dashboards_controller.rb, app/controllers/works_controller.rb, app/models/contributor.rb, app/models/user.rb, app/policies/collection_policy.rb, app/policies/dashboard_policy.rb, app/policies/work_policy.rb, config/settings.yml, lib/test_shibboleth_headers.rb, sorbet/rbi/hidden-definitions/errors.txt, sorbet/rbi/hidden-definitions/hidden.rbi, spec/features/create_new_work_spec.rb, spec/features/user_return_location_spec.rb, spec/requests/collections_spec.rb, spec/requests/dashboards_spec.rb, spec/requests/works_spec.rb
groundwork for Shibboleth based authorization, with the start of an implementation for #102 (minus some of the suggested UI).
closes #102 (ticketed the part that didn't make it into this PR)
unit tests
base settings now has app user workgroup names.
=> workgroup based authorization groundwork, fleshed out permissions checking, rudimentary authZ failure handling

README.md, app/controllers/application_controller.rb, app/models/user.rb, app/policies/collection_policy.rb, app/policies/dashboard_policy.rb, app/policies/work_policy.rb, config/settings.yml, lib/test_shibboleth_headers.rb, spec/requests/dashboards_spec.rb, spec/requests/works_spec.rb
=> Use a configurable header for group membership

app/views/works/show.html.erb
=> Show keywords

.rubocop.yml, app/components/collections/form_component.html.erb, app/components/collections/form_component.rb, app/controllers/collections_controller.rb, app/forms/collection_form.rb, app/policies/collection_policy.rb, app/views/collections/edit.html.erb, app/views/dashboards/show.html.erb, config/routes.rb, spec/requests/collections_spec.rb
=> Allow collections to be edited

app/components/works/create_modal_component.html.erb, app/components/works/create_modal_component.rb, app/components/works/description_component.html.erb, app/controllers/works_controller.rb, app/javascript/controllers/work_type_controller.js, app/views/dashboards/show.html.erb, spec/components/works/create_modal_component_spec.rb, spec/features/create_new_work_spec.rb
=> Add subtypes to modal

app/components/works/description_component.html.erb
Fixes #45 
The frontend was requiring citation even though it's an optional field.
=> Remove required attribute from citation and update layout

.rubocop.yml, app/controllers/works_controller.rb, app/policies/work_policy.rb, spec/features/create_new_work_spec.rb, spec/features/user_return_location_spec.rb, spec/policies/work_policy_spec.rb, spec/rails_helper.rb, spec/requests/works_spec.rb
=> Ensure that depositors are authorized for the collection.

app/components/works/keywords_component.html.erb, app/components/works/keywords_component.rb, app/components/works/work_form_component.html.erb, app/forms/work_form.rb, app/javascript/stylesheets/keywords.scss, config/initializers/customize_error.rb, spec/components/works/keywords_component_spec.rb, spec/components/works/work_form_component_spec.rb, spec/features/create_new_work_spec.rb, spec/forms/work_form_spec.rb, spec/requests/works_spec.rb, spec/support/capybara_actions.rb
=> Validate that at least one keyword is provided.

app/services/description_generator.rb, spec/factories/works.rb, spec/services/description_generator_spec.rb
=> Copy publication_edtf to the cocina model

.rubocop.yml, app/components/works/description_component.html.erb, app/components/works/related_work_component.html.erb, app/components/works/related_work_component.rb, app/components/works/related_work_row_component.html.erb, app/components/works/related_work_row_component.rb, app/controllers/works_controller.rb, app/forms/work_form.rb, app/views/works/show.html.erb, spec/components/works/related_work_component_spec.rb, spec/components/works/related_work_row_component_spec.rb, spec/requests/works_spec.rb
=> Add related works to the deposit form

app/components/works/description_component.html.erb, app/components/works/related_link_component.html.erb, app/components/works/related_link_component.rb, app/components/works/related_link_row_component.html.erb, app/components/works/related_link_row_component.rb, app/controllers/works_controller.rb, app/forms/work_form.rb, app/views/works/show.html.erb, spec/components/works/related_link_component_spec.rb, spec/components/works/related_link_row_component_spec.rb, spec/features/create_new_work_spec.rb, spec/requests/works_spec.rb
=> Add related links widget to deposit form

app/services/description_generator.rb, spec/factories/works.rb, spec/services/description_generator_spec.rb, spec/services/request_generator_spec.rb
=> Map keywords to cocina

app/components/works/contributor_row_component.html.erb, app/controllers/works_controller.rb, app/forms/work_form.rb, app/javascript/controllers/contributor_controller.js, app/models/contributor.rb, db/migrate/20201105141009_add_full_name_to_contributors.rb, db/structure.sql, spec/forms/work_form_spec.rb, spec/requests/works_spec.rb
=> Organization roles only have a full name

app/components/works/embargo_component.html.erb, spec/features/create_new_work_spec.rb
=> Access select input now required

app/models/work_type.rb
=> Renames Multimedia with mixed materials in Work Types

app/components/works/contributor_row_component.html.erb
=> swap the contributor role type and the name fields in deposit form

spec/services/storage_migrator_spec.rb
Fixes #354
The problem? Looking in the wrong AS disk service. We use a special one in the test environment.
=> Fix flappy spec

app/components/works/embargo_component.html.erb, app/components/works/work_form_component.html.erb, app/components/works/work_form_component.rb, app/controllers/dashboards_controller.rb, app/controllers/works_controller.rb, app/models/user.rb, app/policies/dashboard_policy.rb, app/policies/work_policy.rb, app/presenters/dashboard_presenter.rb, app/views/dashboards/show.html.erb, app/views/works/edit.html.erb, config/routes.rb, spec/components/works/work_form_component_spec.rb, spec/factories/works.rb, spec/features/create_new_work_spec.rb, spec/features/edit_draft_work_spec.rb, spec/features/user_return_location_spec.rb, spec/requests/works_spec.rb, spec/support/capybara.rb
=> Allow a draft deposit to be edited

app/components/works/deposit_progress_component.html.erb, spec/components/works/deposit_progress_component_spec.rb, spec/components/works/work_form_component_spec.rb
Fixes #320
Updated two tests; confirmed in browser.
=> remove date and numbers from progress bar

app/components/works/add_files_component.html.erb, app/components/works/description_component.html.erb
Fixes #335. **Note**, missing Contact email link. 
Test suite
n/a
=> Content additions for Work Form

app/forms/collection_form.rb, app/models/user.rb, app/policies/application_policy.rb, app/policies/collection_policy.rb, app/policies/work_policy.rb, spec/policies/collection_policy_spec.rb, spec/policies/work_policy_spec.rb, spec/requests/collections_spec.rb
=> Prevent unauthorized users from updating collections

.rubocop.yml
=> Add new rubocop cops

app/models/work_type.rb, app/services/request_generator.rb, app/validators/work_subtype_validator.rb, spec/services/request_generator_spec.rb
=> Map h2 work type to cocina work types

app/forms/work_form.rb, spec/requests/works_spec.rb
We don't want to try to sync this to an existing model.
Fixes #388
=> Make the file property a virtual property

app/forms/work_form.rb
=> Simplify the process of attaching a file 

app/components/works/add_files_component.html.erb, app/components/works/contributors_component.html.erb, app/components/works/dates_component.html.erb, app/components/works/description_component.html.erb, app/components/works/embargo_component.html.erb, app/components/works/license_component.html.erb, app/components/works/title_component.html.erb, app/javascript/stylesheets/main.scss, app/javascript/stylesheets/work.scss, app/models/work.rb, app/views/works/show.html.erb, config/settings.yml, spec/features/create_new_work_spec.rb, spec/features/edit_draft_work_spec.rb, spec/models/work_spec.rb, spec/requests/works_spec.rb
closes #33
To allow viewing the details for a work.
Unit, locally.
settings.yml
=> Adds work view.

spec/services/description_generator_spec.rb
I made a flappy spec in PR #393 - this fixes it
=> desc_gen_spec: fix flappy spec

app/models/contributor.rb, app/services/description_generator.rb
Reverts sul-dlss/happy-heron#407
=> Revert "Defer to contributor to have knowledge of its name and type"

README.md
To reflect recent changes in understanding and shared process around Sorbet.
Locally.
README
=> Update documentation about sorbet automation

app/services/description_generator.rb, sorbet/rails-rbi/models/user.rbi, sorbet/rbi/hidden-definitions/hidden.rbi, spec/factories/related_links.rb, spec/factories/works.rb, spec/services/description_generator_spec.rb, spec/services/request_generator_spec.rb
closes #341 
unit tests, rails console
n/a, hopefully specs cover it
=> DescriptionGenerator: map work#related_links to Cocina description

app/controllers/works_controller.rb, app/forms/collection_form.rb, app/models/application_record.rb, app/models/collection.rb, sorbet/custom/controllers/action_controller/base.rbi, sorbet/custom/models/work.rbi, spec/requests/works_spec.rb
=> Send deposits in collection with reviewers to mediation

app/components/works/embargo_component.html.erb
Fixes #391 by updating the text content per the issue.
N/A
N/A
=> Update text content on embargo component

app/components/checkbox_button_component.html.erb, app/components/checkbox_button_component.rb, app/components/works/approval_component.html.erb, app/components/works/approval_component.rb, app/components/works/work_type_modal_component.html.erb, app/controllers/reviews_controller.rb, app/javascript/stylesheets/dashboard.scss, app/javascript/stylesheets/toggle.scss, app/javascript/stylesheets/work.scss, app/models/work.rb, app/policies/work_policy.rb, app/views/dashboards/show.html.erb, app/views/works/show.html.erb, config/routes.rb, spec/components/checkbox_button_component_spec.rb, spec/components/works/approval_component_spec.rb, spec/factories/works.rb, spec/policies/work_policy_spec.rb, spec/requests/reviews_spec.rb
=> Add the ability to approve a deposit in the pending approval state

app/components/works/approval_component.html.erb, app/controllers/reviews_controller.rb, app/javascript/controllers/approval_controller.js, app/javascript/stylesheets/work.scss, app/models/event.rb, app/models/work.rb, app/views/works/show.html.erb, db/migrate/20201112131704_create_events.rb, db/structure.sql, spec/factories/events.rb, spec/models/event_spec.rb, spec/requests/reviews_spec.rb
=> The reviewer can provide a reason when returning a deposit

app/components/works/embargo_component.html.erb, app/javascript/stylesheets/editor.scss
=> Align text for manage release

app/services/contributors_generator.rb
Some optional refactors were suggested for PR #447;  I experimented and ended up with these.
by the tests I wrote for PR #447, of course!
=> [Refactor] contributor_generator small refactors for better clarity

app/forms/application_populator.rb, app/forms/attached_files_populator.rb, app/forms/contributor_populator.rb, app/forms/draft_work_form.rb, app/forms/keywords_populator.rb, app/forms/related_links_populator.rb, app/forms/related_works_populator.rb
=> Extract populators from WorkForm 

spec/services/description_generator_spec.rb
I realized I should have put in this comment earlier.
=> description_generator_spec: add comment

app/validators/created_in_past_validator.rb, spec/validators/created_in_past_validator_spec.rb
=> Validate that publication date is in the past

app/models/work.rb, spec/factories/works.rb, spec/models/work_spec.rb
=> Properly serialize EDTF dates

app/services/contributors_generator.rb, app/services/description_generator.rb, spec/services/contributors_generator_spec.rb
Some small refactors for clarity and compactness
unit tests
=> [Refactor] contributor_generator slight refactor

app/jobs/deposit_job.rb
=> appease rubocop masters

app/policies/work_policy.rb, spec/policies/work_policy_spec.rb
=> Administrators should have all work privileges

app/components/collections/form_component.html.erb, app/components/collections/form_component.rb, app/controllers/collections_controller.rb, app/forms/draft_collection_form.rb, app/javascript/controllers/edit_collection_controller.js, app/javascript/controllers/reviewer_sunets_controller.js, app/views/collections/errors.json.jbuilder, spec/requests/collections_spec.rb
=> Validate that reviewers are provided when review workflow enabled

app/controllers/collections_controller.rb, app/jobs/deposit_collection_job.rb, app/jobs/deposit_job.rb, app/jobs/deposit_status_job.rb, app/models/collection.rb, app/services/collection_generator.rb, db/migrate/20201119215418_add_state_to_collections.rb, db/migrate/20201119215854_add_version_and_druid_to_collections.rb, db/structure.sql, spec/jobs/deposit_collection_job_spec.rb, spec/jobs/deposit_job_spec.rb, spec/jobs/deposit_status_job_spec.rb, spec/services/collection_generator_spec.rb
=> Deposit collections

app/services/file_generator.rb, app/services/request_generator.rb, app/services/structural_generator.rb, sorbet/custom/cocina-models.rbi, spec/jobs/deposit_job_spec.rb, spec/services/request_generator_spec.rb
So that the object has the correct collection in SDR. Fixes #515
=> Add collection membership to the cocina model

app/controllers/works_controller.rb, app/models/work.rb, app/services/event_service.rb, sorbet/custom/models/work.rbi, spec/models/work_spec.rb, spec/services/event_service_spec.rb
=> Move away from the event service by leveraging transition actions

app/services/access_generator.rb, app/services/file_generator.rb, spec/factories/works.rb, spec/services/access_generator_spec.rb, spec/services/file_generator_spec.rb, spec/services/request_generator_spec.rb
=> Map access and embargo to the cocina model

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb
=> Add a banner that displays when a deposit is sent for review

app/components/works/dates_component.html.erb, app/components/works/dates_component.rb, app/models/work.rb, app/services/description_generator.rb, sorbet/custom/forms/draft_work_form.rbi, spec/components/works/dates_component_spec.rb, spec/factories/works.rb, spec/models/work_spec.rb, spec/requests/create_work_spec.rb, spec/requests/edit_work_spec.rb, spec/services/description_generator_spec.rb
=> Default the dates to the stored values

app/components/works/contributor_row_component.html.erb, app/components/works/contributor_row_component.rb, app/components/works/contributors_component.html.erb, app/models/contributor.rb, config/locales/en.yml, spec/components/works/contributor_row_component_spec.rb, spec/components/works/contributors_component_spec.rb, spec/factories/contributors.rb, spec/factories/works.rb, spec/features/help_modal_spec.rb, spec/models/contributor_spec.rb, spec/services/contributors_generator_spec.rb, spec/services/description_generator_spec.rb
=> When editing, show the previously selected roles on the form

app/components/buttons_component.html.erb, app/components/buttons_component.rb, app/components/dashboard/collection_component.html.erb, app/controllers/collections_controller.rb, app/controllers/works_controller.rb, app/models/collection.rb, app/policies/collection_policy.rb, app/policies/work_policy.rb, spec/components/buttons_component_spec.rb, spec/components/works/work_form_component_spec.rb, spec/features/create_new_collection_spec.rb
=> Prevent depositing into an unaccessioned collection

app/components/works/contributor_row_component.html.erb, app/components/works/contributor_row_component.rb, app/components/works/dates_component.html.erb, app/components/works/dates_component.rb, app/components/works/description_component.html.erb, app/components/works/publication_date_component.html.erb, app/components/works/publication_date_component.rb, app/components/works/title_component.html.erb, app/components/works/work_form_component.html.erb, app/components/works/work_form_component.rb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/javascript/controllers/auto_citation_controller.js, app/jobs/deposit_status_job.rb, spec/components/works/contributor_row_component_spec.rb, spec/components/works/dates_component_spec.rb, spec/components/works/publication_date_component_spec.rb, spec/features/create_new_work_spec.rb, spec/jobs/deposit_status_job_spec.rb, spec/requests/create_work_spec.rb
=> Add auto-citation

app/jobs/deposit_status_job.rb, app/models/work.rb, spec/jobs/deposit_status_job_spec.rb
=> Don't add purl to citation if citation is nil

app/policies/work_policy.rb, spec/policies/work_policy_spec.rb
=> Allow collection managers and reviewers to edit works in their collections

app/components/collections/form_component.html.erb, app/controllers/collections_controller.rb, app/forms/draft_collection_form.rb, db/migrate/20201202161823_add_email_depositors_status_changed_to_collection.rb, db/structure.sql, spec/features/create_new_collection_spec.rb, spec/requests/collections_spec.rb
Fixes #586.
Adds to existing test; tested with suite.
n/a
=> Email notification check-boxes for Collection

app/views/layouts/application.html.erb
=> Add a lang tag for better accessability

app/components/buttons_component.rb
=> Refactor button component

app/components/dashboard/all_collections_component.html.erb, app/components/dashboard/all_collections_component.rb, app/components/dashboard/approvals_component.html.erb, app/controllers/dashboards_controller.rb, app/presenters/dashboard_presenter.rb, app/services/stat_builder.rb, app/views/dashboards/show.html.erb, spec/components/dashboard/all_collections_component_spec.rb, spec/factories/object_states.rb, spec/requests/dashboards_spec.rb
=> Show all collections to the admins on the dashboard

app/components/help/form_component.html.erb, app/components/works/add_files_component.html.erb, app/components/works/approval_component.html.erb, app/components/works/contributor_row_component.html.erb, app/components/works/contributor_row_component.rb, app/components/works/deposit_progress_component.html.erb, app/components/works/description_component.html.erb, app/components/works/detail_component.html.erb, app/components/works/embargo_component.html.erb, app/components/works/keywords_component.html.erb, app/components/works/publication_date_component.rb, app/components/works/title_component.html.erb, app/components/works/work_type_modal_component.html.erb, package.json, spec/components/works/contributor_row_component_spec.rb, yarn.lock
=> Upgrade to stimulus 2.0

app/components/dashboard/approvals_component.html.erb, app/components/dashboard/approvals_component.rb, app/views/dashboards/show.html.erb, spec/components/dashboard/approvals_component_spec.rb
This keeps conditional code out of the view.
=> [Refactor] Extract Dashboard::ApprovalsComponent

app/controllers/works_controller.rb, app/policies/work_policy.rb, sorbet/custom/controllers/action_controller/base.rbi, spec/policies/work_policy_spec.rb, spec/requests/show_work_spec.rb
=> Enforce restrictions on who may view a work

app/models/user.rb, config/initializers/devise_remote_user.rb, config/settings.yml, db/migrate/20201204214055_add_name_to_user.rb, db/structure.sql, sorbet/rails-rbi/models/user.rbi
=> Set user name with LDAP attribute

Gemfile, Gemfile.lock, app/jobs/deposit_status_job.rb, lib/tasks/deposit.rake
Fixes #639
This is intended to help with development as the task is not invokable in any other application environment.
Locally and in CI
https://github.com/sul-dlss/happy-heron/wiki/Complete-deposits-locally
=> Mark local deposits as completed

app/javascript/controllers/contact_us_controller.js, app/javascript/packs/application.js, app/views/layouts/application.html.erb, config/routes.rb, config/settings/development.yml
=> Add a link to show the help form

app/services/request_generator.rb, spec/services/request_generator_spec.rb
=> Update RequestGenerator to use the AccessGenerator

app/components/collections/header_component.html.erb, app/components/collections/header_component.rb, app/components/collections/tabs_component.html.erb, app/components/collections/tabs_component.rb, app/components/dashboard/collection_component.html.erb, app/controllers/works_controller.rb, app/javascript/stylesheets/collection.scss, app/policies/work_policy.rb, app/views/collections/_nav.html.erb, app/views/collections/show.html.erb, app/views/works/index.html.erb, config/routes.rb, spec/components/collections/header_component_spec.rb, spec/components/collections/tabs_component_spec.rb, spec/factories/works.rb, spec/requests/show_works_in_collection_spec.rb, spec/services/description_generator_spec.rb, spec/services/request_generator_spec.rb
Using the Dashboard::WorksComponent was not sufficient.
Fixes #693
Fixes #694
Fixes #687
=> Add a page to show the works for a collection

app/components/works/related_link_component.html.erb, app/components/works/related_work_component.html.erb, app/components/works/related_work_row_component.html.erb, app/javascript/stylesheets/editor.scss
=> Add a proper margin for related works and items

app/components/collections/header_component.html.erb, app/components/dashboard/collection_component.html.erb, app/components/help/form_component.html.erb, app/components/works/agreement_component.html.erb, app/components/works/detail_component.html.erb, app/javascript/packs/application.js, app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb, package.json, yarn.lock
Keep up to date, get off of alpha software.
=> Upgrade bootstrap to 5.0.0-beta1

app/components/collections/form_component.html.erb, app/components/collections/links_component.html.erb, app/components/collections/links_component.rb, app/controllers/collections_controller.rb, app/forms/draft_collection_form.rb, app/models/collection.rb, app/models/related_link.rb, app/models/work.rb, app/views/collections/show.html.erb, db/migrate/20201207223546_rename_related_link_work_id_to_linkable.rb, db/structure.sql, spec/components/collections/links_component_spec.rb, spec/factories/related_links.rb, spec/models/related_link_spec.rb, spec/requests/collections_spec.rb, spec/requests/create_collection_spec.rb
Depends on #704
Fixes #699
Fixes #691
=> Collection related

app/mailers/notification_mailer.rb, app/models/work.rb, app/views/notification_mailer/approved_email.html.erb, spec/factories/object_states.rb, spec/mailers/notification_mailer_spec.rb, spec/models/work_spec.rb
=> Send a notification when a item is deposited

config/sidekiq.yml
Email was not being delivered.
=> Configure sidekiq to listen to the mailers queue

app/mailers/notification_mailer.rb, app/models/work.rb, app/views/notification_mailer/submitted_for_review_email.html.erb, spec/factories/object_states.rb, spec/mailers/notification_mailer_spec.rb, spec/models/work_spec.rb
=> Send a notification to approvers when a work is pending approval

Gemfile.lock
=> Update devise-remote-user to avoid deprecations

app/mailers/notification_mailer.rb, app/models/work.rb, app/views/notification_mailer/deposited_email.html.erb, app/views/notification_mailer/new_version_deposited_email.html.erb, spec/mailers/notification_mailer_spec.rb, spec/mailers/previews/notification_mailer_preview.rb, spec/models/work_spec.rb
=> Add notificiation on deposit in a non-reviewed collection

spec/components/works/detail_component_spec.rb, spec/requests/edit_work_spec.rb
Small refactor to use factory traits where possible
Test suite
=> use factory trait for deposited instead of hardcoding string

app/components/dashboard/collection_component.html.erb, app/components/dashboard/collection_component.rb
=> Reduce number of queries to render dashboard without sacrificing readability

app/components/works/work_type_modal_component.html.erb
=> Add the bootstrap 5 data attribute to dismiss the modal

app/views/works_mailer/approved_email.html.erb
=> Add missing parts to approved email text

app/components/works/detail_component.html.erb, app/javascript/controllers/work_updates_controller.js, app/services/broadcast_work_change.rb, spec/models/work_spec.rb
=> Update citation after deposit

app/components/collections/works_component.html.erb, app/components/collections/works_component.rb, app/views/works/index.html.erb, config/locales/en.yml, spec/components/collections/works_component_spec.rb, spec/mailers/previews/helps_mailer_preview.rb
Fixes #674 
Additional unit test for the component
N/A
=> Add additional user and file size columns to the works index listing

app/components/works/embargo_component.html.erb, app/components/works/embargo_component.rb, spec/components/works/embargo_component_spec.rb, spec/factories/works.rb, spec/services/access_generator_spec.rb
=> Show the existing values in the embargo fields

app/components/works/dates_component.html.erb, app/javascript/controllers/date_validation_controller.js
=> Display an error if the edtf isn't valid

app/forms/draft_work_form.rb, app/forms/embargo_date_params_filter.rb, app/validators/embargo_date_parts.rb, spec/forms/work_form_spec.rb, spec/requests/create_work_spec.rb, spec/requests/edit_work_spec.rb, spec/validators/embargo_date_parts_spec.rb, spec/validators/embargo_date_validator_spec.rb
Fixes #556 
Displays the following when month and day are not set:
New and existing tests.
n/a
=> Embargo Date Validation

app/services/types_generator.rb, config/mappings/types_to_genres.yml
Otherwise they don't match and can result in a nil pointer error.
Fixes #760
=> Aligned case in types_to_genres.yml with work_type.rb

app/channels/collection_updates_channel.rb, app/components/collections/header_component.html.erb, app/components/collections/header_component.rb, app/components/collections/information_component.html.erb, app/components/dashboard/collection_component.html.erb, app/components/dashboard/collection_component.rb, app/components/dashboard/collection_header_component.html.erb, app/components/dashboard/collection_header_component.rb, app/components/works/detail_component.html.erb, app/javascript/controllers/state_updates_controller.js, app/models/collection.rb, app/services/broadcast_collection_change.rb, app/views/collections/show.html.erb, app/views/dashboards/show.html.erb, app/views/works/show.html.erb, spec/components/collections/header_component_spec.rb, spec/components/dashboard/collection_header_component_spec.rb
Fixes #653
Tested on QA
Dashboard
Show page
=> Show when a collection is depositing

app/components/collections/form_component.html.erb, app/components/collections/form_component.rb, app/components/works/form_component.html.erb, app/controllers/collections_controller.rb, app/forms/draft_collection_form.rb, app/javascript/stylesheets/collectionEditor.scss, app/javascript/stylesheets/editor.scss, app/javascript/stylesheets/embargo.scss, app/javascript/stylesheets/main.scss, app/javascript/stylesheets/mixins.scss, app/javascript/stylesheets/workEditor.scss, app/views/collections/edit.html.erb, sorbet/custom/forms/draft_collection_form.rbi, spec/factories/collections.rb, spec/requests/create_collection_spec.rb
=> Collection manager can specify the latest permissable embargo date

spec/mailers/collections_mailer_spec.rb, spec/mailers/works_mailer_spec.rb
This is faster than using the database
=> Use stubs where possible

app/controllers/collections_controller.rb, app/mailers/collections_mailer.rb, app/models/collection.rb, app/models/collection_change_set.rb, app/views/collections_mailer/review_access_granted_email.html.erb, spec/mailers/collections_mailer_spec.rb, spec/mailers/previews/collections_mailer_preview.rb, spec/models/collection_spec.rb, spec/requests/edit_collection_spec.rb
=> Reviewer added email

app/views/works_mailer/reject_email.html.erb
Fixes #722 - format email change
In browser
N/A
=> bold and indent rejection reason in email

.rubocop.yml
To silence rubocop warnings and keep our config up to date.
CI
Rubocop config.
=> Update rubocop config with new cops

app/components/collections/work_row_component.html.erb, app/components/collections/work_row_component.rb, app/components/collections/works_component.html.erb, app/components/collections/works_component.rb, spec/components/collections/work_row_component_spec.rb, spec/requests/show_works_in_collection_spec.rb
=> Display units for file sizes

app/components/collections/form_component.html.erb, app/forms/draft_collection_form.rb
Fixes #795 - update collection edit form
Localhost
=> word change to collection participants in collection edit form

app/jobs/base_deposit_job.rb
=> Fix an invalid type definition

app/components/collections/works_component.html.erb, app/components/collections/works_component.rb, spec/components/collections/works_component_spec.rb
=> Order works on the collection page

app/mailers/collections_mailer.rb, app/models/collection_change_set.rb, app/services/collection_observer.rb, app/views/collections_mailer/manage_access_removed_email.html.erb, spec/mailers/collections_mailer_spec.rb, spec/services/collection_observer_spec.rb
=> Send a notification when manage access is revoked

Gemfile, Gemfile.lock
=> Updated dor-services-client to 6.17.0 and sdr-client to 0.41.0

.rubocop.yml, app/mailers/works_mailer.rb, app/services/work_reminder_generator.rb, app/views/works_mailer/new_version_reminder_email.html.erb, config/schedule.rb, spec/mailers/works_mailer_spec.rb, spec/services/work_reminder_generator_spec.rb
=> Send a reminder email for new versions

app/components/buttons_component.html.erb, app/components/buttons_component.rb, app/components/collections/cancel_component.html.erb, app/components/collections/cancel_component.rb, app/components/works/cancel_component.html.erb, app/components/works/cancel_component.rb, sorbet/rails-rbi/mailers/collections_mailer.rbi, sorbet/rbi/gems/activesupport.rbi, sorbet/rbi/gems/docile.rbi, sorbet/rbi/gems/faraday-net_http.rbi, sorbet/rbi/gems/listen.rbi, sorbet/rbi/gems/loofah.rbi, sorbet/rbi/gems/ruby-next-core.rbi, sorbet/rbi/gems/ruby2_keywords.rbi, sorbet/rbi/gems/sshkit.rbi
Fixes #857 - add back button to edit collection/work pages
N/A
=> add cancel button to buttons component

spec/services/collection_observer_spec.rb
=> Fix test that broke after last merge

spec/jobs/deposit_job_spec.rb
=> Avoid deprecated method create_after_upload!

app/components/collections/form_component.html.erb, app/components/works/deposit_progress_component.html.erb, app/components/works/form_component.html.erb, app/views/collections/edit.html.erb
"row" should only be used if the child elements are "col-*"
=> Fix layout so the components align

.rubocop.yml, app/components/dashboard/deposit_progress_component.html.erb, app/components/dashboard/deposit_progress_component.rb, app/components/dashboard/in_progress_component.html.erb, app/components/dashboard/in_progress_row_component.html.erb, app/components/dashboard/in_progress_row_component.rb, app/components/works/deposit_progress_component.html.erb, app/javascript/stylesheets/depositProgress.scss, spec/components/dashboard/deposit_progress_component_spec.rb, spec/components/dashboard/in_progress_row_component_spec.rb
=> Add progress indicators on the dashboard

app/components/works/access_component.html.erb, app/components/works/access_component.rb, app/components/works/available_date_component.html.erb, app/components/works/available_date_component.rb, app/components/works/embargo_component.html.erb, app/components/works/embargo_component.rb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/forms/work_form.rb, app/models/collection.rb, spec/components/works/access_component_spec.rb, spec/components/works/available_date_component_spec.rb, spec/components/works/embargo_component_spec.rb, spec/requests/create_work_spec.rb
=> Enforce the embargo date restrictions provided by the collection

app/javascript/controllers/auto_citation_controller.js, app/models/work.rb, app/services/description_generator.rb, spec/jobs/deposit_status_job_spec.rb, spec/services/description_generator_spec.rb
=> Update text of default citation link placeholder

app/models/contributor.rb, spec/components/works/contributor_row_component_spec.rb
=> Add Distributor to list of Organizational role choices

app/components/works/form_component.rb
=> Add path helper for draft works

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, app/models/work.rb, spec/components/works/detail_component_spec.rb, spec/models/work_spec.rb
=> Display EDTF correctly

app/forms/draft_collection_form.rb, app/models/collection.rb, db/migrate/20210127133325_add_review_enabled_to_collections.rb, db/structure.sql, sorbet/rails-rbi/models/collection.rbi, spec/factories/collections.rb, spec/features/mediated_deposit_versioning_spec.rb, spec/requests/edit_collection_spec.rb
Previously we were just looking for the presence of reviewers. Fixes #661
=> Switch review enabled to being a database field

app/components/works/description_component.html.erb, spec/features/create_new_work_spec.rb
=> Save the auto generated citation

app/components/works/available_date_component.rb, app/components/works/dates_component.html.erb, app/components/works/publication_date_component.html.erb, app/components/works/publication_date_component.rb, spec/components/works/available_date_component_spec.rb, spec/components/works/publication_date_component_spec.rb
=> Validate the publication date is in the past

app/views/collections/new.html.erb
=> Remove unnecessary row class

app/forms/draft_work_form.rb, app/forms/work_form.rb
=> Allow saving a draft with an invalid embargo date

app/components/works/license_component.html.erb, app/components/works/license_component.rb, app/forms/draft_work_form.rb, app/models/collection.rb, app/models/license.rb, spec/components/works/license_component_spec.rb, spec/factories/collections.rb, spec/models/collection_spec.rb, spec/requests/create_work_spec.rb, spec/requests/edit_collection_spec.rb
=> If a collection requires a license, enforce it on the item form

app/policies/work_policy.rb, spec/policies/work_policy_spec.rb
=> Allow admins, collection managers and reviewers to edit submitted items

sorbet/rbi/gems/ast.rbi, sorbet/rbi/gems/capybara-screenshot.rbi, sorbet/rbi/gems/commonmarker.rbi, sorbet/rbi/gems/disposable.rbi, sorbet/rbi/gems/dry-initializer.rbi, sorbet/rbi/gems/dry-logic.rbi, sorbet/rbi/gems/dry-monads.rbi, sorbet/rbi/gems/dry-schema.rbi, sorbet/rbi/gems/dry-struct.rbi, sorbet/rbi/gems/dry-types.rbi, sorbet/rbi/gems/dry-validation.rbi, sorbet/rbi/gems/edtf.rbi, sorbet/rbi/gems/faraday.rbi, sorbet/rbi/gems/jbuilder.rbi, sorbet/rbi/gems/mail.rbi, sorbet/rbi/gems/net-ssh.rbi, sorbet/rbi/gems/nokogiri-1.11.1-x86_64.rbi, sorbet/rbi/gems/okcomputer.rbi, sorbet/rbi/gems/reform-rails.rbi, sorbet/rbi/gems/representable.rbi, sorbet/rbi/gems/rspec-expectations.rbi, sorbet/rbi/gems/rubocop-ast.rbi, sorbet/rbi/gems/sdr-client.rbi, sorbet/rbi/gems/sidekiq.rbi, sorbet/rbi/gems/thor.rbi, sorbet/rbi/gems/turbo-rails.rbi, spec/features/create_new_work_spec.rb
Fixes #978 - an attempt to fix the flappy test
Test suite unflapped?
=> fix test that fails periodically

app/components/works/available_date_component.html.erb
=> Disable the embargo date elements until the embargo radio is selected

app/models/license.rb, spec/models/license_spec.rb
=> Move PDDC license below the ODC licenses

app/components/dashboard/in_progress_row_component.html.erb, app/components/dashboard/in_progress_row_component.rb
=> Collection name for progress bar on dashboard links to the collection

app/components/works/form_component.html.erb, app/javascript/stylesheets/workEditor.scss
=> Add instructions about filling in all fields

app/components/dashboard/deposit_progress_component.rb, app/components/works/detail_component.rb, app/models/abstract_contributor.rb, app/models/work.rb, db/migrate/20210202044303_rename_contributors.rb, db/structure.sql, spec/factories/works.rb, spec/models/work_spec.rb
Rails isn't as clever with STI as I had thought. It was complaining of Author records in the contributors table.
Fixes #982
=> Rename the contributors table to abstract_contributors

app/components/works/add_files_component.html.erb, app/models/author.rb, app/models/contributor.rb, sorbet/rails-rbi/models/abstract_contributor.rbi, sorbet/rails-rbi/models/author.rbi, sorbet/rails-rbi/models/contributor.rbi
Fixes #937 - link contact us text to modal
=> link contact us text in file upload box to modal

app/components/dashboard/in_progress_row_component.html.erb, app/javascript/stylesheets/dashboard.scss, sorbet/rails-rbi/models/collection.rbi
Fixes #945 - show work status in the "in progress" section of the dashboard
~~HOLD: waiting to verify that the status text should be the same as other parts of the dashboard instead of what is shown in the mockup and design doc, see https://github.com/sul-dlss/happy-heron/issues/945#issuecomment-773653948~~
=> add work state to in progress dashboard

app/components/works/dates_component.rb, app/components/works/publication_date_component.rb, spec/components/works/dates_component_spec.rb, spec/components/works/publication_date_component_spec.rb
Fixes #963 
New component tests
n/a
=> Doesn't select values for missing Month and Day in EDTF dates

app/components/works/agreement_component.html.erb, app/javascript/stylesheets/workEditor.scss, spec/components/works/agreement_component_spec.rb
Fixes #970 
Adjusted component test
n/a
=> Terms of Deposit now a section

app/forms/draft_work_form.rb, app/validators/embargo_date_validator.rb, spec/requests/create_collection_spec.rb, spec/validators/embargo_date_validator_spec.rb
=> Validate that the embargo is in the future

app/components/breadcrumb_nav_component.html.erb
=> Remove unnecessary outer nav element

app/components/collections/form_component.html.erb
=> Associate the label with the input element

app/components/works/license_component.html.erb
=> Add a link to get help selecting a license

app/components/collections/detail_component.html.erb, app/components/collections/information_component.html.erb, app/components/collections/links_component.html.erb, app/components/collections/participants_component.html.erb, app/components/collections/release_component.html.erb, app/components/collections/terms_of_use_component.html.erb, app/components/collections/workflow_review_component.html.erb, app/components/works/detail_component.html.erb, app/javascript/stylesheets/details.scss, app/javascript/stylesheets/main.scss, spec/components/collections/links_component_spec.rb
=> Use captions to describe the table rather than table headers

app/javascript/stylesheets/frontpage.scss
we're not using these anymore.
=> Remove unused styles

app/components/works/license_component.rb, spec/components/works/license_component_spec.rb
Fixes #1004 
Added new component test
n/a
=> Use Default License from Collection if missing from Work

package.json, yarn.lock
=> Upgrade bootstrap to 5.0.0-beta2

app/components/popover_component.html.erb, app/components/popover_component.rb, app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/popover_controller.js, app/javascript/packs/application.js, app/javascript/stylesheets/workTypes.scss, config/locales/en.yml, spec/components/popover_component_spec.rb
=> Add tooltips to the select worktype mockup

app/components/dashboard/continue_work_modal_component.html.erb, app/components/dashboard/continue_work_modal_component.rb, app/controllers/dashboards_controller.rb, app/javascript/controllers/popup_modal_controller.js, app/models/user.rb, app/presenters/dashboard_presenter.rb, app/views/dashboards/show.html.erb, spec/components/dashboard/continue_work_modal_component_spec.rb, spec/components/dashboard/in_progress_collection_component_spec.rb, spec/components/dashboard/in_progress_component_spec.rb, spec/features/delete_draft_work_spec.rb, spec/features/edit_draft_work_spec.rb
=> Popup a modal to continue working on a deposit

db/migrate/20210209204542_create_work_versions.rb
=> Fix the migration so that an integer is expected rather than a User

app/components/citation_modal_component.html.erb, app/javascript/controllers/clipboard_controller.js, app/javascript/controllers/show_citation_controller.js, spec/components/citation_modal_component_spec.rb
=> Add a copy citation link

app/services/collection_generator.rb, app/services/request_generator.rb, spec/services/collection_generator_spec.rb, spec/services/request_generator_spec.rb
This is needed for rabbitMQ, but will also fix #1062
=> Make source ids unique

app/validators/work_subtype_validator.rb, spec/validators/work_subtype_validator_spec.rb
=> Mixed material subtypes can be any two options in the full list

app/views/layouts/application.html.erb
Because Amy was able to load two stylesheets at the same time.
=> Switch tubolinks directives to turbo directives

config/locales/en.yml
=> Update the tooltip text for subtype selection on the work type modal

.circleci/config.yml
=> Update the circleci orb

app/components/works/available_date_component.rb, app/components/works/publication_date_component.rb, app/javascript/controllers/auto_citation_controller.js, spec/features/auto_citation_spec.rb, spec/features/create_new_work_spec.rb
Fixes #655 
New feature test of automatic citation 
n/a
=> Automatic citation now generates year based on current year, embargo date, or publication year

app/components/works/contributor_row_component.rb, app/models/abstract_contributor.rb, spec/components/works/contributor_row_component_spec.rb
=> Add Department as a contributor role

app/components/works/edit_link_component.rb, app/models/work_version.rb, spec/models/work_version_spec.rb
=> Display edit button when work is deposited

app/views/welcome/show.html.erb
=> Hide icons from aria

README.md
So that everyone can understand how this thing works.
=> Add documentation about how we're using RabbitMQ and Sneakers

app/validators/embargo_date_validator.rb, spec/validators/embargo_date_validator_spec.rb
Fixes #923 
New unit tests
n/a
=> Embargo Validator now check's Collection Duration

app/policies/dashboard_policy.rb, spec/features/delete_draft_work_spec.rb, spec/policies/dashboard_policy_spec.rb, spec/requests/dashboards_spec.rb
=> Allow depositors to see the dashboard

app/services/types_generator.rb, spec/services/types_generator_spec.rb
=> Don't raise errors when there is no subtype derived genre

app/services/collection_observer.rb, spec/services/collection_observer_spec.rb
=> Fix CollectionObserver after version split

app/services/collection_observer.rb, spec/jobs/deposit_status_job_spec.rb, spec/models/work_version_spec.rb
=> Provide the correct attribute to the collection activity mailer

Gemfile, Gemfile.lock, README.md, config/deploy.rb
=> Use capistrano to manage sneakers

app/components/collections/create/form_component.html.erb, app/components/collections/update/details_form_component.html.erb, app/components/collections/update/settings_form_component.html.erb, app/components/works/contact_email_row_component.html.erb, app/components/works/contact_email_row_component.rb, app/components/works/form_component.html.erb, app/controllers/collection_versions_controller.rb, app/forms/draft_collection_version_form.rb, spec/components/works/contact_email_row_component_spec.rb, spec/requests/edit_collection_version_spec.rb
=> Show the error for emails

app/components/collections/create/form_component.html.erb, spec/requests/create_collection_spec.rb
=> Remove errors from top of the collection details edit page

app/components/collections/create/buttons_component.rb, app/components/collections/update/details_form_component.html.erb, app/components/collections/update/settings_form_component.html.erb, app/components/works/buttons_component.html.erb
Better spacing for cancel buttons
Localhost
=> add classes to cancel button for better spacing

app/models/abstract_contributor.rb, spec/models/contributor_spec.rb
=> Ensure that Department is a valid role

Gemfile, Gemfile.lock, app/services/file_generator.rb, spec/services/request_generator_spec.rb
To test changes before they go to prod.
Will be tested in QA/stage.
None
=> Bump underlying cocina model that uses publish attr

Gemfile, Gemfile.lock, app/services/structural_generator.rb, spec/services/request_generator_spec.rb
=> Bump cocina-models to 0.55.0

Gemfile, Gemfile.lock
=> Updated sdr-client.

app/services/description_generator.rb, sorbet/custom/cocina-models.rbi, spec/services/description_generator_spec.rb
To align H2 with dor-services-app.
Unit
NA
=> Access mapping

config/mappings/types_to_genres.yml, config/mappings/types_to_resource_types.yml, spec/services/description_generator_spec.rb, spec/services/request_generator_spec.rb, spec/services/types_generator_spec.rb
Align with dor-services-app mapping. Use examples from dor-services-app.
Unit
NA
=> Updated types/form generation.

app/services/description_generator.rb, app/services/related_links_generator.rb, sorbet/custom/cocina-models.rbi, spec/services/collection_generator_spec.rb, spec/services/description_generator_spec.rb
To keep in sync with dor-services-app examples.
Unit
NA
=> Update related item mapping.

app/services/description_generator.rb, spec/factories/work_versions.rb, spec/services/description_generator_spec.rb
Keep H2 and dor-services-app in sync.
Unit
NA
=> Update mappings for events.

config/mappings/types_to_genres.yml, spec/services/types_generator_spec.rb
=> Add tech manual genre for software.

Gemfile.lock
Use the latest models and gems.
CI
None
=> Bump cocina-models and related gems

Gemfile, Gemfile.lock, app/services/access_generator.rb, app/services/collection_generator.rb, spec/services/access_generator_spec.rb, spec/services/collection_generator_spec.rb
Make necessary changes for deposits as required by changes for access/embargo in cocina model.
Unit
NA
=> Access/embargo changes for updates in cocina model.

app/models/license.rb, app/services/access_generator.rb, config/licenses.yml, spec/models/license_spec.rb, spec/services/access_generator_spec.rb, spec/services/request_generator_spec.rb
=> Transfer license to SDR

config/licenses.yml
=> Switch to cannonical URL for ODBL

app/services/collection_observer.rb, config/locales/en.yml
=> Set a translation key for settings_updated

app/forms/draft_work_form.rb, spec/forms/work_form_spec.rb
Maybe part of the solution for #1352 
New unit test
n/a
=> Removes expired embargo dates from Work Form

.rubocop.yml, app/controllers/application_controller.rb, app/models/collection_change_set.rb
=> Add new rubocop rules

app/controllers/application_controller.rb, app/models/user.rb
=> Add the user to the honeybadger context

package.json, yarn.lock
=> Upgrade to a released version of Bootstrap

app/policies/work_version_policy.rb, spec/policies/work_version_policy_spec.rb
=> Allow reviews by collection managers

app/controllers/works_controller.rb, app/packs/entrypoints/application.scss, app/packs/stylesheets/nextStep.scss, app/views/works/next_step.html.erb, app/views/works/next_step_review.html.erb, config/routes.rb, spec/features/create_new_work_spec.rb, spec/features/edit_draft_work_spec.rb, spec/features/mediated_deposit_versioning_spec.rb
=> Add pages that explain what happens next after a deposit

app/components/works/add_files_component.html.erb, app/components/works/file_row_component.html.erb, app/packs/controllers/dropzone_controller.js, app/packs/stylesheets/dropzone.scss
=> Add validation for files

app/components/related_link_component.html.erb, app/components/works/access_component.html.erb, app/components/works/add_files_component.html.erb, app/components/works/agreement_component.html.erb, app/components/works/authors_and_contributors_component.html.erb, app/components/works/contact_email_row_component.html.erb, app/components/works/contributor_row_component.html.erb, app/components/works/contributor_row_component.rb, app/components/works/contributors_component.html.erb, app/components/works/contributors_component.rb, app/components/works/dates_component.html.erb, app/components/works/description_component.html.erb, app/components/works/embargo_component.html.erb, app/components/works/form_component.html.erb, app/components/works/license_component.html.erb, app/components/works/related_work_component.html.erb, app/components/works/title_component.html.erb, spec/components/works/agreement_component_spec.rb, spec/components/works/contributors_component_spec.rb
Fixes #1391 
- Adds '*' to required fields
- Update text to "* REQUIRED FIELDS*
- Removes (optional) where unnecessary.
Updated tests when looking for text
=> Update required field labels and remove optional text for works

config/initializers/devise.rb
To support capital letters and more than one subdomain
Fixes #1340
=> Update email regex

app/packs/controllers/date_validation_controller.js
=> Prevent submission when dates are in the future

app/views/works/next_step.html.erb, app/views/works/next_step_review.html.erb
=> Move the instructions steps to the correct partials

app/components/works/contributor_row_component.html.erb, app/components/works/subtypes_component.html.erb, spec/components/works/subtypes_component_spec.rb
Fixes #1451 
Updated unit tests
=> Update work subtypes to remove optional

app/components/works/dates_component.html.erb, app/components/works/dates_component.rb, app/packs/controllers/date_range_controller.js
=> Ensure the range is valid before allowing deposit

app/packs/modules/validate-forms.js
=> Scroll to first invalid element on the form

app/forms/collection_settings_form.rb, app/forms/draft_collection_form.rb, spec/features/remove_duplicate_depositors_spec.rb
Fixes #1269 
New feature test
n/a
=> Ensures depositors are unique

app/components/dashboard/collection_component.html.erb, app/components/dashboard/collection_component.rb, app/models/collection.rb, app/models/collection_version.rb, app/models/work.rb, app/models/work_version.rb, app/policies/work_policy.rb, app/views/dashboards/_collection_summary.html.erb, app/views/dashboards/_collection_summary_row.html.erb, app/views/dashboards/show.html.erb, spec/components/dashboard/collection_component_spec.rb, spec/factories/collection_versions.rb, spec/factories/work_versions.rb, spec/models/work_version_spec.rb
=> Depositors should only see their works in the collection table

app/components/first_draft_collections/update/form_component.html.erb, config/environments/development.rb
=> Add missing close tag

app/components/dashboard/collection_header_component.html.erb, app/components/dashboard/collection_header_component.rb, spec/components/dashboard/collection_header_component_spec.rb, spec/requests/dashboards_spec.rb
=> Only show edit button to people who are allowed to edit

app/components/dashboard/all_collections_component.html.erb, app/controllers/searches_controller.rb, app/packs/controllers/find_druid_controller.js, config/routes.rb, spec/requests/search_spec.rb
=> Provide a way for an admin to jump to the page for a druid

app/components/dashboard/all_collections_component.html.erb, app/packs/entrypoints/application.scss, app/packs/stylesheets/allCollections.scss
Add a button to expand it
Fixes #1338
=> Collapse the All Collections table by default

app/components/works/work_type_modal_component.html.erb, app/packs/stylesheets/workTypes.scss
=> Layout subtype options column first

app/controllers/works_controller.rb, app/mailers/collections_mailer.rb, app/models/work_version.rb, app/services/collection_observer.rb, app/views/collections_mailer/first_draft_created.html.erb, app/views/collections_mailer/item_deposited.html.erb, app/views/collections_mailer/version_draft_created.html.erb, spec/jobs/deposit_status_job_spec.rb, spec/mailers/collections_mailer_spec.rb, spec/models/work_version_spec.rb, spec/requests/edit_work_spec.rb
Each is specific to a particular situation.
Fixes #882
=> Split collection notification into 3 separate notifications

app/components/works/available_date_component.rb, spec/components/works/available_date_component_spec.rb
=> Display embargo requirement inline

app/components/works/available_date_component.html.erb, app/packs/controllers/auto_citation_controller.js
=> Don't use the embargo date for the citation unless embargo is selected

app/components/works/form_component.rb
This will prevent any confusin if the implementation of persisted? on the work_form changes
=> [refactor] Delegate persistence to the form

app/components/collections/participants_component.html.erb, app/components/collections/release_component.html.erb, app/components/collections/show/details_header_component.html.erb, app/components/collections/show/settings_header_component.html.erb, app/components/collections/terms_of_use_component.html.erb, app/components/collections/workflow_review_component.html.erb, app/components/dashboard/collection_header_component.html.erb, app/components/dashboard/in_progress_row_component.html.erb
Otherwise it tries to resolve the link within the frame
=> Set the turbo-frame target to be the top of the page

app/components/works/embargo_component.html.erb, config/locales/en.yml
=> Add display text for visibility properly

config/schedule.rb, lib/tasks/cleanup.rake
=> Add rake task to clean up unattached files after 7 days

app/views/helps/create.turbo_stream.erb, spec/features/help_modal_spec.rb
=> Update the help modal text for the contact form

app/controllers/first_draft_collections_controller.rb, spec/requests/create_collection_spec.rb
=> Redirect to the collection page on deposit

app/components/collections/works_component.html.erb, app/components/purl_check_link_component.html.erb, app/components/purl_check_link_component.rb, app/components/works/detail_component.html.erb, app/components/works/edit_link_component.html.erb, spec/components/purl_check_link_component_spec.rb
Fixes #1319 
Unit and feature tests
n/a
=> Show Work Type Modal in Work Detail if purl_reservation is True

app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb, spec/features/create_new_work_spec.rb
closes #1339
Pretty
Unit, locally
NA
=> Formats EDTF dates.

app/controllers/collections_controller.rb, app/services/collection_observer.rb, spec/requests/edit_collection_spec.rb, spec/services/collection_observer_spec.rb
=> Refactor method name

README.md, app/components/works/detail_component.html.erb, app/jobs/record_embargo_release_job.rb, app/models/event.rb, config/locales/en.yml, db/migrate/20210527193102_change_event_to_allow_nil_user.rb, db/structure.sql, lib/tasks/rabbitmq.rake, spec/components/works/detail_component_spec.rb, spec/factories/events.rb, spec/jobs/record_embargo_release_job_spec.rb
Fixes #1347
Tested on stage: https://sul-h2-stage.stanford.edu/works/17385
=> Log an event when the embargo is lifted

app/components/works/file_row_component.html.erb, app/packs/controllers/dropzone_controller.js, spec/features/create_new_work_spec.rb
Fixes #1327
Tested in a feature test.
n/a
=> DropZone checks for duplicate filenames

Gemfile.lock
New version of cocina-models.  see https://app.honeybadger.io/projects/77112/faults/78457297
=> bump cocina models to avoid mismatch

app/views/shared/_terms_of_deposit.html.erb, config/settings.yml
Fixes #1534 
Testing suite
`config/settings.yml`
=> New FAQs link to Terms of Deposit modal

app/components/works/available_date_component.html.erb, app/components/works/available_date_component.rb, app/packs/controllers/available_date_controller.js
=> Ensure the embargo date is in the future

app/components/dashboard/all_collections_row_component.html.erb, app/components/dashboard/all_collections_row_component.rb, spec/components/dashboard/all_collections_row_component_spec.rb, spec/requests/dashboards_spec.rb
=> Add a link to the works in the collection from the admin table

app/components/citation_modal_component.html.erb, app/components/collections/detail_component.html.erb, app/components/collections/links_component.html.erb, app/components/collections/work_row_component.html.erb, app/components/popover_component.html.erb, app/components/works/file_row_component.html.erb, app/components/works/show/files_component.html.erb, app/components/works/work_type_modal_component.html.erb, app/views/welcome/show.html.erb, app/views/works/_edit_button.html.erb, app/views/works/next_step_review.html.erb
I believe this improves accessability
See https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/accessibility
=> Mark icons as aria-hidden

app/components/works/version_description_component.html.erb
Ref https://github.com/sul-dlss/happy-heron/issues/1574#issuecomment-854725760
=> Add asterisk by 'Version your work' to indicate it's required

app/models/work_version.rb
=> Allow nilable in Type Signature

app/components/collections/version_description_component.html.erb, spec/components/collections/version_description_component_spec.rb
See https://github.com/sul-dlss/happy-heron/issues/1574#issuecomment-854725760
=> Update text for version your collection

Gemfile.lock
=> Update sdr-client (for cocina-models 0.60.0)

app/components/collections/history_component.html.erb, app/components/collections/information_component.rb, app/components/local_time_component.rb, app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, app/packs/entrypoints/application.js, config/locales/en.yml, package.json, spec/components/local_time_component_spec.rb, yarn.lock
=> Draw timestamps in the local zone

Gemfile.lock
This reverts commit 9a07bc3095210eb913cc8aa4bd1ab7eb99a80649.
=> Revert "Update sdr-client (for cocina-models 0.60.0)"

app/models/collection_version.rb, spec/models/collection_version_spec.rb, spec/services/collection_observer_spec.rb
=> Send email to managers on collection deposit

config/licenses.yml, spec/models/license_spec.rb
=> Update unsupported license labels

app/components/works/show/files_component.html.erb, spec/components/works/show/files_component_spec.rb
=> Status for hide file decodes to 'Yes' and 'No'

app/components/works/author_row_component.html.erb, app/components/works/author_row_component.rb, app/components/works/authors_component.html.erb, app/components/works/contributor_role_component.rb, app/components/works/contributor_row_component.html.erb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/models/work_version.rb, app/packs/controllers/nested_form_controller.js, app/packs/controllers/ordered_nested_form_controller.js, db/migrate/20210608161622_add_weight_to_abstract_contributor.rb, db/structure.sql, spec/components/works/author_row_component_spec.rb, spec/components/works/contributor_role_component_spec.rb, spec/models/work_version_spec.rb, spec/requests/create_work_spec.rb
=> Allow Authors to be reordered

app/controllers/collection_versions_controller.rb, app/services/collection_version_event_description_builder.rb, spec/services/collection_version_event_description_builder_spec.rb
=> Collection events track information about what changed

app/controllers/work_versions_controller.rb, app/controllers/works_controller.rb, spec/features/delete_draft_work_spec.rb
Fixes #1149 
Feature test updated
=> Redirect to collection works page after discarding a draft work

app/packs/stylesheets/palette.scss
=> Refactor palette and add some comments

app/packs/stylesheets/bootstrapVariables.scss, app/packs/stylesheets/collection.scss
This helps align with the mockups.
=> Make the link-color digital-blue

app/packs/stylesheets/dashboard.scss
closes #1632
Fix indent.
Local
NA
=> Remove indent under your Collections.

app/components/dashboard/approvals_component.html.erb, app/packs/controllers/datatable_approvals_controller.js
=> Add datatable controller for sorting the approvals table

spec/services/description_generator_spec.rb, spec/services/request_generator_spec.rb, spec/services/types_generator_spec.rb
Make it easy to find these tests
CircleCI
n/a
=> Xit tests failing because of new type mapping

app/components/first_draft_collections/create/details_component.html.erb
closes #791
Better data entry.
Local
NA
=> Changes collection description to a text area.

app/components/works/form_component.rb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/forms/keywords_populator.rb, app/forms/work_form.rb, app/services/work_version_event_description_builder.rb, db/migrate/20210616201626_allow_null_fields.rb, db/structure.sql, spec/requests/create_work_spec.rb, spec/services/work_version_event_description_builder_spec.rb
=> Track changes for works

Gemfile, Gemfile.lock, package.json, yarn.lock
=> Upgrade turbo-rails

app/packs/entrypoints/application.scss, app/packs/stylesheets/collections.scss, app/views/dashboards/show.html.erb
closes #1633
Per ticket
Local
NA
=> Add toggling for your collections.

app/packs/stylesheets/bootstrapVariables.scss
This aligns with the design comps
=> Remove link underline

app/components/collections/information_component.rb, spec/components/collections/information_component_spec.rb
closes #789
Per ticket.
Unit
NA
=> Adds version comment for collections.

app/components/citation_component.rb, app/packs/entrypoints/application.scss, app/packs/stylesheets/citationButton.scss, spec/components/citation_component_spec.rb
=> disable citation component when the work isn't published

app/components/works/detail_component.html.erb
=> Remove data from the release header

app/views/welcome/show.html.erb
=> Fix a broken html tag

app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb
=> Display the depositor name

app/components/collections/information_component.rb, spec/components/collections/information_component_spec.rb
refs #789
I got it wrong the first time.
Unit
NA
=> Fixed the description that is displayed as version comment.

app/components/collections/show/settings_header_component.html.erb, app/components/collections/show/settings_header_component.rb, app/components/collections/work_row_component.html.erb, app/components/collections/work_row_component.rb, app/components/collections/works_component.html.erb, app/components/purl_check_link_component.rb, app/components/works/detail_component.html.erb, app/components/works/edit_link_component.rb, app/controllers/works_controller.rb, app/views/collections/_collection.html.erb, app/views/works/index.html.erb, spec/components/collections/works_component_spec.rb, spec/features/purl_reservation_spec.rb, spec/requests/show_works_in_collection_spec.rb
=> Allow setting type on a registered purl from collection member list

app/components/collections/works_component.html.erb
closes #1675
Correct sorting
QA
NA
=> Sets date format for sorting by modified date in works list table.

app/components/collections/works_component.html.erb, app/components/collections/works_component.rb, app/packs/controllers/datatable_works_controller.js, spec/components/collections/works_component_spec.rb
closes #787
Per ticket.
Unit, local
NA
=> Hides depositor column when user is depositor.

app/components/works/detail_component.html.erb, app/packs/controllers/copy_controller.js, app/packs/entrypoints/application.scss, app/packs/stylesheets/copyButton.scss, app/views/dashboards/_collection_summary_row.html.erb
closes #1034
Per ticket.
Local
NA
=> Adds PURL copy button.

app/components/works/file_row_component.html.erb
closes #1708
Fix styling for readability.
Local
NA
=> Fix styling of previously saved filenames.

config/mappings/types_to_genres.yml, config/mappings/types_to_resource_types.yml, spec/factories/work_versions.rb, spec/requests/create_work_spec.rb, spec/services/description_generator_spec.rb, spec/services/request_generator_spec.rb, spec/services/types_generator_spec.rb
Part of #1392 
n/a
H2 mappings in dor-services-app
Requires further work to update code and other tests to reflect the mapping changes.
Implementation ticket #1435
=> Revised type mapping

config/environments/production.rb
=> Allow new-sdr for action cable

Gemfile, Gemfile.lock
=> Update sdr-client to 0.58.0 (cocina-models to 0.61.0)

package.json, yarn.lock
This fixes https://github.com/sul-dlss/happy-heron/security/dependabot/yarn.lock/css-what/open
=> Upgrade css-minimizer-webpack-plugin

app/services/work_version_event_description_builder.rb, spec/factories/collections.rb, spec/services/work_version_event_description_builder_spec.rb
Fixes #1719
locally and with unit tests
=> history shows embargo modified only when it's so

.rubocop.yml, app/components/works/dates_component.rb, app/mailers/collections_mailer.rb, spec/components/popover_component_spec.rb, spec/components/works/link_to_show_component_spec.rb, spec/features/create_new_work_spec.rb, spec/mailers/collections_mailer_spec.rb, spec/mailers/reviewers_mailer_spec.rb, spec/mailers/works_mailer_spec.rb, spec/requests/create_work_spec.rb, spec/services/description_generator_spec.rb
adding new cops.
rubocop and rspec.
=> add rubocops

app/packs/stylesheets/bootstrapVariables.scss
closes #1752
Accessibility
Local
NA
=> Adds link underline for hover.

.rubocop.yml, app/services/description_generator.rb, sorbet/custom/cocina-models.rbi, spec/factories/works.rb, spec/services/description_generator_spec.rb, spec/services/request_generator_spec.rb
closes #1777
Complete DRO request.
Unit
NA
=> Adds admin metadata to cocina request.

app/views/works/next_step.html.erb, app/views/works/next_step_review.html.erb
=> Link titles on next step pages.

app/views/reviewers_mailer/submitted_email.html.erb, spec/mailers/reviewers_mailer_spec.rb
=> Add a direct link to the work under review in the email

app/components/works/keywords_row_component.html.erb, app/controllers/autocomplete_controller.rb, config/settings.yml, spec/features/create_new_work_spec.rb, spec/requests/autocomplete_spec.rb
closes #1755
More relevant results.
Unit, QA
NA
=> Switches autocomplete to use OCLC Fast endpoint.

spec/requests/edit_work_spec.rb
=> Fix lint error.

app/packs/controllers/datatable_approvals_controller.js, app/packs/controllers/datatable_collections_controller.js, app/packs/controllers/datatable_works_controller.js, app/packs/stylesheets/collection.scss, app/packs/stylesheets/collections.scss
closes #1742
Per ticket.
Local
NA
=> Switch datatables to disable search via config. Enable search for works.

app/models/license.rb, config/licenses.yml, spec/models/license_spec.rb
closes #1747
Per ticket
Locally
=> Adds public domain mark.

app/packs/modules/validate-forms.js
closes #1763
Better UX
Locally
NA
=> Prevent submitting a draft with an incomplete range.

app/services/orcid_service.rb, spec/services/orcid_service_spec.rb
closes #1733
Support looking up a name via ORCID id.
Unit, local.
NA
=> Adds ORCID service.

app/packs/entrypoints/application.js
=> Switch turbolinks to turbo.

app/jobs/assign_pid_job.rb, spec/jobs/assign_pid_job_spec.rb
=> If the druid_assigned message comes back with a DOI, persist it

Gemfile, Gemfile.lock, app/jobs/deposit_job.rb, spec/jobs/deposit_job_spec.rb
=> Request that a DOI be assigned when calling the SDR API

.rubocop.yml, app/controllers/dashboards_controller.rb, app/packs/controllers/work_type_controller.js, app/presenters/dashboard_presenter.rb, app/views/dashboards/show.html.erb, spec/requests/dashboards_spec.rb
Fixes #1703
Added to request spec for dashboards controller.
=> Deposits in progress includes 'PURL Reserved'

app/components/collections/release_component.html.erb, app/components/collections/release_component.rb, sorbet/rails-rbi/models/collection.rbi, spec/components/collections/release_component_spec.rb
closes #1727
Per ticket
Unit
NA
=> Adds DOI assignment to collection view page.

app/services/request_generator.rb, spec/services/request_generator_spec.rb
=> Add the doi to the request

app/components/collections/show/details_header_component.html.erb, app/components/collections/show/settings_header_component.html.erb, app/components/purl_check_link_component.html.erb, app/packs/controllers/purl_reservation_controller.js, app/packs/controllers/work_type_controller.js, app/views/collections/_deposit_button.html.erb, app/views/works/_edit_button.html.erb
=> [Refactor] Camel case javascript methods

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb
=> View item doi

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb
=> View item doi setting

app/components/works/doi_component.html.erb, app/components/works/doi_component.rb, app/components/works/embargo_component.html.erb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/models/work.rb, app/services/work_version_event_description_builder.rb, db/migrate/20210715161256_change_add_doi_default.rb, db/structure.sql, spec/components/works/doi_component_spec.rb, spec/components/works/embargo_component_spec.rb, spec/jobs/deposit_job_spec.rb, spec/models/work_spec.rb, spec/services/work_version_event_description_builder_spec.rb
closes #1728
Per ticket
Unit
NA
=> Updates item deposit form with new DOI assignment section.

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb
=> Lists keywords on separate lines.

app/components/works/description_component.html.erb, app/packs/entrypoints/application.scss, app/packs/stylesheets/switch.scss, spec/features/create_new_work_spec.rb
closes #1815
Usability
Unit, local
NA
=> Changes auto-generated citation switch.

spec/services/cocina_generator/description/generator_spec.rb
So H2 produces the cocina that dor-services-app expects.
CircleCI
n/a
=> Update general mappings to match dor-services-app

app/packs/stylesheets/frontpage.scss, app/packs/stylesheets/suNavbar.scss, app/views/layouts/application.html.erb, app/views/welcome/show.html.erb, config/settings.yml
=> Adds additional links to home page.

app/components/works/subtypes_component.html.erb
closes #1828
Accessability
Local
NA
=> Group and label work types.

app/components/works/embargo_component.rb, spec/components/works/embargo_component_spec.rb
closes #1741
Per ticket.
Unit
NA
=> Do not allow changing release setting when item has been released.

app/services/cocina_generator/description/contributors_generator.rb, app/services/cocina_generator/description/generator.rb, spec/services/cocina_generator/description/contributors_generator_spec.rb, spec/services/cocina_generator/description/generator_spec.rb, spec/services/cocina_generator/dro_generator_spec.rb
=> Generator spec

app/services/request_generator.rb, config/settings.yml, spec/services/request_generator_spec.rb
=> Set a DOI when requested on subsequent versions

app/services/cocina_generator/description/contributors_generator.rb, app/services/cocina_generator/description/generator.rb, spec/services/cocina_generator/description/contributors_generator_spec.rb, spec/services/cocina_generator/description/generator_spec.rb
=> Re-revert contributor type changes. 

app/components/collections/settings_component.html.erb, app/components/collections/update/depositors_component.html.erb, app/components/collections/update/depositors_component.rb, app/components/collections/update/managers_component.html.erb, app/components/collections/update/managers_component.rb, app/components/collections/update/reviewers_component.html.erb, app/components/collections/update/reviewers_component.rb, spec/components/collections/update/depositors_component_spec.rb, spec/components/collections/update/managers_component_spec.rb, spec/components/collections/update/reviewers_component_spec.rb
This is a necessary step to adding nested forms for the contributors. See #1036
=> [Refactor]  Extract components for the form contributors 

app/components/works/file_row_component.html.erb, app/packs/controllers/dropzone_controller.js, app/packs/modules/validate-forms.js, app/packs/stylesheets/dropzone.scss, spec/features/create_new_work_spec.rb
closes #1577
Sometimes users go down the unhappy path.
Local
NA
=> Display file upload errors.

Gemfile, Gemfile.lock
The previous version was missing some definitions for rails.
=> Upgrade sorbet-rails to the latest

app/models/orcid.rb, app/services/cocina_generator/description/contributors_generator.rb, sorbet/rails-rbi/models/abstract_contributor.rbi, sorbet/rails-rbi/models/author.rbi, sorbet/rails-rbi/models/contributor.rbi, spec/models/orcid_spec.rb, spec/services/cocina_generator/description/contributors_generator_spec.rb
closes #1843
Per ticket
Unit
NA
=> Adds ORCID to cocina model when depositing.

app/components/collections/works_component.rb, app/components/dashboard/collection_component.html.erb, app/components/dashboard/collection_component.rb, app/policies/collection_policy.rb, app/policies/work_version_policy.rb, app/views/dashboards/_collection_summary_row.html.erb, spec/components/dashboard/collection_component_spec.rb, spec/policies/collection_policy_spec.rb
closes #1035
Per ticket
Unit, local
=> Show depositor in your collections tables when user is reviewer.

app/components/works/embargo_component.rb, app/forms/work_form.rb, app/models/work.rb, spec/forms/work_form_spec.rb
=> Don't expect release to be present when the component isn't

app/controllers/dashboards_controller.rb, app/controllers/helps_controller.rb, app/controllers/welcome_controller.rb, app/views/helps/create.turbo_stream.erb, app/views/helps/new.html.erb, app/views/welcome/first_time.html.erb, config/routes.rb, db/structure.sql, spec/features/help_modal_spec.rb, spec/features/welcome_spec.rb, spec/requests/dashboards_spec.rb
=> Take users without permissions to the contact page

Gemfile, Gemfile.lock
=> Add addressable as a direct dependency

app/components/collections/update/reviewers_component.html.erb
=> Reviewers component should use reviewers (not depositors)

app/views/works_mailer/approved_email.html.erb, app/views/works_mailer/deposited_email.html.erb, app/views/works_mailer/new_version_deposited_email.html.erb, spec/mailers/works_mailer_spec.rb
=> Mail the doi link in the notifications

app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb
=> Update text shown when user chooses not to assign a DOI

app/packs/controllers/contributors_controller.js, spec/features/create_new_work_spec.rb
=> Add better front-end validation for orcid

.rubocop.yml
=> Enable new rubocops.

app/services/cocina_generator/description/types_generator.rb, config/mappings/types_to_resource_types.yml, spec/services/cocina_generator/description/generator_spec.rb, spec/services/cocina_generator/description/types_generator_spec.rb, spec/services/cocina_generator/dro_generator_spec.rb
=> Export the datacite form to cocina

spec/support/capybara.rb
closes #1977
Less flapping.
Unit
=> Ignore PendingConnectionsError.

app/components/works/purl_reservation_modal_component.html.erb, app/forms/reservation_form.rb, app/packs/controllers/purl_reservation_controller.js, app/packs/entrypoints/application.scss, app/packs/stylesheets/purlReservationModal.scss, app/views/collections/_deposit_button.html.erb, spec/features/purl_reservation_spec.rb
closes #1985
Per ticket
Unit
NA
=> Provide DOI option when reserving a PURL.

app/components/works/contributor_row_component.html.erb, app/packs/stylesheets/workEditor.scss
=> Adjust spacing for contributor.

config/settings.yml
=> Update terms of deposit link

config/mappings/types_to_resource_types.yml
=> Resource type term fixes

app/services/cocina_generator/description/collection_description_generator.rb, app/services/cocina_generator/description/generator.rb, spec/requests/create_collection_spec.rb, spec/services/cocina_generator/collection_generator_spec.rb
=> Send collection description to SDR

.circleci/config.yml, .rubocop.yml, app/forms/attached_files_populator.rb, app/forms/collection_contributor_populator.rb, app/forms/contact_emails_populator.rb, app/forms/contributor_populator.rb, app/forms/keywords_populator.rb, app/forms/related_links_populator.rb, app/forms/related_works_populator.rb, app/forms/reviewers_populator.rb, app/models/orcid.rb, docker/app/Dockerfile, spec/policies/collection_policy_spec.rb, spec/policies/work_version_policy_spec.rb, spec/rails_helper.rb
=> Test on ruby 3.0

Gemfile, Gemfile.lock
=> Use branch of sdr-client that has a 6 min timeout

.circleci/config.yml
Use v2 of orb to fix bug with code climate
=> Update orb to v2

Gemfile, Gemfile.lock
=> Update turbo-rails to 1.0

README.md, bin/dev
=> Provide default roles/user when starting the dev server

docker/workers/Dockerfile
Docker base image for workers in sync with ruby version of code
Building docker image
=> Update workers Dockerfile base image to ruby3

README.md
Reflect correct version of Ruby used in app
=> Update README's ruby version to 3.0

app/components/works/contributor_row_component.html.erb, app/javascript/controllers/nested_form_controller.js, app/javascript/controllers/ordered_nested_form_controller.js
Fixes #2114
☝🏻 
CI, deployed to stage to make sure console error no longer logged
None
=> Make ordered author button widgets Stimulus targets

README.md
Small reminder about a step needed when testing locally.
Unit tests.
README.md
=> A reminder to create/migrate the db when testing

app/assets/stylesheets/frontpage.scss
part of #2151
deploying to stage
=> Stop using uppercase for Digital Repository on front page

app/views/welcome/show.html.erb
More for #2151
deployed to stage for product owner
=> Digital Repository must have capital R

app/services/cocina_generator/structural/file_generator.rb, app/services/cocina_generator/structural/generator.rb, spec/services/cocina_generator/collection_generator_spec.rb, spec/services/cocina_generator/dro_generator_spec.rb
Ref https://github.com/sul-dlss/cocina-models/issues/343
=> Stop hardcoding cocina URIs

app/components/works/agreement_component.html.erb, app/components/works/agreement_component.rb
It's preferable to put code in classes rather than templates.
Test suite.
=> Refactor agreement to pull code out of the template and into the class

app/components/works/agreement_component.html.erb, app/javascript/controllers/available_date_controller.js, app/models/user.rb, app/validators/embargo_date_parts.rb, spec/forms/work_form_spec.rb, spec/validators/embargo_date_parts_spec.rb
To avoid https://app.honeybadger.io/projects/77112/faults/85235636
Fixes #2235
=> fix bug with embargo release date and user without recent terms of agreement

README.md, config/initializers/byebug.rb
Because it is helpful to be able to use byebug when debugging.
Localhost
=> add info on how to use byebug

.rubocop.yml, spec/requests/create_collection_spec.rb
Rubocop happiness
Existing tests
=> add new cop and auto-correct

app/models/work_version.rb
Follow on from #2265 based on https://github.com/sul-dlss/happy-heron/pull/2265#discussion_r891179529 
Existing tests
=> add additional code comment about unicode postgres problem

app/models/user.rb, config/locales/en.yml, spec/models/user_spec.rb
=> Validate the format of an email address

.circleci/config.yml
=> Update sul-dlss orb to 3.1.2

README.md
Add info about a useful rake task to the README
=> add some info about rake task to readme

config/environments/production.rb
This was accidentally removed in https://github.com/sul-dlss/happy-heron/commit/0df5e88517d095deaec1109ad22f0087654dfe3f\#diff-da60b4e96eff2b132991226d308949e23f4ef3aad45ad59edd09cbc32cc6251eL71
Fixes #2374
=> Set asset_host for action_mailer

.rubocop.yml, Gemfile.lock, app/components/works/detail_component.rb, app/components/works/embargo_component.rb, spec/components/works/embargo_component_spec.rb, spec/factories/related_works.rb, spec/mailers/reviewers_mailer_spec.rb, spec/requests/autocomplete_spec.rb, spec/requests/create_work_spec.rb, spec/requests/edit_collection_link_spec.rb, spec/requests/edit_collection_version_link_spec.rb, spec/services/cocina_generator/description/generator_spec.rb
Add new cops and autocorrect/manually correct.
Existing tests
=> add new cops and correct

config/application.rb
Keep up to date and make deprecations go away.
=> Switch to using Rails 7 defaults

app/components/works/contact_email_row_component.html.erb, app/components/works/keywords_row_component.html.erb
=> Remove unused attribute

app/controllers/admins_controller.rb, app/policies/admin_dashboard_policy.rb, app/views/admins/show.html.erb, config/routes.rb, spec/requests/admins_spec.rb
=> Add an admin dashboard page

app/views/layouts/application.html.erb
=> Fix header spacing for bootstrap 5.2

README.md
=> Remove sorbet cruft from Readme

docker-compose.yml
=> Update PG to match production (12.9)

app/javascript/controllers/year_field_controller.js
=> Remove cruft

config/mappings/types_to_genres.yml, config/mappings/types_to_resource_types.yml
=> Add content subtypes

.rubocop.yml
=> Rubocop tweaks.

app/models/work_version.rb, db/migrate/20220812205204_add_publication_date_to_work_version.rb, db/structure.sql, spec/models/work_version_spec.rb
=> Store the publication date on a work version when it is published

README.md
=> Removed branch aliasing section from README

.circleci/config.yml, README.md, app/jobs/deposit_status_job.rb, db/seeds.rb, spec/jobs/deposit_status_job_spec.rb
closes #2402
Correctly display who/what is performing event.
Unit
=> Sets user for Deposited event to SDR.

app/components/admin/navigation_component.html.erb, app/components/admin/navigation_component.rb, app/controllers/admin/users_controller.rb, app/models/user.rb, app/policies/admin_dashboard_policy.rb, app/presenters/admin/user_presenter.rb, app/views/admin/users/index.html.erb, app/views/admins/show.html.erb, config/routes.rb, spec/requests/admin/search_for_user_spec.rb
=> Allow searching for users

db/seeds.rb
So that the sunetid is properly displayed.
=> Change email address for sdr user.

app/models/collection.rb, app/models/work.rb, app/views/admin/users/index.html.erb, spec/models/collection_spec.rb, spec/models/work_spec.rb
=> Display non-namespaced druids on the user search result

app/controllers/admin/users_controller.rb, app/policies/admin_dashboard_policy.rb, app/policies/application_policy.rb, app/policies/user_policy.rb
This makes it less confusing about which policy should be consulted.
Test suite.
=> Separate the UserPolicy from the AdminDashboardPolicy

app/components/admin/navigation_component.rb, app/controllers/admin/collection_reports_controller.rb, app/javascript/controllers/admin_date_range_controller.js, app/models/admin/collections_report.rb, app/policies/collection_report_policy.rb, app/services/admin/collections_csv_generator.rb, app/services/admin/collections_report_query.rb, app/views/admin/collection_reports/new.html.erb, config/routes.rb, spec/features/admin/collections_report_spec.rb, spec/services/admin/collections_csv_generator_spec.rb, spec/services/admin/collections_report_query_spec.rb
=> Adds admin collection report.

app/components/admin/navigation_component.rb, app/controllers/admin/work_reports_controller.rb, app/models/work_report.rb, app/policies/admin/work_report_policy.rb, app/services/admin/work_csv_generator.rb, app/services/admin/work_report_query.rb, app/views/admin/work_reports/new.html.erb, config/locales/en.yml, config/routes.rb, spec/features/admin/work_report_spec.rb, spec/services/admin/work_csv_generator_spec.rb, spec/services/admin/work_report_query_spec.rb
=> Create the report of works

app/components/admin/activity_time_selector_component.html.erb, app/components/admin/activity_time_selector_component.rb, app/components/admin/item_activity_row_component.html.erb, app/components/admin/item_activity_row_component.rb, app/components/admin/items_activity_component.html.erb, app/components/admin/items_activity_component.rb, app/components/admin/items_activity_table_component.html.erb, app/components/admin/items_activity_table_component.rb, app/controllers/admins_controller.rb, app/models/event.rb, app/policies/admin_dashboard_policy.rb, app/views/admins/items_recent_activity.html.erb, app/views/admins/show.html.erb, config/routes.rb, spec/requests/admins_spec.rb
=> Adds recent activity for items to admin page.

app/services/admin/collections_csv_generator.rb, spec/services/admin/collections_csv_generator_spec.rb
=> Drop the namespace of the druid from the collection report

app/assets/stylesheets/work.scss, app/components/works/admin_component.html.erb, app/components/works/admin_component.rb, app/components/works/detail_component.html.erb, app/controllers/work_owners_controller.rb, app/controllers/works_controller.rb, app/javascript/controllers/sunet_input_controller.js, app/policies/work_owner_policy.rb, app/policies/work_version_policy.rb, app/views/shared/_flashes.html.erb, app/views/work_owners/edit.html.erb, app/views/works/_work.html.erb, app/views/works/details.html.erb, config/locales/en.yml, config/routes.rb, spec/components/works/detail_component_spec.rb, spec/features/change_work_owner_spec.rb, spec/requests/show_work_spec.rb
refs #2312
Support admin function.
Unit
=> Support changing work owners.

app/components/admin/collection_activity_row_component.html.erb, app/components/admin/collection_activity_row_component.rb, app/components/admin/collections_activity_component.html.erb, app/components/admin/collections_activity_component.rb, app/components/admin/collections_activity_table_component.html.erb, app/components/admin/collections_activity_table_component.rb, app/controllers/admins_controller.rb, app/policies/admin_dashboard_policy.rb, app/views/admins/collections_recent_activity.html.erb, app/views/admins/show.html.erb, config/routes.rb, spec/requests/admins_spec.rb
=> Displays recent collection activity on admin dashboard.

app/views/first_draft_collections_mailer/first_draft_created.html.erb, spec/mailers/first_draft_collections_mailer_spec.rb
Fixes #2468 - Amy's request in slack.
She already signed off on this code.
=> first_draft_created.html.erb for mailer uses creator's name and email

app/services/admin/collections_report_query.rb, spec/services/admin/collections_report_query_spec.rb
=> Changes collection report sort order to collection name.

app/components/works/dates_component.html.erb, app/javascript/controllers/date_approximate_controller.js
closes #2358
More accurate date entry.
Local, Amy
=> Make days and approximate dates mutually exclusive.

app/components/collections/work_row_component.html.erb, app/components/collections/works_component.html.erb, config/locales/en.yml
On the collection, when looking at the deposits tab, the owner should show rather than the depositor
Fixes #2334
CI
=> Display the owner on the deposits tab

app/controllers/work_owners_controller.rb, spec/requests/change_work_owner_spec.rb
Fixes #2329
Amy tested on stage.
=> Add new owner as a depositor in a collection

app/components/works/description_component.html.erb
=> Adds help text to keyword box.

app/controllers/work_owners_controller.rb, app/mailers/works_mailer.rb, app/views/works_mailer/changed_owner_email.html.erb, spec/mailers/works_mailer_spec.rb, spec/requests/change_work_owner_spec.rb
=> Send email to new owner of item.

app/controllers/reviews_controller.rb, spec/requests/reviews_spec.rb
closes #2094
Less confusing
Unit
=> Use approver for depositing event.

app/components/works/edit_button_component.rb
=> Set the button target so it breaks out of the workDetailsFrame

spec/features/change_work_owner_spec.rb
=> Remove flaky section of test.

app/policies/work_policy.rb, app/policies/work_version_policy.rb, spec/factories/works.rb, spec/policies/work_version_policy_spec.rb
=> Don't allow editing of locked works

app/assets/stylesheets/dashboard.scss, app/components/collections/draft_component.html.erb, app/components/collections/draft_component.rb, app/components/collections/show/details_header_component.html.erb, app/components/collections/show/settings_header_component.html.erb, app/components/dashboard/collection_header_component.html.erb, spec/components/collections/draft_component_spec.rb
=> Indicate draft on various screens.

app/components/admin/locked_item_row_component.html.erb, app/components/admin/locked_item_row_component.rb, app/components/admin/locked_items_component.html.erb, app/components/admin/locked_items_component.rb, app/controllers/admin/locked_items_controller.rb, app/models/work.rb, app/policies/locked_item_policy.rb, app/views/admin/locked_items/index.html.erb, app/views/admins/show.html.erb, config/routes.rb, spec/components/admin/locked_item_row_component_spec.rb, spec/components/admin/locked_items_component_spec.rb, spec/requests/admins_spec.rb
=> Display the locked items on the dashboard

app/components/collections/works_component.rb, app/components/dashboard/collection_component.rb, app/components/works/admin_component.html.erb, app/components/works/admin_component.rb, app/components/works/show/files_component.html.erb, app/controllers/work_decommission_controller.rb, app/javascript/controllers/decommission_controller.js, app/models/collection.rb, app/models/work_version.rb, app/policies/work_decommission_policy.rb, app/policies/work_policy.rb, app/policies/work_version_policy.rb, app/views/work_decommission/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/features/decommission_work_spec.rb, spec/models/collection_spec.rb, spec/policies/work_version_policy_spec.rb, spec/requests/dashboard_collection_spec.rb, spec/requests/show_works_in_collection_spec.rb
closes #2375
Errors happen.
Unit, Amy.
=> Support decommissioning of works.

app/components/works/work_type_modal_component.html.erb
=> Require other for other type.

app/components/citation_component.rb, app/components/citation_modal_component.html.erb, app/components/collections/detail_component.html.erb, app/components/collections/links_component.html.erb, app/components/collections/show/settings_header_component.rb, app/components/dashboard/collection_header_component.rb, app/components/popover_component.rb, app/components/works/contributor_row_component.html.erb, app/components/works/detail_component.html.erb, app/components/works/file_row_component.html.erb, app/components/works/show/files_component.html.erb, app/components/works/state_display_component.rb, app/components/works/work_type_modal_component.html.erb, app/views/collection_versions/_edit_link.html.erb, app/views/collections/_edit_link.html.erb, app/views/dashboards/_collection_summary_row.html.erb, app/views/welcome/show.html.erb, app/views/works/_edit_button.html.erb, app/views/works/next_step.html.erb, app/views/works/next_step_review.html.erb, package.json, spec/components/collections/show/details_header_component_spec.rb, spec/components/collections/show/settings_header_component_spec.rb, spec/components/dashboard/collection_header_component_spec.rb, yarn.lock
Keep up to date with dependencies.  `fa-solid` is more understandable than `fas`
locally
=> Upgrade to font-awesome 6

app/views/works/_edit_button.html.erb, spec/requests/work_edit_button_spec.rb
Fixes #2320
locally & new request spec
=> Don't display the lock on each section of the view page

app/controllers/work_owners_controller.rb, app/mailers/works_mailer.rb, app/views/works_mailer/changed_owner_collection_manager_email.html.erb, spec/mailers/works_mailer_spec.rb, spec/requests/change_work_owner_spec.rb
=> Send email to collection managers when owner changed.

app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/work_type_controller.js
=> Change layout of other subtype input.

app/components/collections/update/depositors_component.html.erb, app/components/collections/update/managers_component.html.erb, app/components/collections/update/reviewers_component.html.erb, app/javascript/controllers/collection_participant_form_controller.js, app/javascript/controllers/sunet_input_controller.js, app/views/work_owners/edit.html.erb
refs #2524
This functionality is working erratically.
Amy.
=> Tweaks sunet lookups and adds error handling.

app/controllers/work_decommission_controller.rb
We don't want part of this to succeed without all of it succeeding
ci
=> Wrap the decommission process in a transaction

app/services/admin/work_report_query.rb, app/views/admin/work_reports/new.html.erb
closes #2513
Good reports
Locally.
=> Fix state filter in item admin report and adds missing hidden fields.

app/components/works/add_files_component.html.erb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/forms/work_form.rb, app/javascript/controllers/complex_radio_controller.js, db/migrate/20220829114247_add_globus_to_work_versions.rb, db/structure.sql, spec/factories/work_versions.rb, spec/forms/work_form_spec.rb, spec/requests/create_work_spec.rb
closes #2349
A little bit of automation is better than no automation.
Unit, Amy.
=> Allows selecting globus upload when creating deposit.

app/components/works/admin_component.rb, spec/features/lock_work_spec.rb
=> Change lock label.

spec/services/admin/collections_report_query_spec.rb
=> Make collections_report_query_spec more determinate.

config/locales/en.yml
=> Add label for no_review_workflow event.

db/structure.sql
This should have been check in a #2531, but it was overlooked.
CI
=> Updated structure.sql after running migrations

app/mailers/works_mailer.rb, app/models/work_version.rb, app/services/work_observer.rb, app/views/works_mailer/decommission_email.erb, spec/mailers/works_mailer_spec.rb, spec/models/work_version_spec.rb
Resolves #2332. 
Unit. (Will be tested in prod by Amy)
=> Email owner on decommission

app/components/dashboard/approvals_component.html.erb, app/components/dashboard/in_progress_collection_component.html.erb, app/components/dashboard/in_progress_component.html.erb, spec/features/mediated_deposit_versioning_spec.rb
Fixes #2295 - update headers on dashboard
=> update dashboard headers

app/components/collections/detail_component.html.erb, app/components/works/detail_component.html.erb
Fixes #2092 - separate multiple contact emails into new lines (works and collections)
Localhost
=> separate multiple emails into new lines

app/views/welcome/show.html.erb, spec/features/welcome_spec.rb
Fixes #2273 - update home page text
Localhost and updated test
=> adjust home page text

app/controllers/work_owners_controller.rb, spec/requests/change_work_owner_spec.rb
closes #2496 
It throws an error.
Unit
=> Allow changing owner to an existing depositor.

app/components/works/keywords_row_component.html.erb, spec/features/create_new_work_spec.rb
=> tweak duplicate keyword javascript error message

app/services/collection_version_event_description_builder.rb, spec/services/collection_version_event_description_builder_spec.rb
refs #2303
Better event descriptions.
Unit
Note: Splitting ticket into multiple PRs.
=> Adjust event descriptions for collection versions.

app/components/collections/show/deposits_header_component.html.erb, app/components/collections/show/deposits_header_component.rb, app/components/collections/show/details_header_component.rb, app/components/dashboard/collection_header_component.html.erb, app/components/dashboard/in_progress_collection_row_component.html.erb, app/views/works/index.html.erb, spec/components/collections/show/deposits_header_component_spec.rb, spec/components/dashboard/collection_header_component_spec.rb
=> Update links for collection editing.

app/views/works_mailer/changed_owner_collection_manager_email.html.erb, app/views/works_mailer/changed_owner_email.html.erb, spec/mailers/works_mailer_spec.rb
=> Changes links in ownership emails.

app/controllers/collections_controller.rb, app/models/collection_change_set.rb, app/services/collection_event_description_builder.rb, app/services/collection_observer.rb, spec/factories/collections.rb, spec/services/collection_change_set_spec.rb, spec/services/collection_event_description_builder_spec.rb, spec/services/collection_observer_spec.rb
closes #2303
Better event descriptions.
Unit
=> Adjust event descriptions for collections.

app/components/help_collection_component.html.erb, app/components/help_collection_component.rb, app/components/popover_component.rb, app/controllers/helps_controller.rb, app/javascript/controllers/help_controller.js, app/mailers/helps_mailer.rb, app/views/helps/new.html.erb, app/views/helps_mailer/jira_email.text.erb, config/locales/en.yml, spec/features/help_modal_spec.rb, spec/mailers/helps_mailer_spec.rb
closes #2272
Encourage users to re-use existing collections.
Unit, Amy
=> Allows user to request access to a collection.

app/jobs/deposit_collection_job.rb, spec/jobs/deposit_collection_job_spec.rb
closes #2563
Collections matter too.
Unit
=> Submit version description for collections.

app/controllers/helps_controller.rb, app/javascript/controllers/help_controller.js, app/javascript/controllers/help_how_controller.js, app/javascript/modules/validate-forms.js, app/views/dashboards/show.html.erb, app/views/helps/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_help_modal.html.erb, spec/features/help_modal_spec.rb
=> Add appropriate collection link to dashboard.

spec/components/works/version_description_component_spec.rb
spec descriptions that are incorrect are really confusing.
=> version_description_component_spec: fix copy pasta typos

app/assets/stylesheets/workEditor.scss, app/components/works/contributor_row_component.html.erb
=> Add fieldset/legend for contributors.

app/mailers/collections_mailer.rb, app/mailers/reviewers_mailer.rb, spec/mailers/collections_mailer_spec.rb, spec/mailers/reviewers_mailer_spec.rb
=> update subject line for manager notifications of activity.

app/components/works/dates_component.html.erb, app/components/works/dates_component.rb, app/components/works/publication_date_component.html.erb, app/components/works/publication_date_component.rb, app/javascript/controllers/complex_radio_controller.js, app/javascript/controllers/date_clear_controller.js
=> Support clearing of dates.

app/components/works/contributor_row_component.html.erb
Fixes #2300 - see design in the ticket (adds the word "OR" as shown in screenshot below)
Localhost
=> add or in contributor section

app/mailers/works_mailer.rb, app/services/work_observer.rb, app/views/works_mailer/decommission_manager_email.erb, app/views/works_mailer/decommission_owner_email.erb, spec/mailers/works_mailer_spec.rb, spec/models/work_version_spec.rb
=> Send email to collection managers when work is decommissioned

Gemfile, Gemfile.lock
Add pry to Gemfile for debugging purposes
Split from #2593
=> add pry to gemfile for debugging

app/policies/account_policy.rb, spec/requests/accounts_spec.rb
This allows collection managers to lookup accounts
Fixes #2510
CI
=> Expand account policy to collection managers

app/jobs/deposit_status_job.rb, app/services/deposit_completer.rb, lib/tasks/deposit.rake, spec/jobs/deposit_status_job_spec.rb, spec/services/deposit_completer_spec.rb
Reverts sul-dlss/happy-heron#2614
=> Extract depositor class from task and job

.circleci/config.yml, Gemfile, Gemfile.lock, README.md, app/controllers/application_controller.rb, bin/cypress, config/initializers/cypress_on_rails.rb, config/initializers/cypress_rails.rb, config/initializers/devise_remote_user.rb, cypress.config.js, cypress/app_commands/clean.rb, cypress/app_commands/eval.rb, cypress/app_commands/factory_bot.rb, cypress/app_commands/log_fail.rb, cypress/cypress_helper.rb, cypress/spec/date_input.cy.js, cypress/support/commands.js, cypress/support/index.js, cypress/support/on-rails.js, package.json, spec/factories/users.rb, spec/factories/work_versions.rb, spec/features/admin/work_report_spec.rb, spec/rails_helper.rb, yarn.lock
To replace Amy as date input tester.
=> Adds cypress scaffolding and test for date input.

cypress/spec/date_range.cy.js
=> Cypress test for date range

cypress/app_commands/log_fail.rb, cypress/spec/date_approximate.cy.js
=> Adds cypress test for approximate dates.

cypress/spec/date_clear.cy.js
=> Add cypress test for clearing dates

app/models/work_version.rb, spec/models/work_version_spec.rb
Will probably fix #2618, and may avert other bad stuff.
~~We should add a test for this too in a follow on PR.~~ Test added
New tests
=> this is a conditional check, not an assignment

app/services/work_version_event_description_builder.rb, spec/services/work_version_event_description_builder_spec.rb
=> Fix description message for new item without values.

app/javascript/controllers/autocomplete_edit_controller.js, app/javascript/controllers/keywords_controller.js
This will prevent the user from submitting a Deposit that has duplicate keywords
Fixes #2604 
Manually
=> Add duplicate keywords to the javascript validation

Gemfile, Gemfile.lock, app/jobs/deposit_job.rb, spec/jobs/deposit_job_spec.rb
closes #2638
Less moving around files.
Unit, QA
=> Only uploads changed files.

app/javascript/application.js
There is no need for extra javascript. It makes the site load slowly.
locally
=> Drop 400kb of unnecessary javascript

app/components/collections/update/details_form_component.html.erb, app/components/collections/update/participant_row_component.html.erb, app/components/first_draft_collections/buttons_component.html.erb, app/components/related_link_row_component.html.erb, app/components/works/buttons_component.html.erb, app/components/works/contact_email_row_component.html.erb, app/components/works/contributor_row_component.html.erb, app/components/works/dates_component.html.erb, app/components/works/file_row_component.html.erb, app/components/works/keywords_row_component.html.erb, app/components/works/publication_date_component.html.erb, app/components/works/related_work_row_component.html.erb, app/views/collections/_delete_button.html.erb, app/views/works/_delete_button.html.erb
This is the preferred syntax in fontawesome 6
locally
=> Use fa-regular over far

app/jobs/deposit_job.rb, app/services/repository.rb
Each class should only have a single responsibility.  This aligns with how Argo interfaces with the repository and will help me to complete #2673
ci
=> [refactor] Extract a Repository class

app/services/new_version_parameter_filter.rb
Docs are helpful when reading the code
n/a
=> Add some documentation to NewVersionParameterFilter

.circleci/config.yml
Keep up to date on depenencies.
=> Update browser-tools orb

app/components/works/add_files_component.html.erb, app/components/works/contributor_row_component.html.erb, app/components/works/dates_component.html.erb
Ref https://github.com/sul-dlss/happy-heron/issues/2642\#issuecomment-1247295711
=> All radio labels on the work edit page use a consistent font-weight

spec/features/create_new_collection_spec.rb, spec/features/create_new_work_spec.rb, spec/features/edit_draft_work_spec.rb, spec/features/update_existing_collection_spec.rb, spec/features/update_existing_work_spec.rb
This is idiomatic capybara.
ci
=> Use within for breadcrumbs tests

app/components/dashboard/profile_button_component.html.erb, app/components/dashboard/profile_button_component.rb, app/controllers/mail_preferences_controller.rb, app/controllers/profiles_controller.rb, app/controllers/work_owners_controller.rb, app/models/collection.rb, app/models/mail_preference.rb, app/models/user.rb, app/policies/collection_policy.rb, app/policies/profile_policy.rb, app/services/collection_observer.rb, app/services/collection_reminder_generator.rb, app/services/work_observer.rb, app/views/dashboards/show.html.erb, app/views/mail_preferences/edit.html.erb, app/views/profiles/show.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20220914211415_create_mail_preferences.rb, db/structure.sql, spec/components/dashboard/profile_button_component_spec.rb, spec/factories/mail_preferences.rb, spec/models/mail_preference_spec.rb, spec/requests/mail_preferences_spec.rb, spec/requests/profiles_spec.rb
So that users may set their email preferences.
Fixes #2510 
Tested by Amy on stage
=> Create a profile page for editing email preferences

app/views/admin/druid_searches/index.html.erb, app/views/admin/users/index.html.erb, app/views/work_owners/edit.html.erb
This is the correct semantic markup
=> Use search type input where appropriate

app/services/work_version_event_description_builder.rb, spec/services/work_version_event_description_builder_spec.rb
Fixes #2304 
- description changes of works that involve associations need some additional logic to detect when one is removed
- description changes of file labels need some additional checks so they operate correctly when a file description is changed to blank, added (but not if added blank), or changed
Localhost and new tests
Note: only one association (keywords) has complete tests (it had none before) - the others should operate exactly the same way since they all use the same logic/code.
=> detect changes to work_version associations correctly

cypress/spec/work_type_modal.cy.js
=> Cleanup work_type_modal.cy.js.

app/javascript/controllers/checkboxes_controller.js, app/views/mail_preferences/edit.html.erb, cypress/spec/email_preferences.cy.js
closes #2707
cypress
Note that deviation from mock-ups was @amyehodge approved.
=> Allows selecting all/none email preferences.

config/initializers/config.rb
refs #2736
To allow secrets to be provided by puppet.
=> Configure config gem to use env variables.

app/components/works/dates_component.html.erb, app/components/works/dates_component.rb, app/javascript/controllers/date_choice_controller.js, cypress/spec/date_clear.cy.js, cypress/spec/date_range.cy.js, spec/components/works/dates_component_spec.rb, spec/features/create_new_work_spec.rb
=> Change creation date to toggle with checkbox.

cypress/spec/work_type_modal.cy.js
Fixes #2624 - Add some additional cypress tests for the work modal
=> add some additional checks to work modal window

Gemfile, Gemfile.lock, app/components/works/show/attached_file_component.html.erb, app/components/works/show/attached_file_component.rb, app/components/works/show/files_component.html.erb, app/controllers/preservation_controller.rb, app/controllers/zips_controller.rb, app/models/attached_file.rb, app/policies/attached_file_policy.rb, app/services/active_storage/service/sdr_service.rb, app/services/cocina_generator/structural/file_generator.rb, config/initializers/preservation_client.rb, config/routes.rb, config/settings.yml, config/storage.yml, spec/components/works/show/attached_file_component_spec.rb, spec/requests/preservation_spec.rb, spec/requests/zips_request_spec.rb
~~Blocked by https://github.com/sul-dlss/operations-tasks/issues/3159~~
Fixes #2677
=> Download preserved files from preservation

app/controllers/works_controller.rb, app/views/works/_delete_button.html.erb, spec/features/delete_draft_work_spec.rb
=> Fix error when deleting draft item.

.rubocop.yml, app/components/works/admin_component.rb, app/controllers/work_move_controller.rb, app/javascript/controllers/collection_input_controller.js, app/models/work.rb, app/policies/work_move_policy.rb, app/policies/work_policy.rb, app/services/check_move_work_service.rb, app/views/work_move/edit.html.erb, config/locales/en.yml, config/routes.rb, cypress/app_commands/clean.rb, cypress/spec/move_work.cy.js, spec/factories/collection_versions.rb, spec/factories/works.rb, spec/requests/move_work_spec.rb, spec/services/check_move_work_service_spec.rb
=> Adds admin function for moving a collection.

app/jobs/deposit_job.rb, app/models/attached_file.rb, app/models/work_version.rb, app/services/active_storage/service/sdr_service.rb, app/services/cocina_generator/dro_generator.rb, app/services/cocina_generator/structural/file_generator.rb, app/services/cocina_generator/structural/generator.rb, app/services/work_observer.rb, spec/factories/work_versions.rb, spec/jobs/deposit_job_spec.rb, spec/rails_helper.rb, spec/services/cocina_generator/dro_generator_spec.rb, spec/services/work_observer_spec.rb
Once the files have moved to preservation, we don't need to keep an extra copy around
Fixes #2639
Test suite, tested on stage.
=> Remove locally cached files after deposit

cypress/fixtures/test.txt, cypress/spec/create_work.cy.js
Fixes #2623 - add a test for uploading a file in the browser and test that is not required for a globus upload
Localhost CI
=> add a cypress test for creating a work with uploaded files

.rubocop.yml, app/models/collection_version.rb, app/models/concerns/collection_version_state_machine.rb, app/models/concerns/work_version_state_machine.rb, app/models/work.rb, app/models/work_version.rb
The file was getting too long. This makes it easier to find what you are looking for.
CI
=> Extract the state machine for WorkVersion to its own file

app/controllers/work_move_controller.rb, config/locales/en.yml, spec/requests/move_work_spec.rb
=> Create an event when a work is moved to a different collection

app/jobs/deposit_job.rb
Fixes #2784 - bug with logging into sdr-api
CI
=> login before we access sdr-api

Gemfile, Gemfile.lock, app/jobs/deposit_job.rb, app/models/attached_file.rb, spec/jobs/deposit_job_spec.rb
=> Adjust deposit to use latest SDR client.

.rubocop.yml, app/controllers/collection_versions_controller.rb, app/controllers/collections_controller.rb, app/controllers/first_draft_collections_controller.rb, app/controllers/works_controller.rb, spec/features/edit_draft_work_spec.rb, spec/mailers/collections_mailer_spec.rb, spec/mailers/first_draft_collections_mailer_spec.rb, spec/mailers/helps_mailer_spec.rb, spec/mailers/reviewers_mailer_spec.rb, spec/mailers/works_mailer_spec.rb, spec/models/abstract_contributor_spec.rb, spec/models/attached_file_spec.rb, spec/models/author_spec.rb, spec/models/contact_email_spec.rb, spec/models/event_spec.rb, spec/models/keyword_spec.rb, spec/models/mail_preference_spec.rb, spec/policies/collection_decommission_policy_spec.rb, spec/policies/collection_policy_spec.rb, spec/policies/collection_version_policy_spec.rb, spec/policies/dashboard_policy_spec.rb, spec/policies/work_policy_spec.rb, spec/policies/work_version_policy_spec.rb, spec/requests/accounts_spec.rb, spec/requests/mail_preferences_spec.rb, spec/requests/orcid_spec.rb, spec/requests/preservation_spec.rb, spec/requests/profiles_spec.rb, spec/requests/zips_request_spec.rb
=> add new rubocops

app/components/works/add_files_component.html.erb
Fixes #2844 - most of the work was already done in #2875, just adding some new changes based on https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471005607
Localhost
=> modify text to match latest UIs

app/services/new_version_parameter_filter.rb
closes #2891
500
Tested this on QA. I'm not too sure how to write a good unit test for this (without spending an entire day).
=> Allow NewVersionParameterFilter to handle non-existing existing params.

README.md, config/deploy/prod.rb
Freeze H2 prod while developing HFS
=> Freeze for production.

app/components/works/add_files_component.html.erb, app/components/works/buttons_component.html.erb, app/components/works/form_component.rb, app/controllers/works_controller.rb, app/models/concerns/work_version_state_machine.rb, config/settings.yml, cypress/spec/create_work_version.cy.js, spec/components/works/add_files_component_spec.rb, spec/components/works/buttons_component_spec.rb, spec/components/works/form_component_spec.rb, spec/requests/complete_globus_setup_spec.rb
Remove Globus complexity that is no longer necessary since code is frozen.
Unit
=> Remove globus feature flag.

README.md, config/schedule.rb, config/settings.yml
Fixes #2869 -- add HB checkins for cron jobs.  Modeled on sul-dlss/preservation_catalog#2075
Config update for production in sul-dlss/shared_configs#1876
=> add hb checkins for cron

app/components/works/add_files_component.html.erb, app/components/works/buttons_component.html.erb
=> Update language displayed related to globus

app/views/works_mailer/globus_account_setup.html.erb, spec/mailers/works_mailer_spec.rb
To make the Globus setup email easier to understand.
Closes #2931 
=> Update Globus account setup email text

app/javascript/controllers/deposit_button_controller.js, cypress/spec/create_work_version.cy.js
Fixes #2932
This commit restores code that I suspect was inadvertently removed.
CI + local browser
=> Display Globus message in deposit form only if a Globus type upload

app/views/works_mailer/globus_endpoint_created.html.erb, spec/mailers/works_mailer_spec.rb
Resolves #2955 to update globus email text. New email looks like below (also forwarded for your review, @amyehodge):
Unit tests updated and pass, QA.
=> Update globus endpoint email

app/assets/stylesheets/workEditor.scss, app/components/works/add_files_component.html.erb
=> Adjust globus confirm sizing.

app/components/works/add_files_component.html.erb, app/views/works_mailer/globus_endpoint_created.html.erb
Fixes #2972 - update to links in email and web page for globus documentation
Localhost
=> fix instructions links in email and page

app/components/works/add_files_component.html.erb, spec/components/works/add_files_component_spec.rb
Resolves #2978 with updated text. 
Unit
@amyehodge here's the updated text on the screen:
=> Update globus files checkbox text

app/assets/stylesheets/details.scss, app/components/works/add_files_component.html.erb, app/components/works/edit/attached_file_component.html.erb, app/components/works/edit/attached_file_component.rb, app/components/works/edit/directory_component.html.erb, app/components/works/edit/directory_component.rb, app/components/works/edit/file_row_component.html.erb, app/components/works/edit/file_row_component.rb, app/components/works/edit/files_component.html.erb, app/components/works/edit/files_component.rb, app/forms/draft_work_form.rb, app/javascript/controllers/dropzone_controller.js, app/javascript/controllers/show_controller.js, app/services/file_hierarchy_service.rb, cypress/spec/edit_hierarchy_work_version.cy.js, spec/factories/work_versions.rb, spec/features/create_new_work_spec.rb, spec/services/file_hierarchy_service_spec.rb
Allow users to work with items that have file hierarchies.
Unit
=> Support adding files to hierarchy

app/assets/stylesheets/work.scss, app/components/works/add_files_component.html.erb
closes #2920
Many, many files.
=> Adds scroll to work edit upload file sections.

app/components/works/add_files_component.html.erb
Resolves #2982 to not bold instructions for globus steps. @amyehodge, here's what this looks like:
Unit
=> Unbolding instructions

config/schedule.rb
Fix typo in scheduled task.
CI
=> schedule typo fix

config/schedule.rb, config/settings.yml, config/settings/test.yml, spec/mailers/collections_mailer_spec.rb, spec/mailers/works_mailer_spec.rb
Fixes settings so that whenever can load settings
=> Removing Socket usage in host setting

app/models/concerns/work_version_state_machine.rb, app/services/work_observer.rb, spec/models/work_version_state_machine_spec.rb
=> Test the recent double-depositing hotfix

app/javascript/controllers/dropzone_controller.js
=> Allow re-upload of deleted files.

Gemfile, Gemfile.lock
=> Upgrade to Sidekiq7

app/views/collections_mailer/invitation_to_deposit_email.html.erb, app/views/collections_mailer/manage_access_granted_email.html.erb, app/views/collections_mailer/review_access_granted_email.html.erb, app/views/works_mailer/changed_owner_email.html.erb, app/views/works_mailer/deposited_email.html.erb, config/settings.yml, spec/mailers/collections_mailer_spec.rb, spec/mailers/works_mailer_spec.rb
Fixes #3046 - add email newsletter subscription link to some emails
Updated specs
=> add link to subscribe to newletter from some emails

app/mailers/collections_mailer.rb, app/services/collection_observer.rb, app/views/collections_mailer/first_draft_created.html.erb, app/views/collections_mailer/item_deposited.html.erb, app/views/collections_mailer/version_draft_created.html.erb, spec/jobs/deposit_complete_job_spec.rb, spec/mailers/collections_mailer_spec.rb, spec/models/work_version_state_machine_spec.rb
fixes #3043 - add links to the item that triggered the email notification to three existing email notifications
~~No testing~~
- Updated the specs to look for the new URLs
- tested on stage
=> T3043 email update

.circleci/config.yml, .rubocop.yml, Gemfile, Gemfile.lock, README.md, docker/app/Dockerfile, docker/workers/Dockerfile
Keep pace with Ruby releases.
CI and will be int-tested in stage
=> Upgrade to Ruby 3.2.2

app/views/admin/users/index.html.erb
Fixes #3058 - modification to user search admin report
Localhost
=> switch role to last modified in admin user search view

.rubocop.yml, spec/factories/contact_emails.rb
so everything is shiny and sparkly
=> add new rubocops and tweaks for them

app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/work_type_controller.js, app/models/work_type.rb, cypress/spec/work_type_modal.cy.js, spec/validators/work_subtype_validator_spec.rb
=> In work type modal, update options for Mixed Materials.

app/components/works/edit/attached_file_component.html.erb, app/views/collection_versions/_collection_version.html.erb, app/views/collections/_collection.html.erb
=> Fix eagerly (and mistakenly) auto-corrected ERB comments

app/models/work_type.rb, config/mappings/types_to_resource_types.yml, cypress/spec/work_type_modal.cy.js, spec/services/cocina_generator/description/types_generator_spec.rb
=> Add conference abstract and pamplet content subtypes

app/components/works/add_files_component.html.erb, app/components/works/dates_component.html.erb
refs #3119
Accessibility
Local
=> Label accessibility on deposit form.

app/jobs/globus_setup_job.rb
refs #3005
Add additional context to help identify source of error in #3005.
=> Adds state to HB context for GlobusSetupJob.

app/components/collections/edit_license_component.html.erb, app/components/works/license_component.html.erb, config/settings.yml
=> Update external links to new library sites

.github/pull_request_template.md
Discussed during dev planning earlier today. We are taking a "first, do no harm" approach to accessibility going forward so we stop introducing new a11y problems.
N/A
=> Update PR template to reflect new accessibility requirement

app/views/layouts/application.html.erb, config/settings.yml
=> Adds gtag.

app/javascript/controllers/work_type_modal_controller.js
closes #3137
Correct user input.
Locally
=> Clear existing subtypes when selecting other type.

README.md, app/controllers/works_controller.rb, app/views/layouts/application.html.erb
Complete work on #3021 
Unit
No
=> Switch user_exists to user_valid

app/models/abstract_contributor.rb, app/models/affiliation.rb, db/migrate/20230705222153_create_affiliations.rb, db/structure.sql
refs #3099
Support adding affiliations to UI and mapping to Cocina.
=> Adds active record model for affiliations.

app/views/works_mailer/globus_endpoint_created.html.erb, spec/mailers/works_mailer_spec.rb
Fixes #3202
RSpec tests.  Eventually the PO will test this as well, but not before the merge.
No.
=> globus_endpoint_created email updated

app/components/works/globus_setup_component.html.erb
Resolves #3203 to update instructions for Globus. @amyehodge see below and also questions from @ndushay on #3202.
HOLD until questions on #3202 are resolved since these should likely be in sync. 
Unit and local instance
No
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) …
=> Update globus instructions

app/assets/stylesheets/editor.scss
closes #3213
https://github.com/sul-dlss/happy-heron/assets/588335/11a4db32-e688-4077-a9ad-eed7d9a7356b
=> Set cursor for autocomplete.

app/views/dashboards/_collection_summary_row.html.erb
closes #3221
https://github.com/sul-dlss/happy-heron/assets/588335/d2733387-8f48-4e04-bd62-204d3dcd6751
=> Correctly handle deleting work from dashboard.

app/assets/stylesheets/palette.scss, app/components/works/buttons_component.html.erb, cypress/spec/create_work_version.cy.js
Fixes #3214
No new violations introduced per Si and WAVE scans.
=> Change alignment, weight, and content of text warning user about Globus deposit state

config/initializers/cypress_on_rails.rb
Less noisy test runs without deprecation warnings.
CI
N/A
=> Avoid using deprecated cypress-on-rails attr

app/views/shared/_terms_of_deposit.html.erb
Fixes #3255 (at least I can't reproduce anymore on localhost after making this change)
Localhost
=> fix tou icons not showing sometimes

Gemfile.lock
Update to latest version of the globus client gem.
=> Update globus client dependency

.gitignore, Gemfile, Gemfile.lock, bin/test-files
=> Adds script for generating test data.

app/controllers/ror_controller.rb, app/views/ror/show.html.erb, spec/requests/ror_spec.rb
closes #3236
More context for users.
Unit, local
=> Adds details to affiliation autosuggest.

app/components/collections/work_row_component.html.erb, app/components/dashboard/in_progress_row_component.html.erb
More fixes for #3221 - content missing when works are deleted (need the fix in a couple more spots).  
Localhost.  It is the exact same fix that was applied in #3233 just in a couple more spots where it is happening.
=> more fixes for content missing problem when deleting works

app/models/work_type.rb, spec/services/cocina_generator/description/types_generator_spec.rb
=> Reorder video subtypes alphabetically

app/services/cocina_generator/access_generator.rb, spec/services/cocina_generator/access_generator_spec.rb
=> Remove extra period in rights statement concatenation

app/views/collections_mailer/item_deposited.html.erb, spec/mailers/collections_mailer_spec.rb
=> Add custom rights statement to collection manager email on item deposit

README.md
seemed possibly helpful based on a short slack discussion yesterday about testing different roles in H2.
this took very little time to add, so if people feel this is more noise than signal, feel free to reject.
confirmed the mentioned things were there in my browser
nope, readme only
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility …
=> non-brute force cookie clearing suggestion in README

app/controllers/helps_controller.rb, app/views/helps/new.html.erb
Fixes #3193 by adding meaningful examples to the fields
CI
SiteImprove
=> Add a basic example to complete the help modal accessibility

app/components/related_link_row_component.html.erb, app/components/works/contact_email_row_component.html.erb, app/components/works/related_work_row_component.html.erb, app/views/dashboards/_collection_summary_row.html.erb, spec/components/related_link_component_spec.rb, spec/components/works/related_work_component_spec.rb
Improves the uniqueness of a few labels so that screen readers use the correct label.
Si
SI
=> Improve aria-labels for uniqueness and accessibility

app/views/profiles/show.html.erb
=> Update caption text for communication preferences

app/components/works/show/attached_file_component.html.erb, app/components/works/show/attached_file_component.rb, config/settings.yml, spec/components/works/show/attached_file_component_spec.rb
Fixes #3351 
NOTE: Corresponding shared configs PR: https://github.com/sul-dlss/shared_configs/pull/2029
CI
=> Add file share link to files display when published

.rubocop/custom.yml, spec/jobs/globus_setup_job_spec.rb
Enable new cops and autocorrect errors
=> Enable new cops and fix linting errors

app/jobs/deposit_complete_job.rb, app/services/deposit_complete_auditor.rb
refs https://github.com/sul-dlss/happy-heron/issues/3297
To help determine why some deposits are not being updated.
=> Adds additional logging to try to identify missing deposits.

app/jobs/deposit_complete_job.rb
Help troubleshoot missing deposit completes.
=> Adds more logging to DepositCompleteJob.

app/javascript/controllers/file_uploads_controller.js, app/views/layouts/application.html.erb, package.json, spec/features/update_existing_work_spec.rb
Fixes #3410
* Do not reference Stimulus targets that are missing
* Integrate Honeybadger with JavaScript stack
=> [HOLD] Fix JavaScript error when modifying files

app/views/layouts/application.html.erb
It is way more noise than signal, sadly.
CI
=> Remove HB integration from client-side JavaScript

app/services/cocina_generator/access_generator.rb, spec/services/cocina_generator/access_generator_spec.rb
Part of #3404 to have line breaks in the use statement make their way into the Cocina and then MODS and display in PURL. 
Deploy to QA.
=> Change separator for custom use statement

app/forms/work_form.rb
Because it sounds better this way.
=> fix typo in validation message

app/components/works/add_files_component.html.erb
Fixes #3428 - update message to users
CI
=> update message shown to users when more than max files are in deposit

config/initializers/okcomputer.rb
So that we are notified when queues disappear.
QA
=> Adds okcomputer check for rabbit queues

Gemfile, Gemfile.lock
=> Upgrade config

.circleci/config.yml, Gemfile, Gemfile.lock, Rakefile, config/application.rb
=> Upgrade cssbundling-rails

app/controllers/works_controller.rb
This code should be equivalent, given a string can't start with two different things.  But these jobs are mutually exclusive, so this makes it more explicit in the code that they cannot/should not both be run.  See https://stanfordlib.slack.com/archives/C69UZCJ8M/p1706212905853809 for some context for this proposed change.
Existing tests
=> make job starts more clear

app/controllers/work_move_controller.rb
Fixes #3466 - add some extra info to the collection move event.
Follow on from #3462 (PO requested after this work was done).
=> change description of collection move event

Gemfile.lock
=> Upgrade to latest bundler

package.json, yarn.lock
=> Upgrade cypress

app/controllers/reservations_controller.rb, app/controllers/works_controller.rb, db/migrate/20240501135224_add_user_version_to_work_versions.rb, db/structure.sql
=> Add migration to specify WorkVersion#user_version

app/components/collections/information_component.html.erb, app/components/collections/information_component.rb, app/components/works/detail_component.html.erb, app/components/works/detail_component.rb
closes #3525
The date was confusing.
=> Removes last saved from details pages.

README.md
=> Adds info on linters to README.

app/mailers/collections_mailer.rb, app/mailers/works_mailer.rb, spec/mailers/collections_mailer_spec.rb, spec/mailers/works_mailer_spec.rb
=> Update email subject lines.

app/components/works/form_component.html.erb, app/components/works/form_component.rb, app/components/works/version_description_component.html.erb, app/javascript/controllers/auto_citation_controller.js, app/javascript/controllers/new_user_version_controller.js
closes #3521
Per ticket.
Locally, Amy
=> Add version to auto citation.

Gemfile, Gemfile.lock, app/jobs/deposit_job.rb, spec/jobs/deposit_job_spec.rb
closes #3543
Tie everything together.
Unit, QA
=> Set user_versions param when depositing.

app/mailers/collections_mailer.rb, app/mailers/works_mailer.rb, spec/mailers/collections_mailer_spec.rb, spec/mailers/works_mailer_spec.rb
=> Email subject header tweaks.

app/views/collections_mailer/version_draft_created.html.erb, spec/mailers/collections_mailer_spec.rb
=> Version draft created email tweak.

.rubocop.yml, Gemfile, Gemfile.lock, README.md, app/forms/base_work_form.rb, app/forms/collection_settings_form.rb, app/forms/draft_collection_form.rb, app/forms/edtf.rb, app/forms/embargo_date.rb, docker/app/Dockerfile, docker/workers/Dockerfile
=> Bump to ruby 3.3.1 and bundle

README.md
Following along the process for testing in the README.md it seemed like the tests fail without this step?
Running the tests locally on my workstation.
=> Mention test:prepare

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, app/controllers/works_controller.rb, app/javascript/controllers/work_type_controller.js, app/views/works/details.html.erb, spec/features/purl_reservation_spec.rb
=> Fix to editing reservations.

app/components/collections/works_component.html.erb
=> Restore ordering works by date in the collection view

app/controllers/fast_controller.rb, config/settings.yml, spec/requests/fast_spec.rb
=> Replace broken FAST API with new FAST suggest API

app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb
=> Handle nil user version when determining previous versions.

app/validators/embargo_date_validator.rb, spec/validators/embargo_date_validator_spec.rb
=> Make EmbargoDateValidator able to handle embargos measured in months

app/views/collections_mailer/invitation_to_deposit_email.html.erb
=> fix broken link in email

.rubocop.yml, app/services/cocina_generator/structural/generator.rb
Another small bit of housekeeping.
=> Enable new cops and a address a new cop complaint

config/deploy.rb
QA doesn't have a worker box, so this wasn't running in QA.
=> Fix roles for rabbitmq setup.

.circleci/config.yml, .rubocop.yml, Gemfile.lock, README.md, docker/app/Dockerfile, docker/workers/Dockerfile
=> Upgrade ruby to 3.4.1 and orbs.

Gemfile, Gemfile.lock
=> Bumped version of pres and sdr clients.

app/views/layouts/application.html.erb
=> Adds GTM code.

Gemfile, Gemfile.lock
Do not need it, do not use it.
CI
=> Remove explicit dependency on mutex_m and spring

app/controllers/objects_controller.rb, app/jobs/base_deposit_job.rb
=> Remove misleading usage of `protected` keyword

.rubocop.yml, app/controllers/application_controller.rb, app/controllers/fast_controller.rb, app/services/admin/collections_csv_generator.rb, app/services/admin/work_csv_generator.rb, app/services/cocina_generator/description/contributors_generator.rb, cypress/app_commands/factory_bot.rb
A few minor maintenance updates that came up when adding the 2 new cops.
=> Rubocop updates for private_constant scoping

lib/tasks/reports.rake
Fixes #3701
Ran the new rake task in a deployed environment.
=> Add a report listing depositor SUNetIDs for given druids

app/services/account_service.rb, spec/services/account_service_spec.rb
Fixes #3706
This commit modifies how `AccountService` responses are cached:
1. When hitting the accountws API, retry a small number (5) of times in rapid succession to increase the chances a user has of getting a valid entry back quickly. Why? The accountws API is flaky, returning 500 error responses frequently.
2. When we get a 500 error currently, H2 is mistakenly caching the empty response, so legit users are showing up as missing when we consult the cache. With retries in place, now we writing nothing to the cache when none succeed.
=> Improve caching of SUNet ID lookups

app/services/account_service.rb
So we can figure out WTF is happening in https://app.honeybadger.io/projects/77112/faults/119698043
CI
=> Add more context to exceptions raised in account service

app/services/cocina_generator/description/contributors_generator.rb
=> Change thesis mapping.

app/services/cocina_generator/description/contributors_generator.rb
=> Map distributor role to provider.

app/services/cocina_generator/structural/file_generator.rb
This will make roundtrip checking in H3 easier.
Unit
=> Consistently order message digests.

app/services/cocina_generator/description/generator.rb, app/services/cocina_generator/structural/file_generator.rb
H3 doesn't allow dupes, so this will help with roundtripping.
Unit
=> Dedupe subjects

Gemfile, Gemfile.lock, app/services/orcid_read_limited_user_service.rb, app/services/orcid_stanford_user_service.rb, config/settings.yml
Part of https://github.com/sul-dlss/dor-services-app/issues/5284
Has shared_configs updates too (linked to from ticket above)
~~Waiting on switchover testing~~
=> Update mais-orcid-client gem

config/settings.yml
Try to avoid these 301 responses: https://app.honeybadger.io/projects/77112/faults/120297096
CI 🤷🏻‍♂️
=> Hit FAST API over HTTPS

app/services/new_collection_version_service.rb, spec/services/new_collection_version_service_spec.rb
closes #3758
It is needed for migration to H3.
Unit, QA
=> Add new collection version service.

Gemfile, Gemfile.lock
=> Adds parallel gem to use for export to H3.

app/services/cocina_generator/description/related_links_generator.rb, spec/services/cocina_generator/description/related_links_generator_spec.rb
Fixes mapping for https://github.com/sul-dlss/hungry-hungry-hippo/issues/1630
Unit
=> Map related link titles for collections

app/jobs/deposit_job.rb
=> Make accessioning configurable in DepositJob.
