sul-dlss/happy-heron

Capfile, Gemfile, Gemfile.lock, config/database.yml, config/deploy.rb, config/deploy/qa.rb, db/schema.rb, docker-compose.yml
Connects to #6
Fixes #18 
To install capistrano and begin testing passenger in standalone mode.
It was deployed to QA.
Shared_configs set up for QA.
=> Install capistrano and add QA environment

app/components/buttons_component.html.erb
=> Buttons must be in a container or they will stretch the full row

Passengerfile.json
Currently, puppet creates and manages this file in the `/opt/app/h2/happy-heron/current/` directory, which is a symlink. So if you redeploy the application and puppet has not yet re-created Passengerfile.json, then you cannot restart Passenger since it depends on that configuration being present.
Note that the contents of this file are identical to what's in puppet now, so when puppet overwrites the file, it should have no effect on the running application or any restarts.
QA
Added Passenger configuration
=> Add passenger configuration to application

README.md
So the design information is findable
=> Add links to design docs

app/models/notification.rb, app/models/user.rb, db/migrate/20201013170323_simplify_columns_in_notifications.rb, db/schema.rb
There were two deficiencies with the prior (copypasta) notifications table:
1. Without notification rows for a user, a user instance was not destroyable because notifiable_type was not defined;
2. We did not need the complexity in the prior table, specifically distinguishing between users and recipients, and also needing to support notifiable models.
I replaced these columns with two new ones: an `opened_at` date, which is `nil` by default, and will allow us to distinguish read from unread messages, and a `text` string to contain the notification message itself.
CI and local testing in console
none
=> Simplify notifications table

README.md
To better organize the README
N/A
README
=> Add type-checking automation section to README

README.md
To ease folks into the new branch name.
N/A
README
=> Document branch naming and aliasing in README

app/components/dates_component.html.erb, app/controllers/works_controller.rb, db/migrate/20201013170323_simplify_columns_in_notifications.rb, db/migrate/20201014223440_rename_work_created_field.rb, db/schema.rb, sorbet/rails-rbi/models/work.rbi, spec/factories/works.rb, spec/features/create_new_work_spec.rb
Draft because I'd like https://github.com/sul-dlss/happy-heron/pull/135 merged first.
`created_etdf` should be `created_edtf` (EDTF == extended date-time format).
CI
none
=> Correct typo in name of work created field

.gitignore
So Naomi can use pry locally and not drive Justin Coyne mad with pry being in the app everywhere.  He had the excellent suggestion of doing this:  https://github.com/gerrywastaken/Gemfile.local
=> .gitignore - add Gemfile.local and Gemfile.local.lock

spec/spec_helper.rb
I find this kind of output super helpful when i'm working in a single spec file:
(except ... not the failures.  failures should never happen.  we're perfect coders.)
```
Coverage report generated for RSpec to /Users/ndushay/sul-dlss-github/happy-heron/coverage. 33 / 289 LOC (11.42%) covered.
SimpleCov failed with exit 1ndushay@m3dl-sm-03-mbph-3 happy-heron (main) $ bx rspec spec/requests/dashboard_request_spec.rb 
Dashboards
shows links to create in a collection (FAILED - 1)
when Settings.allow_sdr_content_changes is
false
displays allow_sdr_content_changes alert text (FAILED - 2)
true
does NOT display allow_sdr_content_changes alert text (FAILED - 3)
Failures:
```
=> spec_helper: default single spec file run to have doc output

app/jobs/deposit_job.rb
Fixes #166 
This avoids a bug in sdr-client: https://github.com/sul-dlss/sdr-client/issues/134
=> Pass an empty structural data model so the object can be registered

config/webpacker.yml
So that webpacker can find application.css
Avoids:
```
4) Collections requests with authenticated user when collection fails to save renders the page again
Failure/Error: <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
ActionView::Template::Error:
Webpacker can't find application.css in /Users/jcoyne85/workspace/sul-dlss/happy-heron/public/packs-test/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
```
=> Set extract_css: false

app/services/request_generator.rb, config/settings.yml, spec/services/request_generator_spec.rb
To allow the hydrus APO to vary by environment.
Unit.
Updated stage and prod shared_configs.
Note: I created an APO in QA. I'm not sure if it matters, but I'm not positive that I got it completely right.
=> Make hydrus APO a setting

app/controllers/application_controller.rb, app/controllers/collections_controller.rb, app/controllers/works_controller.rb, app/javascript/packs/application.js, app/javascript/stylesheets/alert.scss, app/javascript/stylesheets/main.scss, app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb, config/settings.yml, package.json, spec/features/create_new_work_spec.rb, spec/features/user_return_location_spec.rb, spec/features/welcome_spec.rb, spec/requests/collections_spec.rb, spec/requests/works_spec.rb, yarn.lock
Fixes #103 
This feature flag will allow deployment to production early without risk to existing SDR content.  (Think:  before the PO has signed off)
Flag defaults to NOT ALLOWING content to be updated - this makes for more work in tests, but avoids possibly messing up in prod ...  I can reverse the default if desired.
If you try to create a collection or a work, you will be redirected to the dashboard with the alert message shown:
^^ NOTE that the close button for the alert text is on the LEFT.  This is how the access team seems to do it, which is good if the window is wide and/or if the alert text is short.  The last commit is the simple stylesheet change I made for this.
on my laptop and I also wrote some request specs for it.
=> Feature flag

app/jobs/base_deposit_job.rb, app/jobs/deposit_job.rb, app/jobs/deposit_status_job.rb, spec/jobs/deposit_job_spec.rb, spec/jobs/deposit_status_job_spec.rb
closes #202
* Avoid retrying failed deposits.
* Allow waiting for deposit to retry with backoff.
Unit
NA
=> Splits out checking deposit status into separate job.

.autoupdate/postupdate
Connects to #231
To automate type-checking updates as part of weekly dep updates.
It wasn't.
None
=> Add weekly update hook to regenerate and commit Sorbet signatures

.autoupdate/postupdate
And use binstubs to ensure build is using the right binaries for the application.
To automate RBI updates as part of weekly updates.
sul-ci-prod
none
=> Spin up docker-compose

.rubocop.yml
=> Configure new rubocop cops

app/components/works/embargo_component.html.erb
Fixes #236 
Draft while I figure out testing and any relevant refactoring.
After:
=> Add additional options to embargo access form

app/controllers/application_controller.rb
So that groups are available even if the shibboleth session expires.
Fixes #281
Tested on staging.
=> Cache groups in the session

app/components/works/dates_component.html.erb
=> Inputs are readable when valid style is applied

app/components/works/agreement_component.html.erb
This will highlight it when it hasn't been selected
=> Add bootstrap classes to agreement

app/controllers/application_controller.rb
Before this change the empty list may be cached, which means you can never be a member of groups.
Tested on stage.
=> Look for groups headers if the session groups is empty

app/controllers/application_controller.rb, app/models/user.rb, app/models/user_with_groups.rb, app/policies/application_policy.rb, app/policies/collection_policy.rb, app/policies/dashboard_policy.rb
No functional changes.
A user is a persistence object, which has no concept of groups.
Test suite
=> Deconflate groups and users

app/views/dashboards/show.html.erb
Fixes #282 
Note from https://fontawesome.com/icons?d=gallery&q=pencil that `fa-pencil-alt` is being used.  Is this ok?  Is the size okay?  Does it need to be flipped so the point is on the lower right?  etc.
ran it locally
=> use fontawesome pencil icon

app/components/works/contributor_row_component.html.erb, app/components/works/file_row_component.html.erb
Fixes #280
Note:  not 100% certain i got the desired trash icon -- there are a lot and I didn't understand the design doc notation as there is no `fa-trash-o`.  Also not certain if it's the right size.
running locally and ensuring unit tests still pass.
=> use fontawesome wastebasket

.gitignore, spec/requests/collections_spec.rb, spec/spec_helper.rb
Running specs in a random order can help us find deficiencies in the suite.
=> Run specs in a random order without monkeypatches

app/exceptions/try_again_later.rb, app/jobs/deposit_status_job.rb, sorbet/rails-rbi/typed_params.rbi, spec/jobs/deposit_status_job_spec.rb
Fixes #233
This exception is used to trigger Sidekiq retries and is not useful for reporting to Honeybadger. By using a custom exception class, we can ignore it in HB config. 
CI
Corresponding shared_configs work has already been done.
=> Raise custom exception when deposit status not available

app/components/works/contributor_row_component.html.erb, app/components/works/contributors_component.html.erb, app/components/works/related_work_component.html.erb, app/components/works/related_work_row_component.html.erb, app/javascript/controllers/nested_form_controller.js, sorbet/rails-rbi/typed_params.rbi
To be consistent with other JS controllers in the app, and to use the language-specific naming convention.
CI
None
=> Use consistent function naming scheme in JS

app/controllers/works_controller.rb, app/models/work.rb, db/migrate/20201105191840_add_depositor_to_work.rb, db/structure.sql, spec/factories/works.rb
Required for #347 so we know which drafts a logged in user can see.
=> Add depositor to a work

app/components/works/embargo_component.html.erb
Fixes #317
I'm not facile with bootstrap; it would be great if someone who was double checked this.   I did read about what the diff classes I was tweaking meant ...
Firefox, 100% size:
Firefox, 100% size
Firefox, 120% size
=> embargo date input: adjust bootstrap column widths

app/components/works/keywords_component.html.erb, app/components/works/keywords_component.rb, app/components/works/work_form_component.html.erb, app/controllers/works_controller.rb, app/javascript/controllers/keywords_controller.js, app/javascript/controllers/progress_controller.js, spec/components/works/keywords_component_spec.rb, spec/features/create_new_work_spec.rb, spec/requests/works_spec.rb
This is a spike for the team to be able to evaluate the two approaches: local forms vs remote forms. This PR switches from a local form to a remote form:
* local form: this is the standard rails form. when submitted, the request goes to the server and the server will send back to the client a rendered form (if errors) or redirect to a show page, typically
* remote form: this is the new default in rails. when submitted, turbolinks submits the form via XHR, the server does validation, and if validator errors are present, either a partial is rendered and sent or a JSON representation of errors are sent, and you use JS (Stimulus for us) to parse the errors and show them on the page.
Long story short? new-style rails convention prevents unnecessary page loads (more reactive/quicker user …
=> Convert keywords component validation to remote form

config/environments/production.rb
To fix websockets in deployed environments.
in -stage
none
=> Correct request origin typos preventing ActionCable connections

app/components/works/dates_component.html.erb
Fixes #328 (width of date input fields)
I tried to take advantage of Bootstrap's grid system for responsive layouts.
Locally with Firefox and Chrome;  deployed to qa and approved by Amy per slack thread:
=> work form date input widths adjusted

app/components/collections/form_component.html.erb, app/components/works/title_component.html.erb, app/forms/collection_form.rb, app/forms/work_form.rb, app/models/collection.rb, app/models/work.rb, config/initializers/devise.rb
Fixes #332 
* create an email regex to require a pattern like this XXX@XXX.XX  (some characters ending with exactly one @ followed by some characters (e.g. a subdomain) followed by exactly one . followed by at least two characters (e.g. a top level domain)
* put this email regex in a single config location (just took over the Devise config)
* use this configured regex in all current locations where we validate email addresses (client or server side)
* add this validation to the Reform models as well (where they were not before) <-- not sure if this is needed?
=> make email validation more strict client/server side

app/components/works/description_component.html.erb, app/components/works/description_component.rb, app/components/works/work_type_modal_component.html.erb, app/controllers/works_controller.rb, app/javascript/controllers/edit_deposit_controller.js, app/javascript/controllers/work_type_controller.js, app/validators/work_subtype_validator.rb, spec/components/works/work_type_modal_component_spec.rb, spec/features/create_new_work_spec.rb, spec/features/edit_draft_work_spec.rb, spec/models/work_spec.rb, spec/requests/works_spec.rb
Fixes #272
Includes:
* Render a text field for the user-supplied subtype when 'Other' type selected in modal
* Change work subtype validator to change the behavior to require a user-supplied subtype
Bonuses:
* Add an invalid-feedback div to abstract field so users know why it has turned red
CI and in browser
None
=> Require a user-supplied subtype for works of type 'other'

spec/requests/collections_spec.rb
This is both more idiomatic RSpec usage (`describe` vs. `context`) and brings the collections request spec into alignment with the works request spec in this regard.
CI
None
=> Slight refactor of collections request spec

app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/work_type_controller.js
To fix a style regression.
None
=> Fix style regression

.rubocop.yml, app/components/collections/form_component.html.erb, app/controllers/collections_controller.rb, app/forms/collection_form.rb, sorbet/rails-rbi/typed_params.rbi, sorbet/rbi/hidden-definitions/hidden.rbi, spec/requests/collections_spec.rb
Allow configuration of the review workflow on collections.
connects to #348
This PR doesn't quite fully implement what's shown in the mockup and described in the design doc.  In particular:
* the enable/disable button is just a basic radio button instead of the cool switch in the mockup (because i wasn't sure how to do that, and wanted to get everything else working).
* the reviewers list field isn't hidden based on whether the radio button is enabled (i wasn't sure how to implement that idiomatically in this code base).
I'm happy to circle back on those two shortfalls in this PR, or in a follow-on PR, whichever seems most appropriate.  Happy to write the ticket for the next part, if doing that in a separate PR is preferable.
* new unit tests
* manual testing locally
n/a
=> Collection form configures review workflow

app/controllers/dashboards_controller.rb, spec/requests/dashboards_spec.rb
Drafts should only show for the user who created them.
=> Display the drafts for the currently logged in user

app/components/works/agreement_component.html.erb, app/javascript/stylesheets/bootstrapVariables.scss, app/javascript/stylesheets/editor.scss
=> Add invalid feedback message for the agreement

app/components/works/contributor_row_component.html.erb, app/components/works/contributors_component.html.erb, app/components/works/file_row_component.html.erb, app/components/works/related_link_component.html.erb, app/components/works/related_link_row_component.html.erb, app/components/works/related_work_component.html.erb, app/components/works/related_work_row_component.html.erb
This was a head-scratcher. Adding a file to the work form and them adding keywords, related links, related works, or contributors *could* result in one or more files being removed. Why? Apparently because of our use of buttons as submit buttons instead of as button-type buttons.
locally. I could not reproduce in the test suite so there are no test changes.
none
=> Fix file removal in work form bug

app/jobs/deposit_job.rb, app/models/contributor.rb, app/services/description_generator.rb, spec/services/description_generator_spec.rb, spec/services/request_generator_spec.rb
Part of #240 -- waiting for Arcadia to provide more complete mappings for roles.
The contributor data from the work form needs to be saved as descriptive metadata in a deposit.
testing locally, running it on stage and seeing that the contributor mappings are being passed into sdr-api, added unit test and tweaked unit test.
=> map contributors from work form into cocina model for deposit

spec/factories/contributors.rb, spec/factories/works.rb, spec/services/description_generator_spec.rb
To add a spec for descriptive metadata mappings for organizational contributors
=> descriptive_generator_spec: add spec for organization contrib

app/components/collections/form_component.html.erb
Can you comment on this change, @astridu?
I have a related question, as well. It looks like the space between the right edge of the text fields in the collection form is noticeably larger than it is in the work form. Compare e.g. [collection name](https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420930437) and [title of deposit](https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420954309). Is this variance intentional? Thanks!
This is done for greater fidelity to the mock-ups.
None
=> Tweak size of text field divs in collections form

app/models/contributor.rb, app/services/description_generator.rb
This small refactoring makes a few small tweaks to the `Contributor` model and `DescriptionGenerator` service that allow the latter to defer to the former regarding how its name is formatted (and what its type is).
It also:
* Tightens up a type signature (though maybe that change is six-of-one-half-dozen-of-the-other as we all learn how to get value out of Sorbet); and 
* Abandons a potentially misleading Ruby hash style where the keys appear as strings but are actually symbols. *e.g.*, `{ "value": "foo" }["value"]` evaluates to `nil` rather than `"foo"` which might be surprising, and the extraneous quotes are doing nothing for us. So, dump them.
CI
None
=> Defer to contributor to have knowledge of its name and type

app/services/description_generator.rb, spec/services/description_generator_spec.rb
Implement the mapping from H2 `RelatedWork` model to Cocina `description` `relatedResource`.
closes #340
example from https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/h2_cocina_mappings/h2_to_cocina_related_resource.txt --
```
1. Related citation
Stanford University (Stanford, CA.). (2020). May 2020 dataset. Atmospheric Pressure. Professor Maya Aguirre. Department of Earth Sciences, Stanford University.
{
"relatedResource": [
{
"type": "related to",
"note": [
{
"value": "Stanford University (Stanford, CA.). (2020). May 2020 dataset. Atmospheric Pressure. Professor Maya Aguirre. Department of Earth Sciences, Stanford University.",
"type": "preferred citation"
}
]
}
]
}
<relatedItem>
<note type="preferred citation">Stanford University (Stanford, CA.). (2020). May …
```
=> DescriptionGenerator: map #related_works to cocina representation

app/controllers/works_controller.rb, spec/requests/works_spec.rb
We don't have a requirement to let in unauthenticated users.
=> Unauthenticated users should not able to view works

app/services/description_generator.rb, app/services/request_generator.rb, sorbet/custom/cocina-models.rbi, spec/services/description_generator_spec.rb
Unfortunately sorbet doesn't understand dry-struct signatures, so I had to manually define a partial interface to Cocina::Models.  We might want to look at moving cocina-models from dry-struct to https://sorbet.org/docs/tstruct
Discussion  in infrastructure meeting today.
=> Use the structs we have rather than defining complex interfaces

app/views/works/show.html.erb, spec/features/create_new_work_spec.rb
Fixes #424
This commit includes a number of enhancements to the show page in line with the most recently requested changes:
* Link to collection in Details section
* Move subtypes from Details to Description section
* Remove contact email from Details section
* Remove stray angle bracket from contact email
* Allow for organizational contributors to show up
* Remove entire Collection section
Locally and CI
None
=> Updates to show page

app/components/works/add_files_component.html.erb, app/javascript/controllers/dropzone_controller.js, spec/components/works/add_files_component_spec.rb
=> Add a clickable button for file upload

app/services/contributors_generator.rb, app/services/description_generator.rb, sorbet/custom/cocina-models.rbi, spec/factories/works.rb, spec/services/contributors_generator_spec.rb, spec/services/description_generator_spec.rb, spec/services/request_generator_spec.rb
part of #240 (map contributors into cocina model)
This PR is mostly focused on getting the h2 contributor details mapped to the cocina model.  My two reference docs from Arcadia:
- https://github.com/sul-dlss-labs/cocina-descriptive-metadata/blob/master/h2_cocina_mappings/h2_to_cocina_contributor.txt#L717
- https://docs.google.com/spreadsheets/d/1CvEd_NODprNhM2D9VfvJBFs1jfAMEUr0kDxXHe2HkL4
This is maybe 85% of the work;  I thought it best to get this up in a PR while I work on the rest, which may be tricky.
The beginnings of these mappings were in the description_generator;  i move those to the new contributors_generator class.
I wrote unit tests, mostly corresponding to Arcadia's mappings, but in 3 cases I haven't yet implemented her specs. I also added a test or two of my own, including …
=> contributor mappings improvements

app/components/works/dates_component.html.erb, app/javascript/stylesheets/editor.scss
if the browser window is large enough
Fixes #383
=> Date range should appear on one line

app/components/works/dates_component.html.erb, app/components/works/dates_component.rb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/forms/edtf.rb, app/forms/edtf_params_filter.rb, app/forms/work_form.rb, app/validators/created_in_past_validator.rb, config/settings.yml, spec/features/create_new_work_spec.rb, spec/forms/work_form_spec.rb, spec/requests/works_spec.rb, spec/validators/created_in_past_validator_spec.rb
This allows the WorkForm to have fewer responsibilities.
This (casting the date parts to a date)  is somewhat required so that we can validate a date is in the future (rather than just the year). So, either we break it out into smaller pieces or it’s going to grow much larger.  See #329
This is all based on what is already in reform-rails: https://github.com/trailblazer/reform-rails/blob/master/lib/reform/form/multi_parameter_attributes.rb
=> Extract the EDTF handling from the WorkForm

.rubocop.yml, app/services/contributors_generator.rb, app/services/description_generator.rb, sorbet/custom/cocina-models.rbi, spec/services/contributors_generator_spec.rb, spec/services/description_generator_spec.rb
Part of #240;   when a contributor in h2 is a "Publisher" it maps to a Cocina "Event" not a "Contributor".  And for fun, you have to combine it with the publication date which is optional.  And for even more fun, Cocina model objects are immutable, so ... 
unit tests from Arcadia's h2 mapping spec for contributors AND a couple of my own added in.
=> publisher contributors correctly mapped to cocina event, not cocina contributor

app/javascript/stylesheets/toggle.scss
Fixes #432, implements suggestions from [blog post](https://www.a11ywithlindsey.com/blog/create-custom-keyboard-accessible-radio-buttons) that was linked in the ticket.
**Note** Because this is a radio button group, when a work type is selected and the work sub-types check-boxes are displayed, the user needs to use the arrow keys to select another work-type. 
Testing suite.
n/a
=> Work types Radio Buttons accessable through keyboard

Gemfile, Gemfile.lock, spec/rails_helper.rb
Remaining contributor mappings will greatly benefit from using super-diff to see what is different in failing test cocina models and xml
=> add super-diff gem to improve data diff in test output

app/components/works/contributor_row_component.html.erb, app/forms/work_form.rb, app/javascript/controllers/contributor_controller.js, app/javascript/controllers/contributors_controller.js, app/javascript/controllers/edit_deposit_controller.js, sorbet/rbi/sorbet-typed/lib/tzinfo/~>1.1/tzinfo.rbi, spec/features/create_new_work_spec.rb, spec/forms/work_form_spec.rb, spec/requests/works_spec.rb
Fixes #386 
- validate that there is at least one contributor at the work form level, as well as client side.  
- Need to disable client side validation for specific fields depending on role selected, which is done via the same JS methods that hide/show input fields.
- Rename `contributor` JS controller to `contributors` controller to be consistent with keywords
Updated tests to add contributors to continue to get them to pass now that contributor is required.
Added some new unit tests
=> add validation for at least one contributor

app/components/dashboard/collection_component.html.erb, app/components/dashboard/collection_component.rb, app/controllers/application_controller.rb, app/javascript/stylesheets/dashboard.scss, app/policies/work_policy.rb, app/views/dashboards/show.html.erb, spec/components/dashboard/collection_component_spec.rb, spec/policies/work_policy_spec.rb
This will support them being able to be versioned. (see #434)
=> Deposits on the dashboard

.rubocop.yml, .rubocop_todo.yml, app/controllers/works_controller.rb, app/forms/contributor_populator.rb, app/models/work_type.rb, app/services/contributors_generator.rb, app/services/description_generator.rb
Per discussion in dev planning 2020-11-17, here is a PR to increase the class length max and the method length max for rubocop.  
- the first commit is a refactor to slightly reorganize the rubocop.yml file (for ease of maintenance);  
- the second commit is the rule changes
- the third commit is the inline comments that must be removed with these rule changes
- the fourth commit is regenerating rubocop_todo (by hand, so maxes aren't increased)
Weigh in below, check the box when you've reviewed the PR at least once.  If there's lively discussion below, we'll move this to an infradev meeting
=> [Full Team Sign Off] Rubocop adjustments

app/components/works/keywords_component.html.erb, app/javascript/controllers/keywords_controller.js
=> Prevent form submission when pressing return in the keyword widget

app/components/works/detail_component.html.erb, app/jobs/deposit_job.rb
Fixes #480 (PURL link not working correctly on show page)
Also fixed an unrelated rubocop issue
In browser
=> ensure PURL link actually links correctly

app/components/works/detail_component.rb
=> HTML should not show up as escaped

app/forms/draft_work_form.rb
Fixes #502 by not inserting a blank form row via the prepopulator when data already exists.
N/A
N/A
=> Do not include a blank form for items that already have data

app/javascript/controllers/nested_form_controller.js
Fixes #504 (bug with new contributor row being removed not validating even though the row was gone).
In the browser
=> removing an association (e.g. extra contributor) should ensure input fields are set to not required

app/controllers/collections_controller.rb, app/controllers/objects_controller.rb, app/controllers/reviews_controller.rb, app/controllers/works_controller.rb, app/jobs/deposit_status_job.rb, app/models/work.rb, sorbet/custom/models/work.rbi, spec/features/create_new_work_spec.rb, spec/jobs/deposit_status_job_spec.rb, spec/models/work_spec.rb, spec/requests/works_spec.rb
So the user can see when their work has been submitted for deposit, but isn't done yet.
Fixes #490
=> Add a depositing state

app/channels/work_updates_channel.rb, app/components/works/approval_component.html.erb, app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, app/controllers/reviews_controller.rb, app/controllers/works_controller.rb, app/javascript/controllers/work_updates_controller.js, app/jobs/deposit_status_job.rb, app/models/work.rb, app/services/event_service.rb, app/views/works/show.html.erb, sorbet/custom/models/work.rbi, spec/channels/work_updates_channel_spec.rb, spec/factories/works.rb, spec/models/work_spec.rb, spec/requests/reviews_spec.rb, spec/services/event_service_spec.rb
Fixes #508
This commit makes the work show page more interactive by updating the display dynamically, via ActionCable, whenever the work undergoes state changes (moving from draft to depositing to deposited, etc.). It also updates the Purl link when the item gets a druid assigned to it. This makes for a more interactive experience, and prevents page reloads for updates. It also serves as a working example of how to use ActionCable to deliver user-facing features.
Question for @astridu: should we animate/highlight/flash these changes when they occur, or is it preferable to go with the more inobtrusive experience (see screen cap below to see current implementation).
Includes:
* Add an ActionCable channel for streaming work updates to clients
* Rename 'return' to 'reject' for consistent …
=> Update work show page with state changes and new PURLs

Gemfile, Gemfile.lock, app/javascript/stylesheets/work.scss, package.json, spec/support/capybara.rb, yarn.lock
This also required using the trunk of capybara because Bootstrap added a smooth-scrolling directive, which causes capybara to be unable to find some elements.  The change in capybara trunk disables smooth scolling and allows the elements to be found
Fixes #512
=> Upgrade Bootstrap to 5.0.0-alpha3

app/models/work.rb, spec/services/event_service_spec.rb
Do this so they know that they should expect a scintilling update to their work any moment now...
I do not love this approach of stuffing HTML in a string in the model, but I also do not have a better approach in my quiver at the moment. Happy to take suggestions and amend.
NONE
=> Entrance users with a spinner

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, app/components/works/state_display_component.rb, app/models/work.rb, app/services/event_service.rb, spec/models/work_spec.rb
The model is for concerns about persistence and the component is for presentation.
=> [Refactor] move display logic from the model to a component

app/services/contributors_generator.rb, app/services/description_generator.rb, spec/services/contributors_generator_spec.rb, spec/services/description_generator_spec.rb
~~[DRAFT] until I get a final confirmation from Arcadia that the implementation of this is as she desired.~~
~~[DRAFT] until team agrees on ordering and primary status implications from H2 UI and cocina models.~~
Part of #240.
unit tests from Arcadia's h2 mapping spec for contributors, with a bunch of TODO / FIXME comments removed!
=> contributor -> cocina model gets status=primary

app/components/works/contributor_row_component.html.erb, app/components/works/contributor_row_component.rb, spec/features/create_new_work_spec.rb
Fixes #519
This is the behavior specified in the design documentation and has been signed off on by the P.O.
CI and local browser
None
=> Prevent removing the top-most contributor in the work form

app/javascript/controllers/edit_deposit_controller.js
Previously it was trying to parse an unparsable response when the server returned a 500.
=> Only attempt to parse errors when the server gives us errors

spec/requests/create_work_spec.rb, spec/requests/edit_work_spec.rb, spec/requests/show_work_spec.rb
One for each create, update and show
Pure refactor, this makes the specs easier to read.  This enabled me to remove a duplicate spec we had hiding among the pile.
=> [Refactor] Split the works spec into three separate specs

app/components/dashboard/collection_component.html.erb, app/policies/collection_policy.rb, spec/components/dashboard/collection_component_spec.rb, spec/factories/collections.rb, spec/features/create_new_collection_spec.rb, spec/features/create_new_work_spec.rb
Fixes #514 by removing the deposit link if the collections status is `first_draft` or `depositing`.
Unit and feature tests
N/A
=> Do not display the deposit button if the collections state is in draft

spec/factories/object_states.rb, spec/factories/works.rb
Trait definitions in FactoryBot are global. This extracts the object state traits into it's own file for clarity.
N/A
N/A
=> Extract shared traits into their own factory

spec/validators/created_in_past_validator_spec.rb
EDTF days and months must be zero padded
Fixes #614
=> Use a properly formatted date as input to edtf

app/policies/collection_policy.rb, app/policies/work_policy.rb, spec/policies/work_policy_spec.rb
Don't allow deposits into collections that are depositing
=> The create work policy depends on the collections state

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, config/locales/en.yml, spec/components/works/detail_component_spec.rb, spec/factories/events.rb
=> Display events on the deposit show page

spec/validators/created_in_past_validator_spec.rb
This test was too simple and simply adding one to the month.  Now it gets a date one month from now.
=> Avoid month 13

app/components/works/contributor_row_component.html.erb, app/components/works/contributor_row_component.rb, app/javascript/controllers/auto_citation_controller.js, spec/components/works/contributor_row_component_spec.rb
Follows on #230 
Organization names were not displaying as authors.
Before:
After
=> Add improved support for organizations in auto citation

docker/app/Dockerfile, docker/workers/Dockerfile
Running `docker-compose build` locally fails because git is not installed in the base `ruby:2.7.2-alpine`
Test suite
Workers and app Dockerfiles updated
=> Install git package to fix failing Docker builds

app/components/buttons_component.html.erb, app/components/buttons_component.rb, app/controllers/collections_controller.rb, app/controllers/works_controller.rb, app/policies/collection_policy.rb, app/policies/work_policy.rb, spec/components/buttons_component_spec.rb, spec/policies/collection_policy_spec.rb, spec/policies/work_policy_spec.rb
Presently it's possible to attempt to save a draft of a depositing collection, which causes an invalid state transition.  This change prevents that from happening
Fixes #626
=> Prevent update_metadata transition when it isn't allowed

app/models/work.rb
This prevents action-policy from checking if we can create a work in one collection and caching that value and applying it to all places.
=> Create a unique policy cache key for non-persisted objects

app/components/dashboard/collection_component.rb, app/controllers/dashboards_controller.rb, app/policies/collection_policy.rb, app/policies/work_policy.rb, spec/policies/collection_policy_spec.rb, spec/policies/work_policy_spec.rb, spec/requests/dashboards_spec.rb
Previously it was only showing the works you deposited.
Fixes #569
=> Summary of collection works on dashboard shows all editable works

app/components/dashboard/collection_component.html.erb, app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, app/components/works/state_display_component.rb, app/models/work.rb, app/views/dashboards/show.html.erb, config/locales/en.yml, spec/components/works/detail_component_spec.rb, spec/factories/object_states.rb, spec/features/mediated_deposit_versioning_spec.rb, spec/models/work_spec.rb, spec/requests/dashboards_spec.rb, spec/requests/reviews_spec.rb
Fixes #576
Fixes #581
For #576:  display appropriate status for work rejected by reviewer
For #581:  display comments from reviewer if work was rejected
Amy reviewed the changes for #581 in stage;   tests added for both issues with their commits.
=> Display reason and status for Returned reviews

README.md
a badge is more useful if it points to the correct project
=> codeclimate badge points to THIS project

app/components/buttons_component.html.erb, app/components/buttons_component.rb, app/controllers/objects_controller.rb, app/javascript/modules/validate-forms.js, spec/components/buttons_component_spec.rb, spec/features/mediated_deposit_versioning_spec.rb
Fixes #544 - the "Deposit" button for a work should be "Submit for approval" for works in collections with an approval process.
(only for works in collections with review process)
unit tests, Amy reviewed it in qa environment.
=> label Deposit/Submit for Approval button as appropriate

app/views/dashboards/show.html.erb
Small follow on for #641 ... one spot on the dashboard that will not show the name of a collection if it is in draft and blank ... this fixes it 
**Before:**
**After:**
Browser
=> for collections with no title, render the default title in the deposits in progress

app/components/works/detail_component.rb, app/mailers/application_mailer.rb, app/mailers/notification_mailer.rb, app/models/user.rb, app/models/work.rb, app/views/notification_mailer/reject_email.html.erb, config/application.rb, config/environments/test.rb, config/routes.rb, config/settings.yml, spec/factories/object_states.rb, spec/mailers/notification_mailer_spec.rb, spec/mailers/previews/notification_mailer_preview.rb, spec/models/work_spec.rb
fixes #594
Using mailer previews (e.g. http://localhost:3000/rails/mailers/notification_mailer/reject_email) and the test suite.
=> Send an email notification when the work is rejected

config/settings.yml
Instead of depending on an environment variable that may or may not be set.
CI
None
=> Use Rubyish way to get hostname

app/components/works/state_display_component.rb, config/locales/en.yml, spec/requests/dashboards_spec.rb
This is consistent with how we are handling workflow events
=> [Refactor] Move state labels to i18n

app/components/works/detail_component.html.erb
Fix #668 (remove empty <th> column and just make first column span the table)
Local browser
=> remove blank <th> column for accessibility

config/database.yml
This prevents Rails from warning the developer about using the same database for both dev and test, which most of us developers are straddling frequently. This **does not affect deployed environments** because the checked-in `config/database.yml` is overwritten with a file that is managed via Puppet. This is intended to remove drag on development.
CI, locally
See above.
=> Differentiate between test and dev database names

app/components/works/description_component.html.erb, app/components/works/description_component.rb, spec/components/works/description_component_spec.rb
One of the labels did not have the proper id for the checkbox, resulting in an unlabeled input component; an accessability cocncern.
=> Label all checkboxes

app/components/works/add_files_component.html.erb, app/javascript/controllers/edit_deposit_controller.js, app/javascript/controllers/files_controller.js, spec/features/create_new_work_spec.rb
fixes #560
Manually on my laptop.  I was unable to get a feature test working for this, and jcoyne mentioned that writing one might be a pain and not worth the trouble, so i'm omitting it from this PR (but will write more detailed steps to reproduce on the ticket, should someone want to test, and i'm happy to also test on stage myself).  Though in trying to write that test, I found a couple seemingly easy touchups I could make to the test code i was using as a guide, and I left those changes in.
n/a
=> Deposit: clear stale server-side form validation errors after valid data is entered

app/components/works/description_component.html.erb, spec/features/create_new_work_spec.rb
Fixes #669
Tested locally by using the Firefox accessability tool. There are no user visible changes aside from margins below the subtypes, which more closely resemble the mockups:
Before:
=> Add labels for the citation and the auto-citation fields

Gemfile, Gemfile.lock
=> Update capybara to 3.34

.rubocop.yml, app/components/collections/form_component.html.erb, app/components/works/add_files_component.html.erb, app/components/works/contributors_component.html.erb, app/components/works/embargo_component.html.erb, app/components/works/related_link_component.html.erb, app/components/works/related_work_component.html.erb, config/locales/en.yml, sorbet/rails-rbi/routes.rbi, spec/features/mediated_deposit_spec.rb, spec/features/mediated_deposit_versioning_spec.rb, spec/models/work_spec.rb, spec/requests/dashboards_spec.rb
Fixes #707
This changes the app to use labels approved by the P.O.
Also includes:
* Avoid deprecation warnings by using Stimulus 2-style data targets
* Avoid Rubocop warnings
CI
None
=> Update labels for version draft and pending approval states

app/controllers/helps_controller.rb, app/mailers/helps_mailer.rb, app/views/helps_mailer/jira_email.text.erb, spec/mailers/helps_mailer_spec.rb, spec/mailers/previews/helps_mailer_preview.rb
The HelpsMailer should be used in the idiomatic way, that is, by using deliver_later.
=> Refactor the help mailer to send in the background

app/components/works/contributor_row_component.html.erb, app/components/works/related_link_row_component.html.erb, app/components/works/related_work_row_component.html.erb, app/views/dashboards/show.html.erb
Keeps the create a collection button floating to the right. Bootstrap changed the class name to be compliant with RTL languages.
After
Before
=> Update float classes for bootstrap 5

app/components/collections/form_component.html.erb, app/components/dashboard/collection_component.html.erb, app/components/help/form_component.html.erb, app/components/works/approval_component.html.erb, app/components/works/work_form_component.html.erb, spec/features/mediated_deposit_versioning_spec.rb
Consistency is good. In doing this work, I replaced a single usage of `form_for` with `form_with` so the app does not use a mix of local and remote forms, and removed the model argument to this call which is/was unused. This commit also explicitly marks all of our forms as remote forms for future-proofing, as we know an upcoming Rails 6.1 change will make `form_with` default back to local forms.
I found that the mediated deposit versioning spec was flappy locally because there can be two links on the page with the work title, so I changed the spec to look for the link only in the scope of the collection name (the deposits in progress section). To do this, I moved the collection name from a section header to a table caption. I do not notice any UI difference with this change.
CI, local …
=> Use remote forms consistently across app

app/components/collections/history_component.html.erb, app/components/collections/history_component.rb, app/views/collections/show.html.erb, sorbet/rails-rbi/mailers/notification_mailer.rbi, sorbet/rails-rbi/models/collection.rbi, sorbet/rails-rbi/models/related_link.rbi, spec/components/collections/history_component_spec.rb, spec/factories/collections.rb, spec/requests/show_collection_spec.rb
Fixes #700 
Adds the history table:
Unit.
=> Add the collection events to the show page

app/components/collections/information_component.html.erb, app/components/collections/participants_component.rb, app/components/collections/workflow_review_component.rb, sorbet/rails-rbi/models/collection.rbi, sorbet/rails-rbi/models/related_link.rbi, spec/components/collections/information_component_spec.rb, spec/components/collections/participants_component_spec.rb, spec/components/collections/workflow_review_component_spec.rb, spec/requests/show_collection_spec.rb
Fixes #692 
Before:
After:
Updated unit and request tests
=> Remove email domain from display of email usernames

app/components/dashboard/collection_component.html.erb, app/components/dashboard/collection_component.rb
This disentangles the relation that is used to display works and the one that is used to determine whether to render a link to view more works, and gives more names to things vs. relying on integers (primitive obsession).
CI
None
=> Refactor how dashboard collection component determines how many works to show

config/environments/production.rb
So that images link back to our server and aren't relative
Fixes #729 
Tested on QA
=> Set the mail asset host

app/jobs/deposit_status_job.rb
I'm pretty sure this occurs because state-machine has a transaction that doesn't complete until all the after hooks run, so it's possible a job is picking up the email before the work is saved.
Fixes #734
Fixes #744
Fixes #746
Fixes #751
=> Prevent no route matches {} error

app/models/work_type.rb, spec/services/request_generator_spec.rb
Andrew says the "document" option will only work if they upload a single PDF.
=> Set the cocina content type to object if user selected text

Gemfile, Gemfile.lock
to keep in sync with tiny cocina-models change for a dor-services-app mapping ticket.
=> update sdr-client to 0.39

app/controllers/collections_controller.rb, app/controllers/works_controller.rb, app/mailers/collections_mailer.rb, app/models/collection.rb, app/views/collections_mailer/deposit_access_removed_email.html.erb, spec/mailers/collections_mailer_spec.rb, spec/mailers/previews/collections_mailer_preview.rb, spec/models/collection_spec.rb, spec/requests/create_collection_spec.rb, spec/requests/edit_collection_spec.rb
For consistency with where other mails are sent from.
Test suite.
=> Send a mail when deposit access is revoked

app/components/works/detail_component.html.erb
remove what appear to be stray/leftover conflict markers from a rebase git couldn't merge automatically.
reported by @amyehodge on slack:
unit tests, manual testing of the page locally.
before:
after:
not totally sure i chose the correct thing to keep, so would appreciate a look from @jcoyne 
n/a
=> remove merge conflict markers and guess at which part to keep

db/migrate/20201214213408_collection_values_optional.rb, db/structure.sql
We want to allow drafts to be saved without requiring everything.
=> Allow collection values to be nil 

app/components/collections/history_component.html.erb
=> Add missing headers to the collection details page

app/components/collections/works_component.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml
This is quite straight forward:
Manual review
N/A
=> Add simple-DataTable sorting to collection works display

.rubocop.yml, app/services/stat_builder.rb, spec/requests/dashboards_spec.rb
Fixes #776
This refactoring of StatBuilder allows all collections to render in the All Collections component within the dashboard. To my eyes, the class is now also easier to grok.
CI
None
=> Allow empty collections to appear in All Collections

app/models/work.rb, app/services/work_observer.rb
This contains business logic that is triggered when state transitions occur. Business logic should not be in the model class.
=> Extract WorkObserver from work

app/components/works/license_component.html.erb, app/components/works/license_component.rb, spec/components/works/license_component_spec.rb
This fixes a bug where the topmost license is always presented as the currently selected one.
CI
None
=> Display currently selected license in work form

app/components/collections/work_row_component.html.erb, app/components/dashboard/approvals_component.html.erb, app/components/dashboard/collection_component.html.erb, app/components/works/link_to_show_component.html.erb, app/components/works/link_to_show_component.rb, spec/components/collections/works_component_spec.rb, spec/components/works/link_to_show_component_spec.rb
And display the full title as a mouseover
Fixes #802 
Fixes #803 
Fixes #804
=> Truncate titles over 150 characters

app/forms/draft_work_form.rb, app/forms/edtf.rb, app/forms/embargo_date_params_filter.rb, sorbet/rails-rbi/mailers/collections_mailer.rbi, spec/components/works/dates_component_spec.rb, spec/components/works/embargo_component_spec.rb, spec/factories/works.rb, spec/forms/work_form_spec.rb, spec/requests/create_work_spec.rb
Fixes #771
To fix a bug in deployed environments that could change values previously set by the user.
Also includes:
* Disentangle embargo and contributor validation in work form test 
* And add a new factory for valid works for more descriptive factory names in specs
CI and in the browser locally and in QA
None
=> Render work form creation & embargo date radio buttons based on current values

.rubocop.yml, app/components/collections/history_component.html.erb, app/mailers/collections_mailer.rb, app/models/collection.rb, app/models/collection_change_set.rb, app/services/collection_observer.rb, app/views/collections_mailer/participants_changed_email.html.erb, spec/factories/collections.rb, spec/mailers/collections_mailer_spec.rb, spec/mailers/previews/collections_mailer_preview.rb, spec/requests/edit_collection_spec.rb, spec/services/collection_observer_spec.rb
close #596 
close #781 
unit tests, manual testing on local instance (see screenshots)
n/a
=> track participant changes and send participant change email

app/components/collections/form_component.html.erb, app/components/collections/form_component.rb, sorbet/rails-rbi/mailers/collections_mailer.rbi, sorbet/rails-rbi/mailers/works_mailer.rbi
Make the collection form params consistent and get rid of reform indirection
Unit tests
=> make collection form consistent with other attribute retrieval

app/controllers/collections_controller.rb, app/models/collection_change_set.rb, spec/models/collection_spec.rb, spec/services/collection_observer_spec.rb
slightly clearer code, hopefully?  in particular, i was briefly confused by the fact that `CollectionChangeSet.from` returned a `PointInTime` (i expected a `CollectionChangeSet` based on the method name).
hopefully the type annotations, and the method and var renaming make things a bit more obvious.
type checker and unit tests
type annotations
=> small CollectionChangeSet refactor

app/components/dashboard/in_progress_component.html.erb, app/components/dashboard/in_progress_component.rb, app/controllers/dashboards_controller.rb, app/presenters/dashboard_presenter.rb, app/views/dashboards/show.html.erb, spec/components/dashboard/in_progress_component_spec.rb, spec/features/mediated_deposit_versioning_spec.rb, spec/requests/dashboards_spec.rb
Fixes #847
This PR adds to the "in progress" section of the dashboard, which previously displayed only works in the first draft state, by also displaying works in the version draft and rejected states. As part of this work, rename the `drafts` attr of the DashboardPresenter to be more accurate, and extract a view component for this section of the dashboard.
CI, and tested by @amyehodge in QA
None
=> Show returned and version draft works as in progress in dashboard

app/mailers/collections_mailer.rb, app/services/collection_observer.rb, app/views/collections_mailer/manage_access_granted_email.html.erb, spec/mailers/collections_mailer_spec.rb, spec/services/collection_observer_spec.rb
Fixes #599 by adding a notification when manage access is granted.
Unit.
=> Send a notification when manage access is granted

app/services/collection_generator.rb, app/services/request_generator.rb, config/settings.yml, spec/services/collection_generator_spec.rb, spec/services/request_generator_spec.rb
Fixes #838
This commit attaches an attribute to the Cocina registration parameters that allows SDR to associate H2 works and collections with the "Project : H2" project tag, as requested by the P.O.
CI
None
=> Tag works and collections with H2 project tag

app/mailers/collections_mailer.rb, app/services/collection_observer.rb, app/views/collections_mailer/review_access_removed_email.html.erb, spec/mailers/collections_mailer_spec.rb, spec/services/collection_observer_spec.rb
Fixes #600 by adding the notification for removal of reviewers,
Unit
=> Add review access removed notification mailer

config.ru
Without this change the server won't start and will give the error:
```
/Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:233:in `to_app': missing run or map statement (RuntimeError)
```
=> Fix the rack configuration for Rails 6.1

app/views/collections/errors.json.jbuilder, app/views/works/errors.json.jbuilder
Rails 6.1 has a new errors API
=> Avoid the deprecated errors API

app/components/collections/cancel_component.html.erb, app/components/works/cancel_component.html.erb, spec/features/create_new_collection_spec.rb, spec/features/edit_draft_work_spec.rb
Fixes #892 - add a confirmation to the cancel button shown on edit pages to verify user will lose changes if clicked.  Already discussed with Astrid and Amy.
None
=> add confirmation to cancel buttons on edit pages

app/components/collections/form_component.html.erb, app/components/collections/workflow_review_component.rb, app/javascript/controllers/complex_radio_controller.js, spec/features/single_radio_selection_spec.rb
Fixes #796
This PR introduces a new Stimulus controller that can make sure only the currently selected radio button has any child select elements enabled. This is only being used in the collection edit form for release/embargo options, currently, but the approach can be extended to other radio buttons in forms within the application. Since the work is primarily done on the client side, a feature spec is used for testing the change in behavior.
CI and in local browser
None
=> Disable child select elements of unselected radio buttons in collection form

app/components/collections/works_component.html.erb, app/components/dashboard/in_progress_component.html.erb, app/javascript/controllers/datatables_controller.js, app/javascript/packs/application.js, package.json, spec/features/edit_draft_work_spec.rb, yarn.lock
This commit uses Stimulus to setup the simple-datatables library, making sure the DataTable class is imported when needed. Without this change, the data table only renders after reloading the page because of turbo(links).
CI + local browser + QA
None
=> Render datatables on collection works page

app/components/breadcrumb_nav_component.html.erb
=> Align the breadcrumbs with the SUL icon

app/components/works/publication_date_component.html.erb, app/components/works/publication_date_component.rb
as with creation dates, ensure that the user can't enter incomplete dates (e.g. month with no year)
fixes #872
I tested on my local instance, and an incomplete publication date both flagged an error and prevented form submission.
When I tried to submit, there was no explanation of the error at the top of the page, but the box that needed a year was highlighted with an explanation as to what needed correcting (this seems to be the same as the behavior of the creation date field).  Happy to revisit that in this PR or a follow on if that's desired.
I also didn't add a feature test, as I was cribbing from #758, which also declined to add a test.  But similarly, happy to work on testing these validations if we'd prefer to give that another shot.
n/a
=> client side-validation of publication dates

README.md
And include in the new section information about running the webpack dev server.
Transparency and useful information.
It was not.
README
=> Create a new development section

app/components/works/form_component.rb
I believe this may have started when we switched back to local form.
Fixes #915
=> Loosen type declarations for Works::FormComponent

app/components/works/available_date_component.html.erb, app/components/works/available_date_component.rb, app/components/works/form_component.html.erb, spec/components/works/available_date_component_spec.rb, spec/components/works/form_component_spec.rb
=> Display validations when the embargo date is invalid

app/components/collections/edit_license_component.html.erb, app/components/works/work_type_modal_component.html.erb, app/javascript/stylesheets/bootstrapVariables.scss, app/javascript/stylesheets/collectionEditor.scss, app/javascript/stylesheets/embargo.scss
Fixes #940 
To fix style-related bugs.
CI and local browser. See screenshots above.
None
=> Fix work type modal and collection form styles

app/components/collections/edit_license_component.html.erb, app/components/collections/edit_license_component.rb, app/validators/collection_license_validator.rb, spec/components/collections/edit_license_component_spec.rb, spec/features/create_new_work_spec.rb, spec/validators/collection_license_validator_spec.rb
Follows the approach used in https://github.com/sul-dlss/happy-heron/pull/928 and https://github.com/sul-dlss/happy-heron/pull/919
Also, fixes the build.
Consistency and kinder UX. Note that the UI looks messed up in the screen shot due to #929 not having been merged yet.
None
=> Display collection license validation inline in the form

app/forms/draft_work_form.rb, app/forms/work_form.rb
Because we only require these validations when the user is trying to deposit.  Ref #932
=> Move validations to the WorkForm

app/components/breadcrumb_nav_component.html.erb, app/javascript/stylesheets/bootstrapVariables.scss, app/javascript/stylesheets/suNavbar.scss, app/views/layouts/application.html.erb
A better alignment with the design
=> Make a better background

app/components/works/embargo_component.rb, app/forms/draft_work_form.rb, config/locales/en.yml, spec/components/works/access_component_spec.rb, spec/components/works/embargo_component_spec.rb, spec/components/works/form_component_spec.rb, spec/factories/collections.rb, spec/features/create_new_work_spec.rb, spec/requests/create_work_spec.rb
Fixes #697 by removing the selection list if the collection has an access right set other than `depositor-selects`.
When stanford:
TBD
N/A
=> Only allow access selection if collection is depositor-selects

app/components/breadcrumb_nav_component.html.erb, app/components/breadcrumb_nav_component.rb, app/components/dashboard/in_progress_row_component.html.erb, app/components/dashboard/in_progress_row_component.rb
Fixes #953 - truncate collection and work title lengths in breadcrumb navigation and in-progress section of dashboard
Unit test and localhost browser
=> truncate long titles in breadcrumbs

app/components/dashboard/deposit_progress_component.html.erb, app/components/dashboard/deposit_progress_component.rb, app/components/works/add_files_component.html.erb, app/components/works/agreement_component.html.erb, app/components/works/deposit_progress_component.html.erb, app/components/works/title_component.html.erb, app/javascript/controllers/edit_deposit_controller.js, sorbet/rails-rbi/models/abstract_contributor.rbi, sorbet/rails-rbi/models/author.rbi, sorbet/rails-rbi/models/contributor.rbi
Fixes #969 : 
- add "terms" to progress bar on both dashboard and edit work page.
- ensure terms progress field is updated dynamically when you check/uncheck on edit work page
- fix misnamed JS controller reference in other terms on edit work page
- use a different selector for the files that accurately reflects when files exist (previous selector always return length == 0, so that it never looked like files had been uploaded)
NOTE: when working on this, it appears multiple other fields in the terms progress bar on the edit work page are not being updated right now:
- author, description, release, license
Unit tests
=> add terms to progress bars

app/components/dashboard/collection_component.rb
By adding an order by clause to the query
Fixes #805
=> Display the most recent changed works for the collection

app/components/dashboard/in_progress_row_component.html.erb, app/components/dashboard/in_progress_row_component.rb, spec/requests/dashboards_spec.rb
=> Add pencil icons that are edit links to the items in progress

app/components/dashboard/deposit_progress_component.rb, spec/components/dashboard/deposit_progress_component_spec.rb
=> Require the email to be entered before the title is marked as complete

bin/spring
i.e. in production.
This allows us to do `bin/rails c -e p` on the servers again
See: https://github.com/rails/rails/pull/40913
=> Ignore spring when it is not installed

.rubocop.yml
there are new rubocop rules that were added and are noted each time rubocop is run now, add them to `.rubocop.yml`
rubocop passes with new rules (yay)
=> add new rubocop rules that were recently enabled

app/components/works/contributor_row_component.html.erb
=> Update label for organizational name

app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/work_type_controller.js, app/javascript/stylesheets/dashboard.scss, app/javascript/stylesheets/toggle.scss, app/models/work_type.rb, spec/models/work_type_spec.rb
Connects to #716
In order to:
1. Bring the work type modal styles more in line with the mock-ups and the desired look & feel; and
2. Refactor work type modal-related code to make it easier/clearer to do the work in #716 
Includes:
* Make work type modal appearance more closely resemble mock-ups (see mock-up below!)
* Increase padding between work type icon and work type text
* Shrink space between work type boxes
* Lighten background shade of selected work type box to increase contrast
* Increase size of selected work type check box
* Shade selected check box red (instead of black)
* Keep HTML for work type modal header in partial (instead of in JavaScript)
* Move JSON conversion into WorkType class
None
=> Improve work type modal style and refactor in advance of modal changes

app/models/work.rb, app/policies/work_policy.rb, spec/models/work_spec.rb
Fixes #996 - if an item has been submitted for approval, it is still possible for certain people (like a collection manager) to edit it ... this allows it to be saved correctly by keeping the state the same
Localhost browser and new unit test
=> allow saving of works that are in the pending_approval states by collection managers

app/services/types_generator.rb, config/mappings/types_to_genres.yml, config/mappings/types_to_resource_types.yml, sorbet/rails-rbi/models/collection.rbi, spec/services/types_generator_spec.rb
Fixes #939 - allow resource type and genre mappings of top level work types (without subtype selected) 
Note, it looks like all of the mappings changed in the .yml, but they did not.  Instead, all of the subtype mappings became nested in a new `subtypes` header, allowing a `type` header for mapping a work type without subtypes.
New and existing unit tests
Mapping spreadsheet: https://docs.google.com/spreadsheets/d/1EiGgVqtb6PUJE2cI_jhqnAoiQkiwZtar4tF7NHwSMz8/edit#gid=387882643
=> allow types with no subtypes to be mapped

app/components/collections/header_component.html.erb, app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/work_type_controller.js, app/javascript/stylesheets/dashboard.scss, app/models/work_type.rb, app/validators/work_subtype_validator.rb, app/views/dashboards/show.html.erb, config/mappings/types_to_genres.yml, config/mappings/types_to_resource_types.yml, spec/components/works/description_component_spec.rb, spec/factories/works.rb, spec/features/create_new_work_spec.rb, spec/features/mediated_deposit_versioning_spec.rb, spec/forms/work_form_spec.rb, spec/models/work_spec.rb, spec/models/work_type_spec.rb, spec/requests/create_work_spec.rb, spec/services/description_generator_spec.rb, spec/services/request_generator_spec.rb, spec/services/types_generator_spec.rb
Fixes #716
Includes:
* Pull surrounding `<div>`s into the work type modal component to reduce copypasta
* Allow work types to contain *any* subtypes including "more" types
* Add `WorkType.more_types` to prevent collaborators from needing to know the internal structure of the class; prefer message-sending
* Use the message-sending approach from within the work type modal ERB
* Add optional param to `WorkType.subtypes_for` that allows adding "more" types to subtypes which are now valid subtypes
* Add feature spec to test "See more options" link in work type modal
* Adjust tests to reflect changes to work type and subtype validation
NOTE: Until #972 is done, the "more" types selected for a work type **WILL NOT** be visible in the work form. I'm taking that issue next.
None
=> Add collapsible "see more/fewer options" link to work type modal

app/components/collections/terms_of_use_component.html.erb, app/components/collections/terms_of_use_component.rb, app/forms/draft_collection_form.rb, app/models/collection.rb, db/migrate/20210208201246_add_license_option_to_collection.rb, db/structure.sql, spec/components/collections/terms_of_use_component_spec.rb, spec/factories/collections.rb, spec/features/single_radio_selection_spec.rb, spec/forms/collection_form_spec.rb
So we can store the radio button choice separate from whether a license was chosen.
Fixes #958
=> Add a field for license_option

app/components/collections/participants_component.rb, app/controllers/dashboards_controller.rb, app/forms/draft_collection_form.rb, app/models/collection.rb, app/models/collection_change_set.rb, app/models/work.rb, app/policies/application_policy.rb, app/policies/collection_policy.rb, app/policies/work_policy.rb, app/services/collection_observer.rb, app/services/work_observer.rb, app/views/collections_mailer/deposit_access_removed_email.html.erb, app/views/collections_mailer/manage_access_removed_email.html.erb, app/views/collections_mailer/review_access_removed_email.html.erb, sorbet/rails-rbi/models/collection.rbi, sorbet/rails-rbi/models/work.rbi, spec/components/collections/participants_component_spec.rb, spec/factories/collections.rb, spec/features/delete_draft_collection_spec.rb, spec/features/single_radio_selection_spec.rb, spec/jobs/deposit_status_job_spec.rb, spec/models/work_spec.rb, spec/policies/collection_policy_spec.rb, spec/policies/work_policy_spec.rb, spec/requests/create_collection_spec.rb, spec/requests/edit_collection_spec.rb, spec/requests/show_collection_spec.rb, spec/requests/show_works_in_collection_spec.rb, spec/services/collection_observer_spec.rb
This required the association 'managers' to be renamed to 'managed_by' similar to how we use 'reviewed_by'.  See #780 See rails/rails#41010
Fixes #1005
=> Make approvals visible to collection managers

app/models/license.rb, spec/features/create_new_work_spec.rb, spec/models/license_spec.rb
=> Reorder the license groups so that CC-PDDC is lower on the list

app/components/dashboard/in_progress_collection_component.html.erb, app/components/dashboard/in_progress_collection_component.rb, app/components/dashboard/in_progress_collection_row_component.html.erb, app/components/dashboard/in_progress_collection_row_component.rb, app/components/works/contact_email_component.rb, app/controllers/dashboards_controller.rb, app/presenters/dashboard_presenter.rb, app/views/dashboards/show.html.erb, spec/components/dashboard/in_progress_collection_component_spec.rb, spec/components/dashboard/in_progress_collection_row_component_spec.rb, spec/components/dashboard/in_progress_component_spec.rb, spec/features/delete_draft_collection_spec.rb, spec/requests/dashboards_spec.rb
Fixes #946 - add an in progress section to the top of the dashboard, but for collections (not works) that are in a draft state and for which the user is defined as a collection manager
To do:
Todo
=> add collections in progress section for collection managers

app/components/dashboard/in_progress_collection_row_component.html.erb
Fix styling of collections in new progress panel for collection managers.
Before:
After:
=> bottom margin belongs on button, not entire row

app/components/works/description_component.html.erb, app/components/works/description_component.rb, app/components/works/subtypes_component.html.erb, app/components/works/subtypes_component.rb, app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/edit_deposit_controller.js, app/javascript/stylesheets/dashboard.scss, spec/features/create_new_work_spec.rb, spec/features/edit_draft_work_spec.rb
Fixes #972
To allow "more" types to be edited.
The link does not appear and the work types header is not marked as optional:
The link appears, the "more" types are collapsed, and the header is marked as optional:
The link appears, the "more" types are expanded, and the header is marked as optional:
CI and local browser
None
=> Add collapsible "more" work types to work form

app/components/works/subtypes_component.html.erb, app/components/works/subtypes_component.rb, app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/work_type_controller.js, app/javascript/stylesheets/dashboard.scss, app/javascript/stylesheets/main.scss, app/javascript/stylesheets/workTypes.scss, app/models/work_type.rb, app/validators/work_subtype_validator.rb, config/mappings/types_to_genres.yml, config/mappings/types_to_resource_types.yml, spec/components/works/subtypes_component_spec.rb, spec/features/edit_draft_work_spec.rb, spec/requests/create_work_spec.rb
Fixes #715
This commit adds a new music work type, which is unique in that it requires one or more primary subtypes to be selected.
Includes:
* Extract work type-related styles into a dedicated file to fix a bug with the display of the work type modal when clicked from collection show page
* Pad work type boxes in modal to render three per row instead of four
* Make work type stimulus controller able to render a subheader for music-type works
* Change subtype validator so it can enforce music-type works' unique constraint (see above)
* Add genre and resource type mappings for music-type works
CI + local
None
=> Add new work type for Music-type works

app/forms/collection_form.rb, app/forms/draft_collection_form.rb, app/models/contact_email.rb, spec/models/contact_email_spec.rb, spec/requests/create_collection_spec.rb
Fixes #1044 
- need to remove all validation from the `DraftCollectionForm` to have it work properly
- need to remove model level validation for `ContactEmail`, else you cannot save a draft collection with invalid emails (since it needs to persist to the database, and the model level validation will block it)
- add validation for contact emails to the `CollectionForm` to ensure it gets validated when you try and deposit
- added tests to verify you can save draft collections with missing or bogus contact emails
- updated and added tests 
**Notes**:
Seems to be some fallout from #893 and #842 .... you cannot save a draft collection when leaving the contact email blank or when submitting an invalid contact email.  The problem seems to stem from the fact that we do this validation on the …
=> allow collections to be saved with no contact emails

app/components/collections/edit_link_component.rb, app/components/dashboard/in_progress_row_component.html.erb, app/components/dashboard/in_progress_row_component.rb, app/components/works/edit_link_component.rb, spec/features/edit_draft_work_spec.rb
- Users should only see edit icons/links if they are allowed to edit a collection or work.
- Refactor one spot where we create a edit work link to use the component instead
- Update specs
- Also fixes #943 (sorry @jcoyne didn't see you had this in progress), work text in progress bar should link to work show page, not work edit page
Unit tests and localhost browser
=> only show edit icons when user is allowed to edit works or collections

app/components/works/subtypes_component.html.erb, app/components/works/subtypes_component.rb, app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/work_type_controller.js, app/models/work_type.rb, app/validators/work_subtype_validator.rb, spec/components/works/subtypes_component_spec.rb, spec/requests/create_work_spec.rb
Fixes #609
This commit adds the desired behavior to the existing mixed material work type, which is unique in that it requires two or more primary subtypes to be selected.
Includes:
* Make work type stimulus controller able to render a subheader for mixed material-type works
* Change subtype validator so it can enforce mixed material-type works' unique constraint (see above)
CI
None
=> Introduce subtype requirements for mixed material-type works

app/components/works/agreement_component.html.erb, app/controllers/print_controller.rb, app/views/layouts/application.html.erb, app/views/print/terms_of_deposit.html.erb, app/views/shared/_terms_of_deposit.html.erb, app/views/welcome/show.html.erb, config/routes.rb, config/settings.yml, spec/features/print_spec.rb, spec/requests/print_spec.rb
Fixes #1020 and prep for #1022:
- update text of terms of deposit as shown in https://docs.google.com/document/d/1fcr2DYo7OrX-qTdeUOTWKSS1rlq_47sehESmbvgUsrk/edit#heading=h.ab2g8b5m7wat
- move text to a shared partial and add to app layout so we can add a link to the top nav
- add print button to top of terms of deposit modal that links to new print page 
- add new page with no layout/css to ensure clean printing of of terms of deposit
- add link to the terms of deposit modal from the top nav of every page
- add save button to top of modal which links to PDF version of terms (after discussion with Amy)
Note: approach approved by Amy
**New link in header:**
**New buttons on terms modal:**
**Plain print window that opens print dialog by default:**
Localhost browser, new request spec
=> update text in terms of use modal, add print window, and link in nav

app/components/collections/participants_component.html.erb
=> Add missing style to move the caption back to the top of the table

app/components/works/dates_component.html.erb
=> Apply bootstrap classes to approximate checks

app/components/works/add_files_component.html.erb, app/components/works/agreement_component.html.erb, app/components/works/deposit_progress_component.html.erb, app/components/works/form_component.html.erb, app/components/works/title_component.html.erb, app/controllers/validates_controller.rb, app/forms/attached_files_populator.rb, app/javascript/controllers/edit_deposit_controller.js, app/views/validates/_validate.html.erb, config/routes.rb, spec/components/works/deposit_progress_component_spec.rb, spec/components/works/form_component_spec.rb, spec/requests/validate_request_spec.rb
Fixes #935 
This makes the progress component on the edit form fully functional and identical to the behavior on the dashboard
=> Calculate the progress component on the backend

app/controllers/validates_controller.rb, spec/requests/validate_request_spec.rb
Running the validation endpoint was causing dupliate has_many associations to be persisted.
=> Validate should not cause records to persist

.rubocop.yml, app/components/works/detail_component.rb, app/components/works/license_component.html.erb, app/models/license.rb, app/models/work.rb, spec/models/license_spec.rb, spec/models/work_spec.rb
Fixes #1047
This change is intended to help migrate Hydrus 1 data into Hydrus 2, and to display migrated works with their current (CC 3.0) licenses. It allows a small set of displayable licenses to show both in the work show page and on the work form. Before a new version of such a work may be deposited again, a new H2 license must be selected.
Includes:
* Remove license validation from work model
* We are already validating licenses in the work form so this is not necessary and is counter to our approach to validation where we favor form validation over modal validation. This also allows us to migrate *any* license from Hydrus 1.0.
None
=> Allow works to have a small number of legacy licenses

app/components/collections/form_component.html.erb, app/components/collections/form_component.rb, app/components/collections/release_component.html.erb, app/components/collections/release_component.rb, app/components/works/embargo_component.rb, app/controllers/collections_controller.rb, app/forms/draft_collection_form.rb, app/models/collection.rb, db/migrate/20210216220559_remove_release_date_from_collection.rb, db/structure.sql, spec/components/works/embargo_component_spec.rb, spec/factories/collections.rb, spec/features/single_radio_selection_spec.rb, spec/requests/create_collection_spec.rb, spec/requests/create_work_spec.rb
Fixes #966 
On the new collection entry:
On the collection show page:
On the work entry page when release is set to `delay`:
On the work show page:
Unit tests updated and manually verified.
=> Replace collection release date selector with release options

app/views/collections_mailer/invitation_to_deposit_email.html.erb
Fixes #1053 - update email text for deposit notification email
Note: Hold until #1052 is merged, since it uses a setting for showing the terms of deposit in Box
=> Update email text for invitation to deposit

app/components/works/embargo_component.html.erb, app/components/works/embargo_component.rb, spec/components/works/embargo_component_spec.rb
Fixes #336
This commit makes sure not to suggest that files are available shortly after the depositor clicks the deposit button when the collection requires review workflow, in which case the deposit button is the "submit for review" button and requires human intervention before the deposit is approved.
CI
None
=> Vary work embargo component availability text based on collection

app/components/citation_component.rb, app/components/citation_modal_component.html.erb, app/components/citation_modal_component.rb, app/components/collections/header_component.html.erb, app/components/collections/work_row_component.html.erb, app/components/dashboard/collection_component.html.erb, app/javascript/controllers/show_citation_controller.js, app/views/dashboards/show.html.erb, spec/components/citation_component_spec.rb, spec/components/citation_modal_component_spec.rb, spec/components/collections/works_component_spec.rb
=> Add a button to open the citation modal

app/components/works/authors_component.html.erb
This restores the ability to remove authors
Fixes #1091
=> Fix typo in authors component

app/javascript/stylesheets/workTypes.scss
We don't load the Fontawesome font.
Fixes #1087
=> Fix the icon for displaying more

app/services/work_observer.rb
This was a regression introduced in 1fca823e718a33bd918d60fb8c24662c7fe681c7
Fixes #1115
=> Stop sending returned email when deposit is waiting for review

app/models/license.rb, spec/models/license_spec.rb
Because it is deprecated and CC-0 should be used instead. Fixes #1100
=> Remove CC-PDDC from the license lists

app/controllers/dashboards_controller.rb
This was caused by a bad merge in https://github.com/sul-dlss/happy-heron/commit/fe6847a2ae5bd77cd252bc850821dfd313c86215
Fixes #1118
=> Restore manager approvals

.circleci/config.yml
Because if the cache is out of date you get:
Failed to fetch http://deb.debian.org/debian/pool/main/p/postgresql-11/postgresql-client-11_11.9-0+deb10u1_amd64.deb  404  Not Found
=> Update from apt before trying to fetch

app/components/collections/release_component.html.erb, app/components/collections/release_component.rb, spec/components/collections/release_component_spec.rb
Fixes #769 
Depending on the collection manager's choices for Release, the following messages are displayed.
Immediately:
With a specific delayed time period:
When depositor selects a date:
New component tests.
n/a
=> Adds Details for Collection Release

app/javascript/stylesheets/frontpage.scss, app/views/welcome/show.html.erb
=> Update homepage header text

app/models/work_version.rb, spec/models/work_version_spec.rb
This fixes a misplaced parenthesis in the generated SQL.
Fixes #1140
=> Only show items waiting for approvals in the approvals table

config/initializers/devise.rb
Fixes #1145 by allowing for additional domains (i.e. `stanford.edu` as well as `lists.stanford.edu`) as valid email addresses.
N/A
N/A
=> Update Devise.email_regex to allow for more than one subdomain

app/components/collections/form_component.html.erb
=> Convert the depositors field to a text area

Gemfile, Gemfile.lock
=> Remove unnecessary dor-services-client gem

lib/tasks/deposit.rake
What used to be one job is now two separate steps.
=> Update complete_deposit job after switching to rabbitMQ

app/models/work_type.rb, spec/factories/work_versions.rb, spec/jobs/deposit_job_spec.rb
- `WorkType.purl_reservation_type.cocina_type` becomes a valid cocina type (`Cocina::Models::Vocab.object` instead of `'n/a'`)
- fix `reserving_purl` trait for `work_version` FactoryBot fixture to have the `reserving_purl` state (instead of copypasta `purl_reserved` state)
- unskip `deposit_job_spec.rb` test now that the above two changes allow it to pass
This is part of the fix for #1191 (generate valid a valid Cocina model so that initial SDR resource gets created and a PURL is reserved).
The other part of fix for #1191 will be preventing editing/type selection for the work until the PURL is reserved.  That will prevent having to add a bunch of state transitions (as tried in #1202).  The simpler approach of preventing editing in the initial purl reservation states has the upside of …
=> fix Cocina deposit creation for PURL reservation

spec/support/feature_errors.rb
Instead respond with production like responses (e.g. 404 rather than ActiveRecord::RecordNotFound).
This fixes the build because the delete test can delete a record before the delete_button endpoint is called, which leads it to raise a RecordNotFound.  This is handled as expected if it returns a 404 instead.
This code was also used in the hydra_etd project
=> Don't raise errors when running feature specs

app/components/collections/create/form_component.html.erb, app/components/collections/create/settings_component.html.erb, app/components/collections/update/details_form_component.html.erb, app/components/collections/update/settings_form_component.html.erb
This is leftovers from when we switched to local forms and didn't do error handling in Stimulus. Fixes #1232
=> Remove calls to non-existant controller

app/policies/work_version_policy.rb, spec/factories/work_versions.rb, spec/policies/work_version_policy_spec.rb
closes #1191 (should prevent the state transition error i ran into)
closes #1200
* ~~`WorkVersion#updatable?` -- can't update something in the initial stages of PURL reservation, because the `update_metadata!` from `purl_reserved` brings the work version to draft.  If picking type and the first two PURL reservation states (`purl_requested`, `reserving_purl`) could happen in any order, it'd make the possible [states and transitions balloon](https://github.com/sul-dlss/happy-heron/pull/1202#issuecomment-786371113), to little benefit (since in most cases PURL reservation should happen quickly, and should block type selection and metadata update for only a few seconds).  See also https://github.com/sul-dlss/happy-heron/pull/1202 and https://github.com/sul-dlss/happy-heron/issues/1191~~ (as …
=> slightly stricter updatability checks

app/mailers/collections_mailer.rb, app/mailers/reviewers_mailer.rb, app/mailers/works_mailer.rb, app/presenters/user_presenter.rb, spec/mailers/collections_mailer_spec.rb
Fixes #1220 - show a default name for users (this will work in both emails and anywhere else user names are used, which would otherwise result in blank showing)
Added a new test
=> use a default name for users if none is found

app/components/collections/create/buttons_component.html.erb, spec/components/collections/create/buttons_component_spec.rb
Fixes #1253 - temporarily hide save as draft button for brand new collections
Unit test updated and localhost browser
=> hide save as draft button for new collections

app/components/works/buttons_component.html.erb, spec/features/create_new_draft_work_spec.rb
=> Allow creating a draft without being prompted about not saving

app/models/collection_version.rb
closes #1215
Fix error reported by HB.
Not.
NA
=> Pass collection version instead of collection to CollectionsMailer.

README.md
=> Remove outdated deployment documentation from README

app/components/dashboard/in_progress_collection_row_component.html.erb, spec/components/dashboard/in_progress_collection_component_spec.rb, spec/components/dashboard/in_progress_collection_row_component_spec.rb
It is confusing for the user to edit a collection in progress and end up on a page that does not have a Deposit button.  We should instead link to the details part of the edit collection form, which has the Deposit button.
Extracted from #1257
=> when editing collection on dashboard, go to the details tab which has the deposit button

config/locales/en.yml
I'm not sure this will be surfaced in the UI, but I thought it might be useful to make sure we have a one-to-one mapping between defined transitions and labels.
CI
i18n.
=> Add translation for pid_assigned transition

app/components/collections/update/settings_form_component.html.erb, app/services/types_generator.rb, config/mappings/types_to_genres.yml, config/mappings/types_to_resource_types.yml, spec/services/types_generator_spec.rb
Replacing #1218 - updated resource and genre type mappings
Also
- remove genre duplicates which causes duped genres which came from both the top level type and the subtypes
- update tests to reflect new data
Some updated tests
=> Update resource type and genre mappings

app/services/description_generator.rb, spec/services/description_generator_spec.rb
closes #1328
Blank notes cause roundtrip validation errors.
Unit
NA
=> Ignores blank notes (citations and abstracts).

app/components/collections/edit_license_component.html.erb, app/components/works/detail_component.html.erb, app/components/works/license_component.html.erb, app/services/access_generator.rb, app/services/request_generator.rb, app/views/shared/_terms_of_deposit.html.erb, config/settings.yml, spec/services/access_generator_spec.rb, spec/services/request_generator_spec.rb
Fixes #1401  by adding a configuration setting for the use and reproduction statement and adding it to the access metadata. This also removes an unused method.
Unit
N/A
=> Send the appropriate use and reproduction statement to sdr-api

app/views/shared/_terms_of_deposit.html.erb
=> Fix footnote marker to be superscript on terms-of-service modal

app/components/collections/edit_license_component.html.erb, app/components/collections/update/details_form_component.html.erb, app/components/collections/update/settings_form_component.html.erb, app/components/first_draft_collections/create/details_component.html.erb, app/components/first_draft_collections/create/form_component.html.erb, app/components/first_draft_collections/create/settings_component.html.erb, app/components/first_draft_collections/update/form_component.html.erb, app/components/related_link_component.html.erb, app/components/works/contact_email_row_component.html.erb, app/components/works/contributors_component.html.erb, app/components/works/dates_component.html.erb, app/components/works/description_component.html.erb, app/components/works/related_work_component.html.erb, spec/components/works/contributors_component_spec.rb
Fixes #1400 
- Updates text under title to "* REQUIRED FIELDS" for collections
- Adds "*" to required fields
- Removes "(optional)"
Updated tests that checked for "optional"
=> Add required field marker and remove optional text for collections

Capfile, config/deploy.rb, config/deploy/prod.rb
So that we have a way of writing the crontab entry automatically.
=> Create a crontab entry when deploying in production

app/forms/draft_work_form.rb, spec/forms/work_form_spec.rb, spec/requests/create_work_spec.rb
Otherwise, this validation gets triggered when registering a purl in a collection that allows the user to choose whether to embargo.
Fixes #1394
=> Only validate embargo parts when the user has selected 'embargo'

app/controllers/works_controller.rb, app/forms/reservation_form.rb
Keep the form stuff in the form.
=> Refactor reserve a PURL to use a form object

app/components/works/purl_reservation_modal_component.html.erb, spec/components/works/purl_reservation_modal_component_spec.rb
(e.g. don't nest footer inside the body)
Before:
After:
=> Make the reserve a purl style have valid bootstrap markup

app/components/works/contact_email_row_component.html.erb, app/controllers/collection_versions_controller.rb, app/controllers/works_controller.rb, app/forms/contact_emails_populator.rb, spec/forms/work_form_spec.rb, spec/requests/edit_collection_version_spec.rb, spec/requests/edit_work_spec.rb
Previously leaving the contact email blank was enabling validations to pass.
Fixes #1362
=> Don't allow blank contact emails

app/components/works/description_component.html.erb, app/components/works/keywords_component.html.erb, app/components/works/keywords_component.rb, app/components/works/keywords_row_component.html.erb, app/components/works/keywords_row_component.rb, app/forms/draft_work_form.rb, spec/components/works/contact_email_component_spec.rb, spec/components/works/keywords_component_spec.rb, spec/components/works/keywords_row_component_spec.rb, spec/features/create_new_work_spec.rb
Fixes #1377
1. Single entry:
2. When another keyword is added:
3. Error message if blank:
4. Entering multiple values:
5. Showing the values saves as draft:
Updated feature tests
=> Update the keyword entry to be a single text box with "add another" button

app/components/collections/show/settings_header_component.html.erb, app/components/collections/show/settings_header_component.rb, app/components/works/detail_component.html.erb, app/components/works/edit_button_component.rb, app/packs/stylesheets/collection.scss
=> Add "edit or deposit" button to item/collection view pages

app/components/works/keywords_row_component.html.erb, spec/features/create_new_work_spec.rb
Provide a more accurate keyword validation message.
=> Update keyword validation message

app/components/related_link_row_component.html.erb
=> Update link text for work related link

app/components/works/add_files_component.html.erb
Fixes #1316 
Sets drops zone max file size to 10GB to match the text on the screen.
=> Set dropzone max file size to 10G

app/components/works/available_date_component.html.erb, app/components/works/contributor_row_component.html.erb, app/components/works/subtypes_component.html.erb, app/packs/controllers/edit_deposit_controller.js, app/packs/controllers/more_types_controller.js
This keeps the function of each controller clear.
=> Extract more-types controller from edit-deposit controller

app/components/works/version_description_component.html.erb
=> Add error message when the change description is not provided

app/components/works/dates_component.html.erb, app/components/works/dates_component.rb, app/components/works/publication_date_component.rb
=> Add a placeholder for year

app/components/works/edit_button_component.rb, app/models/work_version.rb, spec/components/works/edit_button_component_spec.rb
=> Don't render "Edit or Deposit" button when item is deposited

app/components/collections/show/settings_header_component.rb, app/models/collection_version.rb, spec/components/collections/show/settings_header_component_spec.rb
=> Don't render "Edit or Deposit" button for a deposited collection

app/components/dashboard/all_collections_component.html.erb, app/components/dashboard/all_collections_row_component.html.erb, app/components/dashboard/all_collections_row_component.rb, app/components/related_link_row_component.html.erb, app/packs/stylesheets/dashboard.scss, spec/components/dashboard/all_collections_row_component_spec.rb, spec/requests/dashboards_spec.rb
Fixes #1049 
Note: This is draft pending updated test(s).
=> Add draft label to collection name when needed on dashboard

config/environments/development.rb
Because this breaks dropzone in development
Fixes #1506
=> Disable comments that show what template is rendered

app/controllers/searches_controller.rb, spec/requests/search_spec.rb
The UIT security scanning software tries to fuzz this which triggers a Nil pointer error.  This change instead raises ActionController::ParameterMissing which is handled by ActionDispatch::ExceptionWrapper: https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L21
Fixes #1491
=> Require the search parameter

app/components/works/authors_and_contributors_component.html.erb
The show page doesn't link to the right part of the page.
=> Add missing anchor, which is linked to from the show page

app/components/collections/detail_component.rb, app/components/collections/update/details_form_component.html.erb, app/components/collections/update/details_form_component.rb, app/components/collections/version_description_component.html.erb, app/components/collections/version_description_component.rb, app/controllers/collection_versions_controller.rb, app/forms/draft_collection_form.rb, app/forms/draft_collection_version_form.rb, db/migrate/20210520161846_add_version_description_to_collection_versions.rb, db/structure.sql, spec/components/collections/version_description_component_spec.rb
Fixes #968 
Creating a collection or editing a draft the what's changing element is not displayed:
The What's Changing element is displayed when editing a deposited or version_draft collection:
Unit
=> Add what's changing element to collections detail editing

app/jobs/deposit_status_job.rb, spec/jobs/deposit_status_job_spec.rb
When an embargo is released, DSA versions the object which triggers a deposited message.  This change guards against handling these messages which was causing invalid state transitions.
Fixes #1313
=> Guard against deposited messages from embargo release

app/jobs/assign_pid_job.rb, lib/tasks/rabbitmq.rake
This means we don't have to process every registration to see if it's an h2 object
=> Route the pid assigned by project name

app/components/related_link_row_component.html.erb
=> Validate link format

app/components/collections/edit_license_component.html.erb
Then the front end validation will do the right thing and scroll up to it when it isn't selected.
Fixes #1487
=> Make the license selection required

app/models/work_version.rb
So that we can cleanly delete WorkVersions.
=> Clean up contributors when deleting WorkVersions

app/packs/controllers/dropzone_controller.js
=> Disable submit while uploading

app/components/works/dates_component.html.erb, app/components/works/dates_component.rb, app/components/works/publication_date_component.rb, spec/components/works/dates_component_spec.rb, spec/components/works/publication_date_component_spec.rb
Previously 'work' was hardcoded everwhere.
Fixes #1587
=> Refactor date components to use the forms param_key

app/packs/controllers/dropzone_controller.js
Fixes #1579, only checks for duplicate file names for those FileRowComponts that are visible. Uses `.offsetParent` property on the element, `nil` if the enclosing parent display is set to none (which we set in order to remove this file when the user submits the form). See https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent
Test suite
n/a
=> Ignore fileTargets if parent display is none

app/validators/embargo_date_parts.rb, spec/forms/work_form_spec.rb, spec/validators/embargo_date_parts_spec.rb
Previously the validator was setting an error on :'embargo-date', but the AvailableDateComponent was looking for :embargo_date
=> Use correct key for embargo date

app/components/collections/show/details_header_component.html.erb, app/components/collections/show/settings_header_component.html.erb, app/components/collections/show/settings_header_component.rb
closes #1476
Fix alignment when collection name is long.
Locally
NA
=> Fix deposit button alignment.

app/forms/draft_work_form.rb, spec/components/works/dates_component_spec.rb, spec/components/works/publication_date_component_spec.rb, spec/forms/draft_work_form_spec.rb
So the parameters are always named 'work' regardless of whether this is a draft or not.
This can occur here: https://github.com/sul-dlss/happy-heron/blob/main/app/controllers/works_controller.rb#L83
when the draft fails to save, then it re-renders the form with a DraftWorkForm and all the parameters are prefixed with `draft_work` rather than the expected: `work`
Fixes #1578
=> DraftWorkForm should have the same model name as WorkForm

app/components/collections/version_description_component.html.erb
=> Add invalid feedback for collection version description

app/jobs/deposit_job.rb, spec/jobs/deposit_job_spec.rb
This can happen when the catalog is down (as it is everynight for a restart)
See:
https://app.honeybadger.io/projects/77112/faults/79787375
https://app.honeybadger.io/projects/67994/faults/64602885
Ref #1585
=> Deposits that fail should automatically retry

app/components/works/available_date_component.html.erb, app/components/works/available_date_component.rb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/forms/embargo_date.rb, app/forms/embargo_date_params_filter.rb, app/packs/controllers/available_date_controller.js, spec/components/works/available_date_component_spec.rb, spec/forms/work_form_spec.rb
closes #1527
So that the embargo date is correctly retained, populated, and validated.
Local
NA
=> Embargo date

app/components/works/contributor_row_component.html.erb, app/components/works/contributor_row_component.rb, app/packs/controllers/contributors_controller.js, spec/features/create_new_work_spec.rb
This stopped doing anything useful back when https://github.com/sul-dlss/happy-heron/commit/7f7adb02c2b85866cbeab353978eb82b617a4124#diff-480d3ee3cd54681b7cc0549457979474ae723cd1dcb64352c9467b2680b3171e was changed
=> remove inoperative code

.rubocop.yml, app/components/works/available_date_component.rb, spec/components/works/available_date_component_spec.rb, spec/forms/work_form_spec.rb
Up to date cops gives us less noise when running specs.
rubocop passes without the noise.
=> rubocop: add new cops from 1.16

README.md
A small README update to reflect the `docker compose` command now that `docker-compose` is deprecated.
README
=> Update references to docker compose

app/controllers/dashboards_controller.rb
=> Alpha sort collections on the dashboard

app/components/dashboard/in_progress_collection_row_component.html.erb
=> Add pencil icon to in progress collections

app/components/collections/edit_license_component.html.erb
Fixes #1342 
When the pencil icon for terms and license is clicked, that section is now at the top of the window.
=> Land on the terms area when the terms pencil edit icon is clicked

app/components/first_draft_collections/create/settings_component.html.erb, config/locales/en.yml, spec/features/create_new_collection_spec.rb
Fixes #1343 
Fixes #1344 
1343:
1344:
Unit test updated
=> Fix missing capitalization in help text

app/components/collections/works_component.html.erb, app/components/dashboard/all_collections_component.html.erb, app/components/dashboard/collection_component.html.erb
=> Add striping to collection tables

app/components/works/keywords_row_component.html.erb
=> Remove unwanted spacing before garbage icon

app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb
=> Display the version info

app/components/collections/work_row_component.html.erb, app/components/dashboard/continue_work_modal_component.rb, app/components/dashboard/in_progress_row_component.rb, app/components/purl_check_link_component.rb, app/components/works/detail_component.rb, app/components/works/link_to_show_component.rb, app/presenters/work_title_presenter.rb, app/views/works/_edit_button.html.erb
We have been abusing the Works::DetailComponent just to format a title value.  This extracts that functionality to it's own class.
=> [Refactor] Extract WorkTitlePresenter

app/models/event.rb
Fixes #1619 by ordering the event data in descending chronological order
Works:
Collection:
=> Use a default scope to order events chronologically

app/packs/stylesheets/collection.scss
Note, as in a prior PR, the configuration option in dataTables to disable searching does not seem to be working and we've had to hide via CSS. 
I'm happy to investigate that further, but for now, this removes the search.
=> Hide dataTable searching on the collection works tab

app/packs/stylesheets/frontpage.scss, app/packs/stylesheets/palette.scss, app/packs/stylesheets/suNavbar.scss, app/packs/stylesheets/sulFooter.scss
Because "alabaster" is not a color permitted by the identity guide.
=> Switch to using white text on the header to follow the identity guide

app/components/works/authors_component.html.erb
=> update text for authors section

app/packs/stylesheets/collectionEditor.scss
=> style 'version your collection' like 'version your work'

app/controllers/collection_versions_controller.rb, spec/requests/edit_collection_version_spec.rb
closes #1516
Redirect to correct page.
Local, unit
NA
=> Redirect to collection details page after collection details save.

.rubocop.yml
we must appease our rubocop masters or bad things will happen.
=> rubocop.yml gets newly created cops

app/components/works/subtypes_component.html.erb, spec/components/works/subtypes_component_spec.rb, spec/features/edit_draft_work_spec.rb
Fixes #1643
running locally and unit test changes
=> item deposit has corrected header for work subtypes

app/controllers/works_controller.rb, spec/requests/purl_reservation_spec.rb
We weren't getting work type and work subtype validations for a registered purl.
Fixes #1618
locally and a request spec was written
=> setting work type on a purl reservation validates appropriately

app/components/works/detail_component.html.erb
This enables the show page to draw linebreaks where the user entered them.
Fixes #1666
=> Use simple_format for abstract

app/controllers/terms_controller.rb, app/views/print/terms_of_deposit.html.erb, app/views/shared/_terms_of_deposit.html.erb, app/views/terms/_show.html.erb, app/views/terms/show.html.erb, config/routes.rb
This avoids having pages of legal text hidden on every page and makes it easier to debug broken request tests
=> Load the terms lazily

app/components/works/description_component.html.erb, app/components/works/related_work_row_component.html.erb, app/components/works/title_component.html.erb, app/packs/controllers/no_newlines_controller.js, spec/components/works/title_component_spec.rb
closes #1032
Better data entry.
Local
NA
Note that default citation was already a text area.
=> Makes title and related works into text areas.

app/controllers/works_controller.rb, app/services/work_observer.rb, spec/features/create_new_work_spec.rb
Previously we were logging changes on the update and then on the deposit events.
=> Don't log changes two times

app/forms/draft_work_form.rb
This prevents a failure in one of the nested models from creating bad data in the database.
Fixes #1660
Fixes #1683
Fixes #1671
=> Include all the save operations within the transaction

app/services/description_generator.rb, spec/services/description_generator_spec.rb
closes #1697
Depositing was failing due to roundtrip validation errors because empty URIs are removed in dor-services-app mapping.
Unit
NA
=> Remove blank URIs from cocina.

app/components/works/file_row_component.html.erb, app/forms/draft_work_form.rb, app/services/work_version_event_description_builder.rb, spec/forms/work_form_spec.rb, spec/services/work_version_event_description_builder_spec.rb
Otherwise it considers these to have changed because _destroy being set to an empty string is considered a change from it being false
Fixes #1695
=> Specify types on nested models to prevent them being marked as changed

app/components/works/buttons_component.html.erb, app/components/works/buttons_component.rb, app/components/works/dates_component.html.erb, app/components/works/dates_component.rb, app/components/works/publication_date_component.html.erb, app/forms/draft_work_form.rb, app/forms/edtf_params_filter.rb, app/packs/controllers/date_range_controller.js, app/packs/controllers/date_validation_controller.js, app/validators/created_date_parts.rb, app/validators/created_in_past_validator.rb, spec/components/works/dates_component_spec.rb, spec/features/create_new_work_spec.rb, spec/requests/create_work_spec.rb, spec/validators/created_in_past_validator_spec.rb
closes #914
* Validate date intervals.
* Do not discard interval dates that the user has entered.
Unit, local
NA
=> If providing a create date interval, requires start and finish year.

config/deploy/prod.rb
Now that we are in production, we want to alert users that they have unfinished deposits they need to finish.
=> Run the cron job on prod

app/components/first_draft_collections/create/settings_component.html.erb, app/packs/controllers/review_workflow_controller.js, spec/features/create_new_collection_spec.rb
closes #1702.
Confusing for user to be able to enter reviewers when review workflow turned off.
Local, unit
NA
=> Disable reviewers when review workflow turned off.

app/models/collection_change_set.rb, app/services/collection_observer.rb, spec/services/collection_observer_spec.rb, spec/spec_helper.rb
closes #973
Users were being sent gratuitous emails.
Unit
NA
=> Do not send redundant/unnecessary participant change notifications.

app/components/works/file_row_component.html.erb, app/forms/draft_work_form.rb
This was removed as part of https://github.com/sul-dlss/happy-heron/commit/770a7ba4a0ef6ac2bfc8aa1b6511ab41319942eb#diff-81e6b6427ea21d10a73dc41dd6b55cbdccd6002a200ddf5cce9b5e26daee19f6
However, this field is necessary when we redraw the form after a server side validation fails (such as the embargo date is in the past).
Fixes #1352
Fixes #1700
=> Restore the hidden file field

config/application.rb
Typically when you have an error in the console, it's a typo or something you don't need everyone to know about.  This also cuts down on the SIGHUP errors if you leave your console open and it times out.
Fixes #1520
=> Disable honeybadger when working in the console

app/controllers/works_controller.rb, spec/requests/edit_work_spec.rb
closes #1694
All properties that were collections were erroneously being reported as changed even if they weren't.
Unit
NA
=> Records correct changes when creating a new version.

app/components/works/keywords_row_component.html.erb, app/packs/controllers/autocomplete_edit_controller.js, app/packs/controllers/nested_form_controller.js
closes #1737
Additional support for using FAST for keywords.
QA
NA
=> Do not allow editing of FAST keywords. Allow deleting first keyword.

app/packs/entrypoints/application.js
closes #1357
Turbo was caching with an open modal causing the modal to flash on page changes.
Local
NA
=> Close modals before turbo caches.

app/controllers/work_versions_controller.rb, spec/requests/delete_work_version_spec.rb
closes #1598
Allow deleting first version.
Unit, QA
NA
=> Create a new head version for work when discarding first version.

app/components/works/publication_date_component.rb, app/packs/controllers/auto_citation_controller.js, spec/features/auto_citation_spec.rb, spec/features/create_new_work_spec.rb
closes #1801
Per ticket.
Unit
NA
=> Stop using publication year to construct citation.

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, config/settings.yml, spec/components/works/detail_component_spec.rb
closes #1730
So that the user knows what the future DOI will be.
Unit
NA
=> Provides future DOI on item view page.

app/components/works/available_date_component.html.erb, app/components/works/dates_component.html.erb
Fixes #1827 - move input controls that are related to the same field into a single fieldset (just wrap the existing div) and ensure they have a legend.
=> move grouped dates on work edit page into fieldsets

app/packs/controllers/nested_form_controller.js
This means it only needs to find one and doesn't need to iterate over the whole set
=> Refactor detection of empty nested form

spec/services/orcid_service_spec.rb
The WebMock.disable_net_connect! is already called in rails_helper.rb
=> Remove duplicate webmock call

.circleci/config.yml, spec/services/orcid_service_spec.rb
https://circleci.com/developer/images/image/cimg/ruby#image-name states that cimg/ruby was designed to supercede the legacy circleci/ruby:* images
=> Update to using the modern circle docker images

app/components/works/access_component.html.erb, app/components/works/embargo_component.html.erb, app/components/works/embargo_component.rb, app/packs/stylesheets/workEditor.scss, spec/components/works/access_component_spec.rb, spec/components/works/embargo_component_spec.rb, spec/components/works/form_component_spec.rb, spec/features/create_new_work_spec.rb
closes #1724
UI consistency
Unit, local
NA
=> Update layout for release and visibility section of item deposit form.

spec/features/delete_draft_collection_spec.rb
closes #1848
So we can stop hitting the Circle re-run button.
=> Adds delay to flappy spec.

spec/services/cocina_generator/description/types_generator_spec.rb
So H2 produces the cocina data that dor-services-app expects.
CircleCI
n/a
Implementation ticket #1867
=> Update type mapping to match current dor-services-app form spec

app/components/breadcrumb_nav_component.html.erb, app/components/breadcrumb_nav_component.rb, app/views/collection_versions/edit.html.erb, app/views/collections/edit.html.erb, app/views/dashboards/show.html.erb, app/views/first_draft_collections/edit.html.erb, app/views/layouts/application.html.erb, app/views/works/edit.html.erb, app/views/works/index.html.erb, app/views/works/new.html.erb, spec/components/breadcrumb_nav_component_spec.rb, spec/features/welcome_spec.rb, spec/requests/dashboards_spec.rb, spec/requests/edit_collection_spec.rb, spec/requests/edit_work_spec.rb
closes #1799
Accesability.
Unit
NA
=> Provides more descriptive page titles.

spec/services/cocina_generator/description/contributors_generator_spec.rb
To make sure H2 is delivering the cocina that dor-services-app expects. Changes: replaces contributor role with citation note for uncited contributors; adds type to events; marks two unnecessary tests for deletion.
CircleCI
n/a
Implementation ticket #1866
=> Update contributor mappings to match dor-services-app spec

app/services/cocina_generator/description/generator.rb, spec/services/cocina_generator/description/generator_spec.rb
we were getting an HB roundtripping error
unit test
=> cocina generator: date range with end dates both approx tweak

db/migrate/20210802203252_add_orcid_to_abstract_contributors.rb, db/structure.sql
So we can persist the orcid of a contributor.
=> Add orcid database field to contributors

app/models/abstract_contributor.rb, app/models/orcid.rb, spec/models/abstract_contributor_spec.rb, spec/models/orcid_spec.rb
So that other code can be confident about the format of the ORCID that is stored.
Unit
NA
=> Adds validation for orcid ids.

app/services/request_generator.rb, spec/services/request_generator_spec.rb
Fixes bug - you can't assign a doi without a druid.
unit tests;   will do more manual testing as I work on testing update_doi_metadata action in DSA, triggered from H2 in stage.
=> request_generator: druid needed to assign doi

app/components/works/detail_component.html.erb, app/components/works/show/orcid_component.html.erb, app/components/works/show/orcid_component.rb, spec/components/works/detail_component_spec.rb
closes #1735
Per ticket
Unit, local
NA
=> Adds display of ORCID to work detail page.

app/components/citation_component.rb
This prevents a deprecation warning like:
app/components/citation_component.rb:17: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
=> Double splat the kwargs to tag.button

app/services/cocina_generator/description/related_links_generator.rb, sorbet/custom/cocina-models.rbi, spec/services/cocina_generator/description/related_links_generator_spec.rb
This prevents DSA from raising a round trip error when PURL links are provided.
=> Related links that are purls have a special expression in cocina

app/services/cocina_generator/description/related_links_generator.rb, spec/services/cocina_generator/description/related_links_generator_spec.rb
Because otherwise DSA will fail these from round tripping
=> Normalize related links that are purls using https

Gemfile, Gemfile.lock, package.json, yarn.lock
We were pinned to a github version until this release was made, so this clears some tech debt.
=> Upgrade turbo-rails to a released version

app/policies/work_policy.rb, spec/features/purl_reservation_spec.rb
Fixes #1837 - allow reserved PURLs to be deleted.
~~Question: this just destroys the `Work` and `WorkVersion` in the database, it would for any work that is in a first draft state.  I think it should be fine even after we have a held a PID?~~
Localhost browser, added delete to existing purl reservation test.
=> allow reserved purls to be deleted

app/components/works/detail_component.html.erb
Fixes #1336 : align (most) fields on item view page with a fixed width column for the labels.
I didn't align the Files, Author and Contributors and History sections because they are currently displayed differently.  The aligned sections have a label and a value in each row, but the the other three sections noted above are tables, with each row containing only values, with the labels at the top of the table columns.  If we also want to align those, we may run into other issues with the display (for example, a person's name will be long and won't be suitable for the smaller column width that the labels in the other sections are constrained to):
**Current view on main branch:**
**View in this PR:**
=> align items show page table columns

app/components/works/buttons_component.rb, app/models/work_version.rb, app/policies/work_policy.rb, spec/features/delete_draft_work_spec.rb
Fixes #1946 - allow rejected (returned) or pending approval first drafts to be deleted
Updated tests
=> Allow rejected or pending approval first drafts to be deleted

app/components/works/doi_component.html.erb, app/packs/stylesheets/palette.scss, app/packs/stylesheets/switch.scss
Fixes #1938
This updates slider styles so we can see the slider against a gray background
Before:
After:
=> Use slider widget for registering a DOI 

app/components/collections/settings_component.html.erb, app/components/works/doi_component.html.erb, config/settings.yml
=> Open the 'What is a DOI' link in a new tab

app/packs/controllers/datatable_works_controller.js
closes #1952
User experience
Local
NA
=> Scroll into view on collection results list paging.

app/components/collections/update/details_form_component.html.erb, app/components/collections/update/settings_form_component.html.erb, spec/features/create_new_collection_spec.rb
Fixes #1949 - cancel target location should be collection view pages when editing
Added new expectations to edit collection spec
=> go back to collection details/settings when canceling editing

app/components/works/buttons_component.html.erb, app/components/works/buttons_component.rb, spec/components/works/buttons_component_spec.rb, spec/features/create_new_work_spec.rb, spec/features/edit_draft_work_spec.rb
Fixes #1950 - cancel link on work edit form should go to work show page (if existing work) or collection works listing page (if new work)
Updated existing test, added new test
=> cancel work editing goes to work show page

app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb, spec/support/view_component.rb
...But will get a DOI when it is deposited.
Fixes #1959
=> Add a message for an already deposited item that doesn't have a DOI

app/policies/work_policy.rb, spec/policies/work_policy_spec.rb
To address #1951 - add collection managers and reviewers to the work delete policy
Added new tests
=> allow reviewers and collection managers to delete works

Gemfile, Gemfile.lock, app/services/cocina_generator/description/related_links_generator.rb, config/settings.yml, spec/components/dashboard/collection_component_spec.rb, spec/models/collection_spec.rb, spec/models/work_spec.rb, spec/services/cocina_generator/collection_generator_spec.rb, spec/services/cocina_generator/description/related_links_generator_spec.rb, spec/services/cocina_generator/dro_generator_spec.rb
Make PURL use https by default.
=> Upgrade to cocina models 0.62.0

app/components/related_link_row_component.html.erb, app/components/related_link_row_component.rb, app/components/works/contact_email_row_component.html.erb, app/components/works/contact_email_row_component.rb, app/components/works/related_work_row_component.html.erb, app/components/works/related_work_row_component.rb, spec/components/related_link_component_spec.rb, spec/components/works/related_work_component_spec.rb
closes #1499
UX
Local, unit
NA
=> Enable user to delete the first entry of multi-entry fields.

Gemfile, Gemfile.lock, spec/features/purl_reservation_spec.rb, spec/support/capybara.rb
Cuprite is now a Rails default and it doesn't throw all the deprecation warnings that apparition does.
Fixes #1966
=> switch from apparition to cuprite

app/packs/controllers/collection_participant_form_controller.js
closes #1925
User experience.
Local.
NA
=> Hides collection participant results list when query deleted.

app/packs/controllers/contributors_controller.js
The Orcid validation was not being applied when validating a form for deposit.
Local
=> Add custom validity for Orcid validation errors.

app/components/works/show/files_component.html.erb
closes #1888
Allow the file name column to stretch for long file names.
Local
NA
=> Remove col specification from file column for file table.

app/policies/work_version_policy.rb, spec/policies/work_version_policy_spec.rb
To address https://github.com/sul-dlss/happy-heron/issues/1951#issuecomment-901451204 -- it looks like perhaps our updating of the work policy in #1964 now allows the delete icon to be shown for everyone who can delete, but when the deletion is actually attempted, the work_version policy prevented the deletion (for a collection manager).  The theory is that it works for admins and depositors since they are currently allowed to delete work_versions, but not for collection managers or reviewers because they are not currently allowed to delete work_versions.  This code matches up the work and work_version policies so that they are the same group of people.
Added tests
=> allow reviewers and collection managers to also delete work_versions

app/services/cocina_generator/structural/file_generator.rb, spec/services/cocina_generator/structural/file_generator_spec.rb
=> Restrict files to stanford-only when the object access stanford

app/components/works/keywords_row_component.html.erb, app/controllers/autocomplete_controller.rb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/packs/controllers/autocomplete_edit_controller.js, app/services/cocina_generator/description/generator.rb, db/migrate/20210816133101_add_cocina_type_to_keywords.rb, db/structure.sql, spec/factories/keywords.rb, spec/requests/autocomplete_spec.rb, spec/services/cocina_generator/description/generator_spec.rb
closes #1874
Accurate subject metadata.
Unit
NA
=> Determines type of subject terms from FAST and include in cocina.

app/policies/common_work_policy.rb, app/policies/work_policy.rb, app/policies/work_version_policy.rb
Follow on from #1980 to refactor work and work_version policy to avoid code duplication.  Create new base class for works and work_versions, move a couple methods there used by all work related policies.
Existing tests
=> refactor policies to remove code duplication for delete works

app/components/dashboard/all_collections_component.html.erb
closes #1999
Local
Before:
After:
=> Fixes data sorting for All Collections table.

app/packs/stylesheets/bootstrapVariables.scss
closes #1989
Accessability
Local
=> Switch form-text to black.

app/services/cocina_generator/description/types_generator.rb, spec/services/cocina_generator/description/generator_spec.rb, spec/services/cocina_generator/description/types_generator_spec.rb, spec/services/cocina_generator/dro_generator_spec.rb
This is the order that DSA constructs the cocina from the MODS, so failing to order this way creates a round tripping error
=> Make the datacite specific form last

app/services/cocina_generator/description/generator.rb, spec/services/cocina_generator/description/generator_spec.rb
The form saves an empty string into the database, this must be serialized to cocina as 'topic'. This bug was introduced in https://github.com/sul-dlss/happy-heron/pull/1965
=> Prevent blank keyword types from being serialized

app/jobs/deposit_job.rb, app/jobs/reserve_job.rb, app/models/work_version.rb, app/services/work_observer.rb, spec/jobs/deposit_job_spec.rb, spec/jobs/reserve_job_spec.rb
This reduces the number of conditionals we need to support, making it easier to debug problems.
=> Separate deposit job from reserve PURL job

app/forms/reservation_form.rb, app/forms/work_form.rb, app/jobs/deposit_job.rb, app/models/work.rb, app/services/cocina_generator/dro_generator.rb, spec/features/purl_reservation_spec.rb, spec/forms/work_form_spec.rb, spec/models/work_spec.rb, spec/requests/edit_work_spec.rb, spec/services/cocina_generator/dro_generator_spec.rb
Previously we were not setting a DOI if it was only requested in a second version
Fixes #2005
=> Assign a DOI when creating a new version

app/forms/draft_work_form.rb, spec/requests/edit_work_spec.rb
=> Prevent the 'false' string from evaluating truthy when creating a DOI

app/components/works/contributor_row_component.html.erb
Fixes #2041 
Currently the order of authors is not retained when changed during an edit. This triggers the display update and persistence of authors when order is changed.
=> Update auto generated citation when changing order of authors

app/components/works/purl_reservation_modal_component.html.erb
Fixes #2040 
The extra modal was removing the ability for the normal data-close action to be linked to the appropriate div.
=> Remove extra modal class tag causing modal not to close properly

app/views/collections_mailer/invitation_to_deposit_email.html.erb
Fixes #2047 
@amyehodge tested in prod and signed off.
=> Fix order of link_to terms of service in email template

app/services/cocina_generator/access_generator.rb, spec/services/cocina_generator/access_generator_spec.rb
Fixes #2069 - embargo release access rights should match what the user set to ensure when the object is released, it has the correct access
Added new unit test
=> embargo release criteria should match what the user set

Gemfile, Gemfile.lock
Revert `turbo-rails` to released version.
Gemfile
=> Update turbo-rails to released version

config/application.rb
doing so raises a deprecation warning
=> There is no need to require view_components explicity

config/application.rb
To reduce timeouts occurring during large file uploads (> 5-10 minutes). 🤷🏻‍♂️ 
Deployed it and uploaded a large file successfully
n/a
=> Follow sdr-api's lead by upping the ActiveStorage service URI timeout

app/services/cocina_generator/description/generator.rb, spec/factories/work_versions.rb, spec/services/cocina_generator/description/generator_spec.rb
Fixes #2139 - approximate dates should be parsed in the same way as non-approximate dates when added to cocina, they just get a qualifier added to the cocina metadata
Added new fixtures and tests (confirmed they failed before my code change and passed after it)
=> parse approximate dates in the same way as non-approximate dates

app/services/cocina_generator/description/collection_description_generator.rb, app/services/cocina_generator/description/generator.rb, app/services/cocina_generator/description/related_links_generator.rb, spec/services/cocina_generator/collection_generator_spec.rb, spec/services/cocina_generator/description/related_links_generator_spec.rb, spec/services/cocina_generator/dro_generator_spec.rb
Including this in cocina is no longer required.
Unit
=> Removes SDR as digital repository in cocina.

app/assets/stylesheets/suNavbar.scss
Only larger units are permitted to do this.
=> Stop using uppercase for Digital Repository

Gemfile.lock
Silence redis.pipeline deprecation warnings in cron emails
=> Bump sidekiq to 6.4.1

app/validators/embargo_date_validator.rb, spec/validators/embargo_date_validator_spec.rb
Fixes #2168 - use Pacific Time Zone when computing today's date, so you can set an embargo date of tomorrow even if it's late in the day pacific (after 4pm, UTC will say it's tomorrow)
I think this should work fine with our current release process, because when it runs, it will see the date has passed and release it that night.
Updated tests
=> use today's date in pacific time zone for embargoes

app/validators/embargo_date_validator.rb, config/application.rb, spec/validators/embargo_date_validator_spec.rb
This reverts #2179 (use Pacific time for embargo dates), and instead just sets the application's default time zone to Pacific.  This will have the same effect as the reverted change for the embargo dates, and will also make the date displays for users show in the Pacific time zone.  This will prevent weird "from the future" things like below happening, where I edited an item on March 4 after 4pm, but it showed as last updated on March 5 (since anytime after 4pm Pacific is now the next day in UTC).  Since we display dates (and not timestamps) to users, I think this change should do the expected thing for anyone in North America.
Tests and localhost browser.
=> set default time zone for the app to Pacific; revert embargo changes

app/components/collections/update/settings_form_component.html.erb, app/components/works/form_component.html.erb, app/forms/draft_work_form.rb, app/forms/work_form.rb, spec/forms/draft_work_form_spec.rb
Fixes #2171 - validate subtypes on draft work form because if the user tries to save a draft work with an invalid subtype (e.g. they had selected "music" but then unselected any subtypes), the work will be in an inconsistent invalid state that cannot be saved to the database.  This is a pretty rare condition, as we already validate subtypes before you get to this form (in the modal when you create a new work), but it is possible to get past that form and then deselect subtypes and make the work version invalid.  This should prevent that from happening.
Also, improve error display for validation errors on draft work page so you don't miss them.  
**Before:**
**After:**
Updated tests
=> validate subtypes on draft form; improve error display

app/validators/embargo_date_validator.rb, config/application.rb, spec/validators/embargo_date_validator_spec.rb
Reverts sul-dlss/happy-heron#2181
Potentially may cause unwanted side effects, see https://github.com/sul-dlss/happy-heron/pull/2181#issuecomment-1059692039
Follow on PR: #2184
=> Revert "set default time zone for the app to Pacific; revert embargo changes"

app/components/collections/work_row_component.html.erb, app/components/dashboard/all_collections_row_component.html.erb, app/components/dashboard/approvals_component.html.erb, app/components/dashboard/in_progress_row_component.html.erb, app/components/local_time_component.rb, app/views/dashboards/_collection_summary_row.html.erb
Modify the component for display of local times to also display local dates (skip time display option) and use it instead of showing UTC based dates. Note that the date format is not going to be localized with `i18n` anymore but our display format is like this `Mar 4 2022`, which is not ambiguous.  In place of #2181 
~~Holding for reverting of that PR: #2183~~
Existing tests
=> show dates in local time zone

Gemfile.lock
To stay up-to-date with sdr-client releases
CI + was successfully integration tested in stage
=> Bump sdr-client to 0.74.0

Gemfile, Gemfile.lock
No need to pin the dependency at patch-level now that the bug is fixed.
CI
=> Unpin ViewComponent now that the bug introduced in 2.51.0 has been fixed

Gemfile, Gemfile.lock, README.md, app/components/collections/works_component.html.erb, app/components/dashboard/all_collections_component.html.erb
The works need to be sorted by date in descending order by default. There was a very small problem with the date format being used with simple-datatables. I noticed that the Collections list was broken in a similar way, and adjusted it there too.
Also bundled in this change is version upgrade to puma because of ﻿﻿https://github.com/puma/puma/security/advisories/GHSA-h99w-9q5r-gjq9
Tested on https://sul-h2-qa.stanford.edu/ @amyehodge tested in Stage and gave her approval.
=> Sort works by date in descending order by default.

.rubocop.yml, app/controllers/application_controller.rb, app/jobs/deposit_job.rb, config/initializers/devise_remote_user.rb
Fixes #2217 - when a DepositJob fails, we can add some HB context (like druid, depositor, work id) to help debug.
Also -- add new rubocop cops and autofix errors.
It was not, but this is a pretty minor change.
=> add some HB context for when deposit jobs fail

app/components/works/agreement_component.html.erb, app/components/works/agreement_component.rb, spec/features/edit_draft_work_spec.rb
Based on work done in #2241 and #2242, this fixes the underlying cause of the bug identified in #2235.
Also 
Fixes #2243 (add a new test for this edge case)
The issue is that the `agree_to_terms` property on the work form was overloaded and could refer to the value of the existing HTML form checkbox as well as the custom derived property we were hoping to use (which did some lookup on the user in the database).  So in cases where the form was re-rendered with an error message and the value of the HTML checkbox was unchecked, the `agree_to_terms` property was returning a "0" instead of `false`, triggering our exception.  The fix is to just bypass the form property and delegate this check straight to the user model, which is what we were originally trying to do anyway.  This lets us avoid …
=> check the depositor agreement directly instead of going through the form

app/views/collection_versions/edit.html.erb
Fixes #2255 - breadcrumb nav for collection details is wrong (should go to collection_version controller and not collection controller)
Note: this bug may not be obvious in localhost, since if the collection and collection_version have the same ID, it will look like it is working just fine.
=> fix collection version breadcrumb navigation

app/controllers/collection_versions_controller.rb, app/forms/draft_collection_version_form.rb, spec/factories/collection_versions.rb, spec/requests/edit_collection_version_spec.rb
Fixes #2256 - start from blank description for new collection versions
also, rename some variables to be more clear
Localhost and added/updated tests
=> start with blank version description for new versions

app/models/work_version.rb, spec/requests/create_work_spec.rb
Potential suggestion to deal with https://app.honeybadger.io/projects/77112/faults/85827019, user pasted in text from a PDF into the abstract field, which breaks in postgres upon submission.  Seems like there should be a more uniform way of doing this.
Localhost
=> sanitize abstract

app/components/works/detail_component.rb
=> Use the original work.created_at instead of the work_version.created_at

app/models/work.rb, spec/components/works/embargo_component_spec.rb
Fixes #2366. Shows embargo as already released if the embargo date is today. 
Unit
=> Embargo is considered released on today's date

app/models/work_version.rb, spec/models/work_version_spec.rb
More investigation into #2240
Results:
- license is allowed to be nil on `work_version` in the rails validations (https://github.com/sul-dlss/happy-heron/blob/main/app/models/work_version.rb#L26), but we have a database constraint that prevents the model from being saved if nil (https://github.com/sul-dlss/happy-heron/blob/main/db/structure.sql#L578)
- while the last instance of the HB exception in #2240 does not appear to be because of a nil license, I was able to reproduce the exception on the rails console by trying to save a contributor associated with a draft work version that had a nil license
- it's unclear to me if a user is ever able to actually select a nil license, so I'm wondering why we allow this to be valid -- suggest we make the rails validation match the database …
=> Require license at model level to match database constraint

.rubocop.yml, app/forms/contributor_form.rb, app/forms/draft_work_form.rb, app/forms/work_form.rb, app/models/abstract_contributor.rb, spec/requests/create_work_spec.rb
Because in a draft you should be allowed to save an incomplete contributor
Fixes #2385 
=> Validate the contributors on the form not on the model

Gemfile, Gemfile.lock, config/application.rb
We don't need the transpiling capabilities of sprockets because we're using node based tools for that now. Propshaft is a much lighter dependency.
deployed to qa
=> Switch from sprockets to propshaft

app/components/works/dates_component.html.erb, app/components/works/dates_component.rb, app/components/works/publication_date_component.rb, app/javascript/controllers/year_field_controller.js
When the up button is first pressed, set the value to the max value of the field rather than the minimum (default).
Fixes #2357
Tested locally.
=> Default years to the max value

spec/features/mediated_deposit_versioning_spec.rb
=> Adds sign out to flaky features/mediated_deposit_versioning_spec.

app/models/work_version.rb, spec/models/work_version_spec.rb
Upon testing it was revealed that the publish date was not persisted
=> Persist the publiblished date

app/components/breadcrumb_nav_component.rb, app/views/admins/show.html.erb, db/structure.sql
Fixes #2327 - setup component to easily add breadcrumbs to admin functions
For future admin views, just need to add something like this (same as the rest of the app).  The new `admin: true` param will add the `Admin Dashboard` link to the breadcrumbs.
```
<% content_for :breadcrumbs do %>
<%= render BreadcrumbNavComponent.new(admin: true,
breadcrumbs: [ { title: 'Some admin function', link: '/link_desired' } ]) %>
<% end %>
```
Localhost
=> add structure for getting admin dashboard breadcrumb nav

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, spec/requests/show_work_spec.rb
closes #2314
Part of adding support for an owner being a different role than depositor.
Unit
=> Displays owner on item detail page.

Gemfile, Gemfile.lock, app/jobs/deposit_job.rb, spec/jobs/deposit_job_spec.rb
closes #2090
More helpful than SDR API default version description.
Unit
=> Provides version description when updating deposit.

Gemfile.lock, README.md
Since `rake db:prepare` does not seed the test database, adding instruction to do so.
Locally
=> Adding instruction for seeding test db

app/views/admin/users/index.html.erb
Missing the breadcrumb nav on one of the new admin pages.  Added (see below)
Localhost
=> add breadcrumb nav to admin search for user

app/components/collections/settings_component.html.erb, app/components/collections/update/depositors_component.html.erb, app/components/collections/update/managers_component.html.erb, app/components/collections/update/reviewers_component.html.erb, app/controllers/accounts_controller.rb, app/javascript/controllers/collection_participant_form_controller.js, spec/requests/accounts_spec.rb
Fixes #2278 and fixes #2279
Changes:
- Updated instruction text above entry form
- Updated message shown when no results are found
- Clear sunet entry text box when focus is lost (unless there is a found search result)
- Hide search result modal when focus is lost (unless there is a found search result)
- Prevent return from being pressed in text box (stops form from being prematurely saved if the user has not clicked the "Add" button)
- Stop user from entering text that does not look like a sunet (must be between 3-8 characters, no special characters, doesn't start with a number)
- Double check that values are not saved unless you click the "Add" button first
New error message when results not found:
Localhost
=> changes around sunet validation and entry on collection edit form

app/models/work.rb, app/services/cocina_generator/description/date_generator.rb, app/services/cocina_generator/description/events_generator.rb, app/services/cocina_generator/description/generator.rb, spec/factories/work_versions.rb, spec/services/cocina_generator/description/events_generator_spec.rb, spec/services/cocina_generator/description/generator_spec.rb, spec/services/cocina_generator/dro_generator_spec.rb
closes #2368
So that item has complete descriptive metadata.
Unit
=> Adds deposit date into cocina description.

app/mailers/first_draft_collections_mailer.rb, app/models/collection_version.rb, app/views/first_draft_collections_mailer/first_draft_created.html.erb, config/settings.yml, spec/mailers/first_draft_collections_mailer_spec.rb, spec/models/collection_version_spec.rb
~~PROBLEM:  email is always set to `h2-administrators@lists.stanford.edu` for all environments.  Does this need to be a shared_configs setting?  And if so ... what is an email we can use that will not be spamful for anyone, including ops?~~
I added a setting, defaulting to false, to turn on these emails.  PR https://github.com/sul-dlss/shared_configs/pull/1834 turns it on in prod (and is harmless otherwise).
Fixes #2326
locally.
From rails log:
```
17:16:59 web.1  | [ActiveJob] [ActionMailer::MailDeliveryJob] [5b9bde01-f055-45e6-a842-5c5a2f9d7a56] FirstDraftCollectionsMailer#first_draft_created: processed outbound mail in 256.2ms
17:16:59 web.1  | [ActiveJob] [ActionMailer::MailDeliveryJob] [5b9bde01-f055-45e6-a842-5c5a2f9d7a56] Delivered mail …
```
=> email admin list when a new collection is started

app/views/works/edit.html.erb
Previously it was rendering unnecessary attributes for the link, (e.g. /works/18056\?work\=18056\&work_version\=1821)
Tested locally.
=> Simplify breadcrumb link rendering

app/components/works/add_files_component.html.erb, app/components/works/file_row_component.html.erb, app/javascript/controllers/dropzone_controller.js, spec/features/create_new_work_spec.rb
Fixes #2336. If a file marked as a duplicate exists, the work cannot be saved or deposited.
Unit and Amy reviewed on stage.
=> Make duplicate file prevent saving or depositing

app/components/dashboard/collection_component.html.erb, app/views/dashboards/_collection_summary_row.html.erb
On the dashboard tables showing collections, we used to show depositor, but now we want to display owner instead.
Fixes #2313
locally
=> Display owner of items on the dashboard

app/models/work_type.rb
Add new sub-types and more types as described in the body of #2299 
Note: this line ensures we don't display a subtype under the "more" menu if it already appears in the "main" subtype section and thus does de-duping automatically: https://github.com/sul-dlss/happy-heron/blob/main/app/components/works/subtypes_component.rb#L36-L38 
=> add new subtypes

app/models/abstract_contributor.rb, spec/components/works/contributor_role_component_spec.rb
Fixes #2292 - add new "Advisor" role to drop-down menu for contributors
Despite this coming first in the list now, "Author" is still the default value.
Localhost
=> add advisor role to person list

app/components/works/dates_component.html.erb, app/components/works/publication_date_component.html.erb, app/javascript/controllers/date_range_controller.js, app/javascript/controllers/date_validation_controller.js, app/javascript/modules/validate-forms.js, spec/features/create_new_work_spec.rb
closes #2293, #2294
Validation error was detected, but not correctly displayed to user.
Local, Amy.
I did not write a error message in the past because it would have been problematic either in December (when months wrap) or the last day of the month (when days wrap).
=> Display error messages for dates.

app/components/works/keywords_row_component.html.erb, app/javascript/controllers/keywords_controller.js
Fixes #1502 - adds client side duplicate keyword validation
Notes:
- for simplicity of implementation, I reused the existing "invalid selection" that typically shows for blank keywords and expanded the error message from "Keyword must be filled in" to "Keyword must be filled in and be unique" so there is a single client side error message that will show in either case
- again for simplicity, the error shows next to the last text box that lost focus when a duplicate was detected, so it may be possible to get into some situations where the error shows on the wrong text box, though i think this simple method should work fine in most cases
Example:
Localhost
=> show client side validation for duplicate keyword entry

app/components/popover_component.html.erb, app/components/popover_component.rb, app/views/works/_edit_button.html.erb, config/locales/en.yml, spec/requests/work_edit_button_spec.rb
Fixes #2319
Fixes #2321
ci & locally
=> Display a lock instead of a pencil when a work is locked

app/views/collections/_edit_link.html.erb
Previously we were relying on a redirect to get to the correct path, however this looses the anchor, so we wouldn't end up at the right spot on the page.
Fixes #2289
Tested locally.
=> Update link to point at the right place

spec/services/collection_reminder_generator_spec.rb
I believe this is easier to understand, because the contexts encapsulate the data that is important to them.
=> Use contexts to organize a spec file

spec/requests/create_collection_spec.rb
Noticed this spec was occasionally flaky based on the ordering of the array.  Since that doesn't seem to matter for functionality, can just sort in the spec and then compare with sorted version instead.
CI
=> make spec less flaky

app/mailers/first_draft_collections_mailer.rb, app/mailers/works_mailer.rb, app/services/work_observer.rb, app/views/works_mailer/globus_deposited_email.html.erb, config/settings.yml, spec/mailers/first_draft_collections_mailer_spec.rb, spec/mailers/works_mailer_spec.rb, spec/models/work_version_spec.rb
closes #2351
So that admins know when to handle globus deposits.
Unit, Amy
=> Send admins email when globus deposited.

app/components/works/subtypes_component.rb, app/javascript/controllers/work_type_controller.js, spec/components/works/subtypes_component_spec.rb, spec/features/create_new_work_spec.rb
=> moreTypes no longer includes exact matches to work type ('Data', 'Image', 'Text')

app/components/collections/detail_component.html.erb, app/components/works/detail_component.html.erb
Fixes #2297 and Fixes #2298
Add paragraph breaks and padding between paragraphs for work abstracts and collection descriptions. 
Note that this easy implementation adds a bottom margin below each paragraph, which spaces multiple paragraphs nicely, but also adds a bit of padding below a single paragraph (see examples below).  Seems like a reasonable tradeoff.
**Work (multiple paragraphs)**
**Work (single paragraph)**
**Collection (multiple paragraphs)**
Localhost
=> add paragraph breaks for collection descriptions and work abstracts

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, app/components/works/show/authors_contributors_component.html.erb, app/components/works/show/authors_contributors_component.rb, spec/components/works/detail_component_spec.rb
Fixes #2283 - split authors and contributors into two tables on detail page
Opted to create a new component since each table is basically the same.
=> split authors/contributors into two tables on details page

app/javascript/controllers/collection_participant_form_controller.js, app/javascript/controllers/sunet_input_controller.js, package.json
Could help with #2524 - sunet lookup issues for collection partipants/owner changes.
I saw this issue too when running the integration tests, and one theory is that we are running too many queries too quickly against the sunet lookup API.  This adds a debounce, so that we won't execute more than one query every 700 milliseconds.  That seems like a reasonable delay that is not so long as to make you think something is not working, but long enough to keep it from firing with each keypress.
=> add debounce to avoid too many sunet lookups

app/models/abstract_contributor.rb, spec/components/works/contributor_role_component_spec.rb
The author should be the default in the contributor role drop-down select list and this is the easy way, by just making it first in the list, even though it is slightly out of alphabetical order.
Verified as ok with PO
=> author should be first in the list

app/components/works/detail_component.rb, app/components/works/version_description_component.html.erb, app/forms/draft_work_form.rb, app/jobs/deposit_job.rb, db/migrate/20220901184555_version_description.rb, db/structure.sql, spec/components/works/detail_component_spec.rb, spec/factories/work_versions.rb, spec/jobs/deposit_job_spec.rb
Fixes #2575  -- i find the two different column names in work_version and collection_version that actually refer to the same sort of data to be confusing.  Also leads to some code complexity that is coming out of work in #2346 
CI
=> rename description column in works to version_description

app/components/works/subtypes_component.html.erb
Fixes #2282
This commit tweaks CSS classes and HTML structure in the work subtypes component so that subtypes (and "more types") in the work edit form render as vertically oriented checkboxes as opposed to horizontally oriented checkboxes.
CI, local testing, and tested successfully by PO in stage
No tests added since this affects only visual rendering of page.
=> Render work subtypes on edit form like the new form

app/controllers/works_controller.rb
Fixes bug introduced in PR #2576 resulting in version_description not being saved for works.
Needs integration testing and unit test check. 
=> Adding version_description to controller

README.md
=> Remove unnecessary env variables from example.

app/components/works/add_files_component.html.erb, app/components/works/file_row_component.html.erb, app/components/works/file_row_component.rb
Fixes #1359 - add file size and date uploaded to the work edit page for previously uploaded files.
NOTE: See comment trail for updated screenshots
What I have now: 
What is should look like: https://github.com/sul-dlss/happy-heron/issues/1359#issuecomment-900828723
=> Add file size and date uploaded to upload file display

app/jobs/deposit_job.rb, app/models/work_version.rb, spec/jobs/deposit_job_spec.rb
closes #2570
Always having to deposit files is expensive.
Unit, QA
=> Metadata only deposits.

app/components/collections/history_component.html.erb, app/jobs/deposit_status_job.rb, lib/tasks/deposit.rake, spec/components/collections/history_component_spec.rb, spec/jobs/deposit_status_job_spec.rb
Fixes #2346
Fixes #2347
This commit injects the version description into the event context for both works and collections, so that the user-provided description is surfaced in work and collection event history.
Thanks for working on this and using the more idiomatic approach, @lwrubel!
Also includes:
* Align collection event history component with work event history component
CI, local dev, QA
=> Add version description to event history tables

app/components/admin/collection_activity_row_component.html.erb, app/components/admin/collection_activity_row_component.rb, app/components/admin/collections_activity_table_component.html.erb, app/components/admin/collections_activity_table_component.rb, app/components/admin/item_activity_row_component.html.erb, app/components/admin/item_activity_row_component.rb, app/components/admin/items_activity_table_component.html.erb, app/components/admin/items_activity_table_component.rb, app/components/admin/locked_item_row_component.rb, app/controllers/admins_controller.rb, app/forms/collection_settings_form.rb, app/models/collection_version.rb, app/views/admins/collections_recent_activity.html.erb, app/views/admins/items_recent_activity.html.erb, spec/requests/admins_spec.rb
Fixes #2567 - simplify recent activity tables in admin interface
Note: we are also simplifying the query and ignoring events, and just using the "last_updated" column on the work/collection versions, which means we will consider even a change to a title as a recent activity.  This required adding some hooks to ensure the updated_at column is touched when any bits of metadata in associated tables are changed.
Also, use title presenters for works and collections so that those in draft states and/or without entered titles will display correctly in the tables (e.g. they will show a linked "No title" instead of a URL or blank row).
Localhost
=> simplify recent activity on admin page

app/jobs/deposit_status_job.rb, app/services/deposit_completer.rb, lib/tasks/deposit.rake, spec/services/deposit_completer_spec.rb
This commit better aligns how local dev handles completing deposits and how it is done in deployed environments. It reduces potential drift.
CI, local, QA
=> Extract deposit completer class from task and job

app/javascript/controllers/collection_participant_form_controller.js
If they don't have access, the server will send a redirect. We don't want the fetch to follow the redirect as they will receive HTML not json
=> Give an error when trying to redirect

Gemfile.lock, app/jobs/deposit_job.rb, spec/jobs/deposit_job_spec.rb
This commit allows the deposit job to proceed for metadata-only updates for objects that do not yet have a druid. If the object has a druid and the SDR find operation fails, an exception will be raised and reported to Honeybadger.
CI
=> Do not run SDR find in deposit job when no druid

app/assets/stylesheets/workEditor.scss
Fixes #2605 - do not grey out unselected labels next to radio buttons
Date drop downs are still made inactive if you select "immediately" since they are not applicable
This PR changes it to look like this:
=> do not grey out unselected radio options

spec/jobs/deposit_job_spec.rb
This test is impossible: it cannot be the case that an update is being performed on a work without a druid. The druid is what determines if a create or an update.
This test was attempting to test the handling of a situation that only occurred because there was a different bug in the code (related to find previous versions). Once that was fixed, this test became impossible.
=> Remove impossible test.

app/controllers/works_controller.rb, app/services/work_version_event_description_builder.rb, spec/features/update_existing_work_spec.rb, spec/services/work_version_event_description_builder_spec.rb
Fixes #2633 - if a user uploads a file, but adds no description, we do not want to record the file description as changed (it currently says it's change even though it is blank, even though it technically "changed", so we just ignore if blank)
More importantly, I also noticed the the reform `changed?` method we use in `WorkVersionEventDescriptionBuilder` seems to indicate some attributes aren't changed, when they actually have.  I was having trouble getting this to work until I did some debugging and saw this.   I suspect that's because we are passing the form to this builder *after* we have persisted to the database, and perhaps this is altering the logic (update: but only for the update action for existing objects)
Event description updates for existing objects has been broken until …
=> do not say a file description changed if it is blank

app/components/works/contributor_row_component.html.erb, app/components/works/contributor_row_component.rb
Consistency in the UI. This makes the radios the primary color. Now they match the look of the radios on the collection form.
Old:
New:
=> Add missing radio button bootstrap styles

app/components/works/detail_component.html.erb
Fixes #2641 - looks like a turbo/stimlus  issue with the link back to collection page, tell it to re-render the whole page
Localhost
=> correctly render new collection page link

app/controllers/collection_versions_controller.rb, spec/features/update_existing_collection_spec.rb
Resolves #2617. 
Added unit test and ran integration test on QA. 
=> Create event context before after_save called

app/mailers/collections_mailer.rb, app/services/collection_observer.rb, app/views/collections_mailer/first_draft_created.html.erb, app/views/collections_mailer/item_deposited.html.erb, app/views/collections_mailer/version_draft_created.html.erb, spec/jobs/deposit_status_job_spec.rb, spec/mailers/collections_mailer_spec.rb, spec/models/work_version_spec.rb
Similar to #2663, the work owner is used instead of the depositor when sending email notifications (in this case, for the collection emails, in the case of #2663, for the work related emails).
Note that the text of a couple of the emails looks like this:
"The Depositor XXXX has started a new version"
Not sure if we want to change the text in the email to say "The Owner XXX...", to me that seems a bit awkward and oddly worded for an end user, even if technically correct.
Updated tests
=> use work owner instead of depositor in collection mailers

app/components/dashboard/approvals_component.html.erb, app/mailers/works_mailer.rb, app/models/work.rb, app/services/work_observer.rb, app/views/reviewers_mailer/submitted_email.html.erb, spec/mailers/reviewers_mailer_spec.rb, spec/mailers/works_mailer_spec.rb, spec/models/work_version_spec.rb
Fixes #2654 - when sending email notifications/reminders about work activity, we should send to the current **owner** not the **depositor**.  In many cases, these are the same person (and start out that way by default), but when an admin switches the work to a new owner, the new owner should be getting these notifications, not the original depositor.
Updated CI
=> use work owner instead of depositor in work mailers

app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/forms/work_form.rb, spec/forms/work_form_spec.rb, spec/requests/edit_work_spec.rb
Fixes #2662 (see comments for discussion on the ticket that led to this outcome): if the user selects the "globus" option and saves the form  (draft or deposit), remove any attached files instead of throwing a validation error.
Localhost and added new requests specs
=> remove attached files when globus option is selected

app/components/works/keywords_row_component.html.erb
See https://getbootstrap.com/docs/5.0/migration/#helpers The only reason this happened to work is that fort-awesome also ships a .sr-only class
locally
=> Replace bootstrap 4 class with bootstrap 5 class

app/assets/stylesheets/workEditor.scss, app/components/works/contributor_row_component.html.erb
Ref #2642
Locally:
Before:
After:
=> Add radio button labels to improve accessability of authors/contributors

app/forms/draft_work_form.rb, spec/factories/work_versions.rb, spec/requests/edit_work_spec.rb, spec/services/work_version_event_description_builder_spec.rb
=> Allow removing all work subtypes.

app/controllers/first_draft_collections_controller.rb, app/controllers/works_controller.rb, spec/features/create_new_collection_spec.rb, spec/features/create_new_work_spec.rb
Currently when you create a new work, the description of changes in the "Updated by user" history event lists a bunch of fields.  When you create a new collection, the description of changes in the "Updated by user" history event is blank.
This makes both say "Created", which seems to make more sense for a brand new work or collection.
Note: a new version of an existing work will continue to list fields that were changed, as will a new version of an existing collection.  This change only applies to new works and collections.
~~Verify this change with PO.~~ Verified
Localhost and updated tests.
=> New works and collections should say "Created" in the description of changes

.circleci/config.yml
Because we deploy on ruby 3.1
CI
=> Test on ruby 3.1

app/controllers/works_controller.rb
Fixes #2695 - redirect to the dashboard if we are deleting a work from there, else go back to the collection deposits page (unchanged)
Localhost
=> redirect to dashboard when deleting works from there

app/components/works/detail_component.html.erb, app/components/works/edit_button_component.rb
This ensures it doesn't go outside the container if the title is long. Fixes #2602
locally
=> Wrap the EditButtonComponent with clearfix

app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/work_type_controller.js, cypress/spec/work_type_modal.cy.js
closes #2687
Per user feedback for errors.
Unit, cypress
=> Require subtypes for music and mixed materials.

app/components/works/detail_component.html.erb, app/components/works/form_component.html.erb, app/components/works/form_component.rb, app/forms/draft_work_form.rb, app/forms/work_form.rb, app/javascript/controllers/auto_citation_controller.js, app/models/work_version.rb, app/services/cocina_generator/description/generator.rb, app/services/work_observer.rb, spec/features/auto_citation_spec.rb, spec/features/create_new_draft_work_spec.rb, spec/features/create_new_work_spec.rb, spec/requests/edit_work_spec.rb, spec/services/cocina_generator/description/generator_spec.rb
Resolves #2628. Adds DOI or placeholder to the auto-generated citation. Goes with https://github.com/sul-dlss/dor-services-app/pull/4234. 
Unit, integration tests on QA. 
=> Add doi to auto-generated citation

app/controllers/work_decommission_controller.rb
Rails associations will automatically run a purge_job when you destroy the object they are attached to.
CI
=> [refactor] simplify code for cleaning up attached files

app/controllers/works_controller.rb, app/services/work_version_event_description_builder.rb, spec/features/create_new_work_spec.rb, spec/requests/create_work_spec.rb, spec/services/work_version_event_description_builder_spec.rb
Fixes #2686 - indicate if a license was changed from the default for a brand new work; if not, keep the current message ("Created")
Todo: 
Localhost and added a request test
=> correctly show license modified on new works

docker/app/Dockerfile, docker/workers/Dockerfile
To use the same version of Ruby in dev as in deployed code. Also, image won't build on 3.0.
Locally built and brought up.
=> Updating ruby version in docker images

app/assets/stylesheets/collection.scss, app/components/collections/admin_component.html.erb, app/components/collections/admin_component.rb, app/components/collections/detail_component.html.erb, app/components/collections/links_component.html.erb, app/components/works/admin_component.rb, app/controllers/collection_decommission_controller.rb, app/controllers/collection_versions_controller.rb, app/controllers/collections_controller.rb, app/models/collection_version.rb, app/policies/collection_decommission_policy.rb, app/policies/collection_policy.rb, app/policies/collection_version_policy.rb, app/policies/work_policy.rb, app/views/collection_decommission/edit.html.erb, app/views/collection_versions/_edit_link.html.erb, app/views/collections/_collection.html.erb, app/views/collections/_deposit_button.html.erb, app/views/collections/admin.html.erb, config/locales/en.yml, config/routes.rb, spec/components/collections/admin_component_spec.rb, spec/factories/collection_versions.rb, spec/features/decommission_collection_spec.rb, spec/features/purl_reservation_spec.rb, spec/models/collection_version_spec.rb, spec/policies/collection_decommission_policy_spec.rb, spec/policies/collection_policy_spec.rb, spec/policies/collection_version_policy_spec.rb, spec/requests/decommission_collection_spec.rb
Fixes #2629
This commit adds the ability to decommission collections if and only if all of their works have previously been decommissioned (or if they have no works). The approach taken in this commit mirrors that used for decommissioning works, with deviations where necessary due to design differences between collections and works.
CI, and tested with Amy in a deployed env
=> Allow collections to be decommissioned

README.md, app/jobs/deposit_complete_job.rb, spec/jobs/deposit_complete_job_spec.rb
DepositCompleteJob seems easier to understand than DepositStatusJob
CI
=> Rename deposit complete job

.rubocop.yml, app/components/admin/all_collections_row_component.html.erb, app/components/admin/all_collections_row_component.rb, app/components/collections/show/settings_header_component.html.erb, app/controllers/admin/collection_reports_controller.rb, app/models/admin/collections_report.rb, app/views/admin/collection_reports/new.html.erb, spec/components/admin/all_collections_row_component_spec.rb, spec/factories/object_states.rb, spec/features/decommission_collection_spec.rb, spec/services/admin/collections_report_query_spec.rb
~~HOLD for PO review~~  Amy approved.
Addressed tweaks to UI for decommissioned collections 
Fixes #2748
locally, and specs written
=> Collection decommish tweaks

app/services/active_storage/service/sdr_service.rb
Fixes #2785 ~~we aren't sure why a `PurgeJob` was called -- expectation is that you should not be able to purge something in preservation already.  This change will hopefully alert HB in a way that gives us a more useful backtrace than what is in~~ This makes the call to delete the Preservation file object a noop, which is what we intend.  Will prevent this HB alert from happening in the future: https://app.honeybadger.io/projects/77112/faults/88770594
CI
=> Delete on Preservation Object storage should be a no-op

Gemfile, Gemfile.lock
preservation-client version 5.0 removes primary_moab_location, which is never used here, thus perfectly safe here.
=> preservation-client is now version 5.0.0

app/models/concerns/work_version_state_machine.rb, app/services/repository.rb, spec/jobs/assign_pid_job_spec.rb, spec/jobs/deposit_complete_job_spec.rb, spec/models/work_version_spec.rb, spec/requests/edit_work_spec.rb, spec/services/repository_spec.rb
closes #2792
To prevent H2 and SDR versions from getting out of sync.
Unit
=> Check version before deposit update.

app/controllers/accounts_controller.rb, spec/requests/accounts_spec.rb
Because we would like to add more than just jcoyne as a depositor.
i.e. this allows us to add anyone has a depositor/reviewer on a ticket that is in our localhost database
Localhost
=> query local database when not in production for account service lookup

app/models/concerns/work_version_state_machine.rb, spec/features/mediated_deposit_versioning_spec.rb, spec/models/work_version_spec.rb
To get tests to pass in local development 
Local testing
=> Skip check_version in dev

app/jobs/base_deposit_job.rb, app/jobs/deposit_job.rb, app/services/repository.rb, app/services/sdr_client_authenticator.rb, spec/services/repository_spec.rb
Fixes #2806
This commit fixes a bug caused by the Repository class having a hidden dependency on a valid SDR client token. Moving authentication into the Repository class ensures we are not bitten by `SdrClient::Find::Failed` "Signature has expired" errors.
CI
=> Ensure SDR client is authenticated in Repository class

config/initializers/sidekiq.rb
Sidekiq wasn't getting logged anywhere. With this removed, sidekiq logs to production.log.
=> Remove sidekiq logging configuration.

app/services/repository.rb, spec/services/repository_spec.rb
closes #2816
Version validation was disallowing PURL reservation.
Unit, stage
=> Allow version validation to accomodate PURL reservation.

README.md
~~To me it looks like the `bin/dev` script sets a user and role by default and does not allow them to be overridden, as is currently suggested by the README.  This was confusing me during recent debugging until I noticed it.~~
Add note about clearing session when changing roles
=> readme should indicate you need to clear sessions when changing roles

app/mailers/helps_mailer.rb, spec/mailers/helps_mailer_spec.rb
#2821 shows that emails do not appear to be making through to Jira.  This adds the sdr-contact list as an alternate location which allows email to get through even if Jira integraiton is not working (though of course, will still be a problem if the sever can't send emails at all).
Re-evaluate if still needed once #2821 is fixed.  
See https://stanfordlib.slack.com/archives/C09M7P91R/p1666380457093009
Localhost and updated test
=> add sdr-contact email for form submission

app/controllers/collections_controller.rb
Fixes #2825 by not enforcing authorization before rendering the admin component which causes a redirect to root.
=> Do not redirect to the root when a depositor views a collection

app/jobs/deposit_job.rb, spec/jobs/deposit_job_spec.rb
closes #2833
Prod bug causing deposits to fail.
Unit, QA, prod
=> Clean content type when depositing.

Gemfile, Gemfile.lock
To fix deployed environments.
CI + integration-tests in stage
=> Pin sdr-client back to 0.96

app/components/works/add_files_component.html.erb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/forms/work_form.rb, app/models/work_version.rb, app/services/work_observer.rb, cypress/spec/create_work.cy.js, db/migrate/20221115215744_work_upload_type.rb, db/structure.sql, spec/factories/work_versions.rb, spec/forms/work_form_spec.rb, spec/models/work_version_spec.rb, spec/requests/create_work_spec.rb, spec/requests/edit_work_spec.rb, spec/services/work_version_event_description_builder_spec.rb
In this workcycle, we will need to expand the options available for users to select from when adding files to an object from two choices (browser upload and globus) to three choices: 
- browser upload 
- globus
- single ZIP file to be expanded
Our current database schema uses a `globus` boolean type column on the `work_version` to designate if an object uses globus uploads or not.  This PR switches the name of the column, makes it an enum to allow for more than two options, and fixes up the code to use the new schema.
This is pre-requisite work for #2843 (and possibly others).
Exiting test suite (updated as needed) and localhost
=> prepare for multiple selectable upload types

app/javascript/controllers/dropzone_controller.js
closes #2860
Prevent user disappointment.
There was already a maxsize check in place. This fixes a small bug that I encountered while testing locally.
=> Fix for maxsize check on upload.

app/components/works/add_files_component.html.erb, app/components/works/buttons_component.html.erb, app/components/works/form_component.html.erb, app/components/works/form_component.rb, app/controllers/works_controller.rb, app/javascript/controllers/deposit_button_controller.js, config/settings.yml, cypress/spec/create_work_version.cy.js, spec/components/works/add_files_component_spec.rb, spec/components/works/buttons_component_spec.rb, spec/components/works/form_component_spec.rb
Resolves #2846 and #2874 to disable the Deposit button when someone selects the new globus upload option. There is a feature flag so this will not show up unless desired. Also partially implements #2844 by adding new text for the new globus upload radio button option.
Unit tests, added cypress test for feature flag, deployed to QA.
h2 integration test on QA passed, although it took a couple of retries. 
=> T2846 disable deposit for globus upload

app/components/works/add_files_component.html.erb, app/forms/draft_work_form.rb, app/javascript/controllers/file_uploads_controller.js, cypress/spec/create_work_version.cy.js, db/migrate/20221117233130_no_upload_type_default.rb, db/structure.sql, spec/features/create_new_draft_work_spec.rb, spec/features/create_new_work_spec.rb, spec/requests/create_work_spec.rb
Fixes #2859 -- do not select any radio button by default when creating a new work, which forces the user to select one
We still need to validate that something is selected to save as draft, but we cannot enforce at the model level because PURL reservations still need to be created without a selection.
Localhost, added a test, modified existing tests to pre-select the previous "browser upload" default.
=> do not have a default upload option selected

lib/tasks/lock.rake
Fixes #2880 - add a rake task so we can easily lock a list of works (specified in a CSV) or all works in a list of collections (specified in a CSV).  Only locks works if not already locked (and if they have a druid if part of a collection, as per Amy's request).
Localhost
=> add a rake task to lock works in a collection or a list of works

app/services/cocina_generator/dro_generator.rb, app/services/cocina_generator/structural/file_generator.rb, app/services/cocina_generator/structural/generator.rb, spec/factories/attached_files.rb, spec/jobs/deposit_job_spec.rb, spec/services/cocina_generator/dro_generator_spec.rb, spec/services/cocina_generator/structural/file_generator_spec.rb
Resolves #2878, #2879, #2886 to
- update cocina structural metadata on later versions of works, rebuilding cocina (rather than copying) for current and existing filesets. Rebuilding cocina will update the label, publish/shelve options, and access rights.
- fixes the externalIdentifier format for filesets and files
Integration, unit. 
DONE: This also needs sul-dlss/sdr-api#535 to be deployed to have the file ids match the fileSet ids. 
=> Always rebuild structural cocina

README.md, app/controllers/works_controller.rb, app/jobs/globus_setup_job.rb, app/views/layouts/application.html.erb, config/settings.yml
Follow on from #2887 
Allow us to test the globus workflow in localhost by simulating the response from the globus API.  This is useful as we may to verify the workflow works as expected by simulating the test H2 user not having a globus account, and then later having a globus account, so we can verify H2 behaves as expected.  You configure this in your `settings.local.yml`  as explained in the updated README.  It will automatically be ignored if running in production regardless of setting.
Localhost
=> allow globus to be put in test mode for localhost work

spec/jobs/globus_setup_job_spec.rb
This spec `spec/jobs/globus_setup_job_spec.rb:86` is flaky and I can't figure out why.  This just adjusts that test and a similar adjacent test to mock out and expect the event to occur instead of testing the actual final state (i.e. it assumes the event we are expecting to be called will then correctly transition the state to the expected value, which is tested in `spec/models/work_version_spec.rb` anyway).
Existing tests
=> fix flaky state transition test

app/services/cocina_generator/structural/generator.rb, spec/services/cocina_generator/dro_generator_spec.rb
**Hold until confirmed tested** by @andrewjbtw 
Connects to sul-dlss/sul-embed#1380
This commit supports work to render folder/directory path information in filenames within sul-embed. Currently, sul-embed respects the order of contentMetadata in public XML (which is generated from from Cocina). Meanwhile, files for a given work in H2 are ordered randomly, based partly on 1) the order in which they were uploaded, and 2) whether the files are staged or preserved. This commit establishes a consistent order for files when generating Cocina for an H2 work, and that order is ascending alpha based on filenames, meaning sul-embed can continue to respect the given order.
CI
=> Generate filesets sorted by their filenames

app/views/works_mailer/globus_deposited_email.html.erb
Fixes #2898 - change text of email to sdr-support when a globus deposit is made
Existing tests
=> change text of email on globus deposit

spec/models/work_version_state_machine_spec.rb
#2906 removed the globus_upload feature flag, there was one more instance of it that can be removed
Existing tests
=> remove one more bit of the globus_upload feature flag

app/components/dashboard/in_progress_row_component.html.erb, app/components/works/globus_setup_button_component.html.erb, app/controllers/works_controller.rb
Fixes #2916 - remove button from dashboard, and change where we re-direct to after globus setup complete
Localhost and existing tests
=> remove globus setup complete button from dashboard

app/components/works/show/files_component.html.erb, spec/components/works/show/files_component_spec.rb
Resolves #2907 to sort files case-insensitive. 
Unit and deployed to QA.
=> Order files by filename

app/assets/stylesheets/work.scss, app/components/works/show/files_component.html.erb, app/components/works/show/files_component.rb, app/controllers/works_controller.rb, app/views/works/_files_list.html.erb, config/routes.rb, spec/components/works/show/attached_file_component_spec.rb, spec/components/works/show/files_component_spec.rb, spec/features/create_new_work_spec.rb
Resolves #2910 to put files in a scrollable container and lazy load with turbo.
Unit. 
=> Load work files table with turbo

app/jobs/fetch_globus_job.rb, spec/jobs/fetch_globus_job_spec.rb
Fixes #2935
This commit mirrors logic already applied to zip uploads to make sure bogus MacOS files are not included in H2 items.
CI + tested successfully by Amy in QA
=> Ignore MacOS-specific bogus file paths in Globus uploads

app/components/works/globus_setup_component.html.erb, app/components/works/globus_setup_component.rb
Fixes #2915 - add a banner to the top of the item show/detail page for globus deposits in a draft state directing users to the help page and showing them the folder name we created on globus.  
This is in the same spot that the banner shows for users who still need to complete their globus account setup (i.e. that banner goes away when they complete their setup and is replaced by this one).
**Account setup complete** (new banner)
**Account setup needed** (existing banner)
~~HOLD for language updates by Amy~~
Localhost
=> Add a banner to globus deposits on item show page

app/assets/stylesheets/details.scss, app/components/works/show/attached_file_component.html.erb, app/components/works/show/attached_file_component.rb, app/components/works/show/directory_component.html.erb, app/components/works/show/directory_component.rb, app/controllers/works_controller.rb, app/models/attached_file.rb, app/services/file_hierarchy_service.rb, app/views/works/_files_list.html.erb, spec/components/works/show/attached_file_component_spec.rb, spec/services/file_hierarchy_service_spec.rb
Fixes #2943 - show file hierarchy on the work show page, as mocked up here: https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471005875
Borrowing from the Argo display: https://github.com/sul-dlss/argo/pull/3913/files
Questions:
- what does the empty vs filled in folder icon mean in the mockups? note: we will never have a folder with no files in it in H2 (and how to render an empty folder?)
- Localhost
- Existing tests
- Updated/added tests
=> Show file hierarchy on the work show page

config/locales/en.yml
Adding a translation for the `globus_setup_complete` event to go from:
to 
@amyehodge if you would like different wording, just let me know.
Unit
=> Adding globus_setup_complete event text

app/components/works/globus_setup_component.html.erb
Resolves #2953 to add instructions to globus setup complete button message. 
Unit.
Here's what this looks like, @amyehodge. I can deploy to QA/stage if you like. (Sorry, this was an admin user so that box is in the images):
BEFORE
AFTER
=> Update user message for globus setup complete button.

app/assets/stylesheets/work.scss, app/components/works/detail_component.html.erb, app/components/works/detail_state_display_component.rb, spec/components/works/detail_component_spec.rb, spec/factories/object_states.rb
Resolves #2959 to show a different message, without a spinner, on the detail page when waiting for Globus files to transfer. 
This will also wrap, @amyehodge was OK with that (see conversation in #2959). 
Unit, added spec. 
=> Separate detail message for globus wait states

app/components/works/globus_setup_component.html.erb
Resolves #2956 to add instructions for user returning to Globus upload work page. 
Unit.
@amyehodge the [screenshot in the issue](https://github.com/sul-dlss/happy-heron/issues/2956#issuecomment-1397365361) is what this looks like. If you'd like to see it live, let me know and I'll deploy to QA.
=> Globus user instructions as warning

app/components/works/add_files_component.html.erb, spec/components/works/add_files_component_spec.rb
Fixes #2957 
1. rename radio buttons for different upload types
2. add panels with instructions for globus uploads
Looks like this now (note: globus instructions only appear when user selects the globus radio button):
Existing tests
=> rename file upload radio button labels; add globus instruction panels

app/components/works/show/files_component.html.erb, app/components/works/show/files_component.rb
Resolves #2958 to add a files component with a message for globus uploads. 
Unit and QA. 
Here's what the box looks like on QA, @amyehodge:
=> Showing files table with a message for globus type

app/models/attached_file.rb, app/services/active_storage/service/globus_service.rb, spec/jobs/fetch_globus_job_spec.rb
Resolves #2966 to use the work ID rather than the druid for globus attached file blob keys.
Unit and QA
=> Use work id in globus attached_file blob key

app/services/repository.rb, spec/services/repository_spec.rb
closes #2971
To allow embargoes to be lifted without creating a kurflufel.
Unit, Amy
=> Tweak version checking strategy.

app/components/works/add_files_component.rb, app/controllers/works_controller.rb, spec/components/works/add_files_component_spec.rb, spec/factories/work_versions.rb
Resolves #2970 so that previous version's globus endpoint is not used on a new work version. 
Unit and QA
=> Hide globus confirmation checkbox until new version draft saved

app/controllers/works_controller.rb, app/mailers/works_mailer.rb, app/views/works_mailer/version_mismatch_email.erb, config/locales/en.yml, spec/mailers/works_mailer_spec.rb, spec/requests/edit_work_spec.rb
HOLD for UI decision from Amy (?)
closes #2864
Prevent version mismatch mayhem.
Unit, QA
=> Warn user and notify admin on version mismatch.

README.md, config/deploy/prod.rb
Reverts #2905
We are clear to deploy H2 `main` to prod again!
N/A
=> Allow deploying `main` to prod again

app/jobs/globus_setup_job.rb, config/settings.yml, spec/jobs/globus_setup_job_spec.rb
refs https://github.com/sul-dlss/infrastructure-integration-test/issues/534
To allow an integration test to bypass a user adding files to globus.
=> Adds globus integration test support.

app/jobs/deposit_job.rb
Addressing timeout error with a deposit, resolves #2992. 
Unit, stage integration test (although that is failing at the shelve step, which I see happening in other contexts too.)
=> Increase sdr client read_timeout

app/controllers/works_controller.rb
Fixes problem where there is an acceptable version mismatch (H2 version is one less than Argo) but H2 is not allowing a new version to be created. 
Unit, QA with integration test
=> Check validity of correct version number

app/models/concerns/work_version_state_machine.rb
Fixes #2997 - the PURL and DOI link placeholders should be replaced with the actual values in the cocina (and thus on the PURL)
What we found:
- in some example druids, e.g. https://argo.stanford.edu/view/druid:tb076ph9251 we noticed that the cocina had correctly replaced the placeholder links in a "create" event, but then there was an "update" event shortly after with the incorrect cocina
- DSA shows that the create action will replace the link placeholders but the update action will not (see https://github.com/sul-dlss/dor-services-app/blob/main/app/services/create_object_service.rb#L116-L123)
- we then tried to investigate why an update event occurred with bad data after the correct data was posted by looking at sdr-api logs
- the only part of H2 that appears to call sdr-api is the …
=> ensure we do not run the object update method after creating it

app/components/works/edit/attached_file_component.html.erb
closes #2998
So that hierarchy isn't lost on new work versions.
Local
=> Retain path in new work versions.

config/routes.rb
Fixes #3014 - add a redirect for old contact form URL to new one
Localhost
=> add redirect for old contact form to new help form

Gemfile.lock, app/jobs/fetch_globus_job.rb
We've observed that long running Globus `list_files()` operations can cause the database connection to be lost, and subsequent attempts to use the database fail. This change should cause connections to be re-established.
(hopefully) fixes #3019
Unit tests
=> Reconnect to database

app/components/works/add_files_component.html.erb
=> Remove subtext for basic file upload option in deposit form.

app/services/active_storage/service/sdr_service.rb
When purging objects that have images, we do not want ActiveStorage to do anything.  Currently we get an HB alert from a raise in the ActiveStorage stack, this just makes it a no-op, which we already have for the `#delete` method.  This `#delete_prefixed` method is also called for images by ActiveStorage and also needs a noop. It is the same change as was done for the globus service a couple months ago: https://github.com/sul-dlss/happy-heron/pull/2969/files
The HB alert: https://app.honeybadger.io/projects/77112/faults/88770594
Existing CI
=> do not alert HB for a purge

app/assets/stylesheets/dashboard.scss, app/assets/stylesheets/frontpage.scss, app/components/admin/navigation_component.rb, app/components/dashboard/page_content_component.html.erb, app/components/dashboard/page_content_component.rb, app/components/page_content_component.html.erb, app/components/page_content_component.rb, app/controllers/admin/page_content_controller.rb, app/controllers/dashboards_controller.rb, app/controllers/welcome_controller.rb, app/models/page_content.rb, app/policies/page_content_policy.rb, app/views/admin/page_content/edit.html.erb, app/views/admin/page_content/index.html.erb, app/views/dashboards/show.html.erb, app/views/welcome/show.html.erb, config/locales/en.yml, config/routes.rb, config/settings.yml, db/migrate/20230420204926_create_page_contents.rb, db/structure.sql, spec/factories/page_content.rb, spec/features/admin/page_content_spec.rb
Fixes #3052 - new admin option to admins can easily edit text and link shown on home page and dashboard page
Waiting on:
Note: the database design will allow for this same basic principle to be used on other pages as well, but for now it's all just hard-coded to use a single page ('home') which is shown on both the dashboard and the home page.  We still have two separate components for display, however, since the design will be different on the home page and the dashboard page.
Design provided by Astrid: https://projects.invisionapp.com/share/ER1387CAQNS5#/screens/473002124?browse
**As implemented in this PR:**
**Admin UI:**
Localhost and new spec
=> allow admin user to edit message shown on home page/dashboard

app/services/work_observer.rb, spec/models/work_version_state_machine_spec.rb
Fixes #3056 - send emails to admin when a user completes a globus email (instead of making it conditional on this setting, which also affects first draft collection email notification)
Existing specs
=> send an email when a user completes a globus deposit

app/services/work_observer.rb, spec/models/work_version_state_machine_spec.rb
Fixes #3056 (for real this time).
This also reverts the change in #3057, which was a red herring (that setting was actually true in production anyway).
The problem with our code is that once we fetch the files from Globus, we switch the upload_type back to 'browser' and so when we run this observer on state change to deposited, the upload type is not 'globus' and we never send an email.  Instead we need to look for the presence of a 'globus_endpoint' URL, which indicates the user originally selected globus as the upload mechanism.  It is not 100% foolproof, as a user may have selected globus originally, received an endpoint, and then later changed their mind back to browser before depositing, but this is an edge case the only consequence of which is that the administrator will get the …
=> actually fix the bug with globus deposit emails not going out

Gemfile, Gemfile.lock
Keep pace with reform-rails releases now that bug found in 0.2.4 was patched.
CI
=> Stop pinning reform-rails to pick up patch in 0.2.5

app/components/admin/navigation_component.rb, app/controllers/admin/work_version_searches_controller.rb, app/policies/work_version_search_policy.rb, app/views/admin/work_version_searches/index.html.erb, config/routes.rb, spec/features/admin/druid_search_spec.rb, spec/features/admin/work_version_search_spec.rb
Fixes #3059 - add admin function to search for work by work_version (useful for admins since HB messages frequently mention work_version IDs, but the app itself uses work ids in the URL
Localhost, new spec (also added a spec for the druid search feature i borrowed code from, since it didn't have one)
=> add work version search admin function

app/controllers/application_controller.rb
There are a few pages in H2 that are visible without authenticating, including the terms page (https://sdr.stanford.edu/terms). If an automated bot sends a long list of query params in a request while not authenticated, the URL gets put in the `request.fullpath`. This can trigger a cookie overflow if it's too long. See: https://app.honeybadger.io/projects/77112/faults/96779132
The error could also be triggered if a session times out while a user has a page open with a lot of params in a GET request, but we POST forms in H2. Since it seems highly unlikely that a legitimate user would be sending a lot of query params in a GET request during normal usage, this should primarily affect bots. 
We already tried to mitigate 500 errors by lowering the acceptable length of the location before …
=> Further reducing allowed location size to avoid cookie overflow

app/views/helps/new.html.erb
Fixes #3118.
The first time user page uses the same form as the help link in the header (compare the background form with the help modal):
Adding a namespace to the [ActiveRecord::FormHelper](https://api.rubyonrails.org/v7.0.5.1/classes/ActionView/Helpers/FormHelper.html#method-i-form_with) call fixes the problem.
=> fix accessibility for help form by adding namespace

app/jobs/globus_setup_job.rb
closes ~~#3050~~ #3060
Avoid retrying jobs that will never succeed.
=> Discard GlobusSetupJob for deserialization error.

app/views/works/_edit_button.html.erb, spec/requests/work_edit_button_spec.rb
closes #3081
Prevent users from horking a work.
=> Disallow editing mid-globus.

app/components/works/subtypes_component.html.erb
closes #3138
Empty header is confusing.
Local
=> Do not show more options when mixed material.

app/components/works/show/attached_file_component.html.erb
=> Remove bullet on files list

app/components/works/keywords_row_component.html.erb, app/views/autocomplete/show.html.erb, spec/requests/autocomplete_spec.rb
closes #3139
So it looks correct.
=> Update autosuggest for stimulus-autosuggest 3.

app/controllers/work_move_controller.rb, spec/requests/move_work_spec.rb
Fixes #3024
This commit allows the owner of a work that has been moved to a new collection to deposit to the collection.
CI
No.
=> Add work owner as depositor to new collection

app/components/citation_modal_component.html.erb, app/components/dashboard/collection_component.html.erb, app/components/dashboard/in_progress_row_component.html.erb, app/components/works/purl_reservation_modal_component.html.erb, app/controllers/works_controller.rb, app/views/collections/_dashboard.html.erb, app/views/dashboards/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_terms_of_deposit.html.erb, app/views/welcome/first_time.html.erb, app/views/welcome/show.html.erb, app/views/works/_delete_button.html.erb, spec/components/dashboard/in_progress_row_component_spec.rb
Fixes #3148
Fixes #3150
* Remove WCAG A/AA and aria violations from welcome page
* Remove WCAG A/AA and aria violations from home page
* Address accessibility errors in welcome & home pages identified by axe and wave plugins
* Eliminate accessibility violations on dashboard page
No.
=> Improve accessibility for welcome/home page and dashboard

app/jobs/globus_setup_job.rb
On QA and stage, if you start a globus deposit with an empty title, this error is raised: https://app.honeybadger.io/projects/77112/faults/97250692
Unit and QA
=> Allow nil titles when integration test setting is true

app/components/collections/detail_component.html.erb, app/components/collections/show/deposits_header_component.html.erb, app/components/collections/show/details_header_component.html.erb, app/components/collections/show/settings_header_component.html.erb, app/components/collections/show/tabs_component.html.erb, app/javascript/controllers/datatable_works_controller.js
~~**NOTE**: This is currently based on the commits in #3159 for easier testing, so the diff looks larger than it really is.~~
Fixes #3151
Fixes #3152
This deals with a11y violations of the A/AA/aria variety as identified by the Siteimprove Accessibility Checker extension and the WAVE extension.
No
=> Improve accessibility for collections pages

app/components/works/add_files_component.html.erb, app/components/works/contributor_row_component.html.erb, app/components/works/keywords_row_component.html.erb, app/javascript/controllers/dropzone_controller.js
Closes #3149
Addressed all A and AA accessibility problems that I could find with SiteImprove, WAVE and Axe plugins.  Note that Axe found no violations in the original.
- ^^ note that the remaining all need design help
- ^^ I was unable to figure out the hidden fields causing the 4 errors still indicated by Wave, so I'm declaring this PR an excellent first cut.
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. …
=> Deposit form complies with WCAG A/AA accessibility levels

app/components/works/globus_setup_component.html.erb
Fixing instructions text to match mock-ups. @amyehodge.
(Mockup: https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/472346509_Globus_Auto_Account)
Note that the mockup has bullets and this is numbered (as originally). Should it switch to bullets?
Unit / local deployment
No
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility …
=> Editing item view globus instructions

app/components/works/add_files_component.html.erb, app/components/works/add_files_component.rb, app/components/works/globus_setup_component.rb, app/controllers/works_controller.rb, app/forms/draft_work_form.rb, app/models/work_version.rb, config/settings.yml, db/migrate/20230629154913_add_globus_origin_to_work_versions.rb, db/structure.sql, spec/components/works/add_files_component_spec.rb, spec/components/works/globus_setup_component_spec.rb, spec/factories/work_versions.rb, spec/requests/edit_work_spec.rb
=> Allows user to select globus origin.

app/views/works_mailer/globus_endpoint_created.html.erb, spec/mailers/works_mailer_spec.rb
Fixes #3049.
Updates email to globus users for new, improved workflow.
@amyehodge does this need PO approval?
@lwrubel if this is needed for other endpoints (Oak, etc.) ... then I assume there will be separate tickets.
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) for …
=> globus_endpoint_created mail message updated

app/assets/stylesheets/frontpage.scss, app/components/help_collection_component.html.erb, app/components/popover_component.html.erb, app/components/popover_component.rb, app/views/helps/new.html.erb, app/views/layouts/application.html.erb
Addresses some of the accessibility issues identified in #3171 
I hope it reduces them!
=> Some accessibility fixes for welcome/home page

app/components/works/subtypes_component.html.erb, app/components/works/work_type_modal_component.html.erb, app/javascript/controllers/more_types_controller.js, app/javascript/controllers/work_type_modal_controller.js
=> Adds aria-expanded for See more options.

app/controllers/first_draft_collections_controller.rb, app/controllers/works_controller.rb, config/environments/development.rb, config/environments/test.rb, spec/requests/create_collection_spec.rb, spec/requests/create_work_spec.rb, spec/requests/edit_collection_spec.rb
Fixes #3191
This commit adds `with_orcid` as a permitted parameter for works in the `WorksController`. As part of this work, configure the app to raise on unpermitted params in the test and dev envs, so we can better flag these before they get to production going forward, and then deal with all the failing tests that causes.
CI
No.
=> Address unpermitted params across various controller interactions

app/components/works/add_files_component.html.erb
=> Updating unzipping note.

app/components/collections/work_row_component.html.erb, app/components/collections/work_row_component.rb
Closes #3218 
These 2 changes improve the performance of how we are fetching the data displayed on the collection deposits page. The main change shows a direct SQL query to avoid preforming multiple queries per file to get the size (this becomes incredibly inefficient with a large number of files). The direct query improves the result time that was several minutes into a second or less.
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it …
=> Improve performance of collection deposits page

app/views/dashboards/_collection_summary_row.html.erb, spec/components/dashboard/collection_component_spec.rb
Fixes #3190 
Per suggestion from SODA report:  "The aria-label can be used to include the deposit name, which is what is being done for the edit links in the Actions column."
wrote a spec, plus ran SiteImprove, WAVE and axe tool
No.
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibili …
=> _collection_summary_row.html.erb: make link text more meaningful

app/services/cocina_generator/description/affiliations_generator.rb, app/services/cocina_generator/description/contributors_generator.rb, spec/factories/affiliations.rb, spec/services/cocina_generator/description/affiliations_generator_spec.rb, spec/services/cocina_generator/description/contributors_generator_spec.rb
closes #3201
So that affiliations are deposited in SDR.
Unit
=> Add mapping of affiliations to cocina.

app/components/works/add_files_component.html.erb, app/components/works/add_files_component.rb
closes #3196
Locally
https://github.com/sul-dlss/happy-heron/assets/588335/5aead8b5-88d9-4cc2-8eb9-02478969bd81
=> Allow user to change Globus origin.

app/components/works/add_files_component.html.erb
For some reason, changes were reverted in https://github.com/sul-dlss/happy-heron/pull/3217
=> Revert unintentional changes to add files component.

app/components/works/globus_setup_component.html.erb, app/components/works/globus_setup_component.rb, spec/components/works/globus_setup_component_spec.rb
closes #3212
User was getting an incomplete link.
Unit
=> Do not render globus instructions until globus endpoint is set.

.rspec, README.md, app/components/dashboard/continue_deposit_modal_component.html.erb, app/views/layouts/application.html.erb, spec/features/accessibility_spec.rb, spec/support/capybara_actions.rb
Fixes #3224
Fixes #3225
Fixes #3226
This commit unskips the prior skipped a11y feature specs and then handles some deficiencies that were missed in the earlier PR:
* Re-add the `accessibility` RSpec tag for CI, documenting it in the README
* For accessibility specs, make sure turbo-frames are loaded before auditing a11y, else we could have false negatives
* Remove the experimental aXe rules, since our icon link approach runs afoul of https://dequeuniversity.com/rules/axe/4.7/label-content-name-mismatch?application=axeAPI
I acknowledge that using `all()` to query the page is an imperfect way to make sure **all** turbo frames are loaded, but I have sniff-tested a number of specs and it at least seems most of them are. So this is an improvement in coverage even if it's imperfect.
No.
=> Unskip all accessibility feature specs

Gemfile, Gemfile.lock, app/models/abstract_contributor.rb, app/models/collection_version.rb, app/models/contact_email.rb, app/models/keyword.rb, app/models/related_link.rb, app/models/related_work.rb, app/models/work_version.rb, spec/models/collection_version_spec.rb, spec/models/contact_email_spec.rb, spec/models/contributor_spec.rb, spec/models/keyword_spec.rb, spec/models/related_link_spec.rb, spec/models/related_work_spec.rb, spec/models/work_version_spec.rb
Adds the [strip-attributes](https://github.com/rmm5t/strip_attributes) gem to easily remove leading/trailing whitespace from designated model attributes.
I chose to configure strip-attributes to only strip specific identified attributes, and also turned off the auto-conversion of `""` to `nil` which broke some tests because the columns were `NOT NULL`.
Fixes #3207
Local development instance and unit tests.
No
=> Strip whitespace

app/controllers/works_controller.rb, app/models/concerns/work_version_state_machine.rb, app/services/work_observer.rb, spec/models/work_version_state_machine_spec.rb, spec/requests/edit_work_spec.rb
Resolves #3071. Both FetchGlobusJob and UnzipJob, which send an event at the end, had been called from an `after_transition` callback. Moving that step out of the state machine, to the controller. 
Unit tests and QA testing. 
No front-end changes
=> Avoid race condition by moving job enqueuing out of state machine

lib/tasks/linters.rake
AFAICT, these requires are unnecessary, as they duplicate what is already listed in the Rubocop configuration. Also, none of our other codebases do this so it is clearly an outlier.
Nope
=> Remove unnecessary requires in rubocop task

app/components/collections/edit_license_component.html.erb, app/components/collections/settings_component.html.erb, app/components/collections/update/depositors_component.html.erb, app/components/collections/update/managers_component.html.erb, app/components/collections/update/reviewers_component.html.erb, app/components/first_draft_collections/create/details_component.html.erb, app/components/popover_component.html.erb, app/components/popover_component.rb, app/components/works/authors_component.html.erb, app/components/works/contributor_role_component.rb, app/components/works/contributor_row_component.html.erb, app/components/works/contributors_component.html.erb, app/components/works/dates_component.html.erb, app/components/works/description_component.html.erb, app/components/works/edit/file_row_component.html.erb, app/components/works/edit/files_component.html.erb, app/components/works/license_component.html.erb, app/components/works/publication_date_component.html.erb, app/components/works/related_work_component.html.erb, app/components/works/subtypes_component.html.erb, app/components/works/title_component.html.erb, app/components/works/work_type_modal_component.html.erb, spec/components/works/contributor_role_component_spec.rb
Fixes one accessibility item in #3171 
Note, after looking at https://inclusive-components.design/tooltips-toggletips/#inclusivetoggletips will leave this as aria-describedby tags, but have now moved the element they are attached to, in some cases to the form input.  In some cases, the tip is describing a section, so left on the label or legend in those cases.
Localhost
=> ensure all popovers have aria-describedBy

app/javascript/controllers/deposit_button_controller.js, cypress/spec/create_work_version.cy.js
Resolves #3246.
Once the "Check this box once all your files have completed uploading to Globus." box is checked, the "deposit is disabled" message will be hidden.
Unit, added to cypress spec.
No new issues.
=> Hiding globus deposit disabled message once box checked

app/components/works/contributor_row_component.html.erb
Closes #3206 
Updates the contributor form as seen below:
=> Update contributor form layout

app/services/orcid_stanford_user_service.rb, lib/tasks/orcid.rake, spec/services/orcid_stanford_user_service_spec.rb
=> Adds rake task for getting Stanford users not in MAIS.

app/javascript/controllers/deposit_button_controller.js
Resolves #3279 problem with deposit button being enabled with globus checkbox selected
Deployed to QA
https://github.com/sul-dlss/happy-heron/assets/1619369/ce96fa23-fb75-410e-90f9-b15acc3ec25f
No
=> Bugfix for globus deposits

app/components/works/add_files_component.html.erb
Fixes #3268 
I ran the site improve plug in against this change. There is a suggestion of an additional visual indicator (i.e. an icon) to improve the visibility of the link, but this is a minor change.
=> Update globus upload text for clarity on file count/size

app/services/check_move_work_service.rb, spec/factories/works.rb, spec/jobs/assign_pid_job_spec.rb, spec/services/check_move_work_service_spec.rb, spec/services/work_version_event_description_builder_spec.rb
closes #3253
So that the collection for a work can be changed prior to a deposit when a DOI is required.
Unit
=> Use assign doi to determine if collection can be moved.

app/components/works/affiliations_component.rb, spec/features/create_new_work_spec.rb
Part of #3285 - do not render affiliations UI component to avoid bugs it introduces
CI and localhost
=> do not render affiliation component

app/components/works/contributor_row_component.rb, app/components/works/keywords_row_component.html.erb, app/components/works/keywords_row_component.rb, spec/components/works/contributor_row_component_spec.rb
Fixes #3181 - make two generic delete button aira-labels (keywords and contributors) unique so users can tell what they are deleting.  The other trash can aria-labels all seem to be labelled appropriately as far as I can tell by searching through code.
For authors/contributors, aria-label for trash can will be:
- "Remove blank author" or "Remove blank contributor" for new rows (even if text added)
- "Remove [actual name]" if an existing row that was previously saved
For keywords, aria-label for trash can will be:
- "Remove blank keyword" for new rows (even if text added)
- "Remove [actual keyword]" if an existing row that was previously saved
=> add unique labels to remove buttons for contributors and keywords

app/components/works/add_files_component.html.erb
Fixes #3267 
No related warnings when running the siteimprove plugin.
=> Update zip upload text to include warning

app/components/works/detail_component.html.erb, app/views/dashboards/_collection_summary_row.html.erb
Fixes #3284 - opening the PURL link with a right-click should go to PURL.  I verified in Firefox that left click still does the copy as expected.
Localhost
=> purl links should go to purl

app/javascript/controllers/auto_citation_controller.js
Fixes #3277 
This enables and disables the manual citation switch when editing items based on the citation value.
In the first 2 screenshots, you can see that I'm using the manual citation as the title in the citation is different than the title in the work. This disables the "auto" citation so that the manual edit is not lost.
When the citation matches the auto generated citation the switch is enabled properly:
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA …
=> Update logic so that auto generated citation is properly enabled when editing

app/javascript/controllers/ordered_nested_form_controller.js
Fixes #3306 
Moving authors up and down on the item work page with the arrows (next to the trash icon) sometimes doesn't work as expected, particularly after adding a brand new blank author.  I believe the issue is that the use of `nextElementSibling` and `previousElementSibling` to find the `<div>` row to move up and down doesn't always work as expected.  If you insepct the HTML of the page after adding a new author, you will see some hidden form elements like this:
`<input autocomplete="off" type="hidden" value="10" name="work[authors_attributes][0][id]" id="work_authors_attributes_0_id">`
These are inserted into the DOM technically as siblings to the `<div>` rows we care about, and so the JS methods find them instead of the divs.  You can see this happening by addling `console.log` …
=> ensure move/up down button targets only contributor row elements

app/jobs/deposit_job.rb, spec/factories/work_versions.rb, spec/jobs/deposit_job_spec.rb
Resolves #3302 to change globus permissions to "r" when depositing starts. 
Unit and stage deploy. Also ran globus integration test. 
If a user tries to rename or edit a file on the globus endpoint once the deposit job starts, they'll get a permission denied message. 
Does not touch front-end.
=> Change globus endpoint permissions on deposit

app/components/popover_component.rb, app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, app/components/works/license_component.html.erb, app/controllers/works_controller.rb, app/forms/base_work_form.rb, app/services/cocina_generator/access_generator.rb, config/locales/en.yml, db/migrate/20230726172521_add_rights_to_work_version.rb, db/structure.sql, spec/components/popover_component_spec.rb, spec/components/works/form_component_spec.rb, spec/factories/work_versions.rb, spec/requests/create_work_spec.rb, spec/services/cocina_generator/access_generator_spec.rb
Closes #3094 as part of #3271
This adds the ability to add custom rights statement to a work, or use the one provided by the collection (if provided)
When provided in the collection:
It's displayed in the entry form for a work:
When allowed and not provided, entry is allowed:
Displayed on the work page:
Note that any custom rights statement is pre-pended to the `useAndReproductionStatement` in cocina per https://stanfordlib.slack.com/archives/C69UZCJ8M/p1690408613716939?thread_ts=1690408431.344109&cid=C69UZCJ8M
Custom instructions are used for the tooltip if provided:
⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test create_object_h2_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test …
=> Adds custom rights entry to the work and work display

app/controllers/preservation_controller.rb
[ActionController::Live](https://api.rubyonrails.org/classes/ActionController/Live.html) is needed for streaming responses. It also looks like setting `Last-Modified` on the HTTP response is needed to prevent passenger in standalone mode from reading the response into memory during caching.
Fixes #3310
Downloading a 4GB file on h2-stage, and not seeing the server go up in 🔥 The downloaded file completes and the checksum matches what is on preservation.
No
=> Mixin Live for streaming

app/components/works/license_component.html.erb
Fixes #3316 
The instructions are not displayed if a custom rights statement is provided.
=> Do not show instructions when custom rights are provided

app/components/collections/edit_terms_of_use_component.html.erb, app/components/collections/terms_of_use_component.html.erb, app/components/collections/terms_of_use_component.rb, app/components/popover_component.rb, app/components/works/license_component.html.erb, app/components/works/license_component.rb, app/models/collection.rb, config/locales/en.yml, config/settings.yml, spec/components/collections/terms_of_use_component_spec.rb
close #3317
close #3314
* manual testing on localhost
* unit tests
custom instructions now display above the custom terms text entry field:
the popover with additional guidance now displays the same text regardless of whether custom or default instructions are presented for custom terms entry:
no popover when custom terms are set by collection:
no additional terms section when additional terms are entirely disabled for the collection:
instructions displayed in separate table row from custom terms setting/value:
additional terms of use displayed without quotes, even when set by collection, and instructions row is hidden when custom terms are set by the collection:
⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test …
=> Fix collection show custom rights instructions

app/views/layouts/application.html.erb
Fixes #3313
This commit changes links in the SUL footer now that the new Stanford Libraries website has gone live after undergoing a thorough rebuild.
CI
No.
=> Fix Stanford Libraries footer links

app/components/citation_component.rb, spec/components/citation_component_spec.rb, spec/components/collections/works_component_spec.rb
Fixes #3188 
- Adds unique ids to the cite buttons
- Improves the screen reader experience by adding a meaningful aria-label to the link.
It improves a couple. tested using VoiceOver screen reader on my laptop.
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) for more …
=> Improve accessibility of work cite links

app/views/shared/_help_modal.html.erb, app/views/shared/_terms_of_deposit.html.erb
SiteImprove suggest the best practice for pages (and modals, etc) is that the top/header visual element be an H1 to apply proper hierarchy, starting with h2/h3 violates this best practice. From SiteImprove:
```
Heading tags help assistive technology users to understand how content is structured. They're also used for in-page screen reader navigation.
When determining heading levels, you should ensure that they follow a nested structure. h1 is used for the primary heading, followed by h2 for subheadings, and so on to h6.
```
⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test create_object_h2_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test manually in [stage|qa] environment, in …
=> Minor update to accessibility best practice update for modal headers

app/components/works/add_files_component.html.erb
Refs #3170 
This updates some of the divs to a `ul > li` list so that it is presented as a list to screen readers but does not change the visual representation.
=> Switch upload instructions to a list

app/components/works/add_files_component.html.erb, app/components/works/agreement_component.html.erb, app/components/works/authors_and_contributors_component.html.erb, app/components/works/authors_component.html.erb, app/components/works/contributors_component.html.erb, app/components/works/dates_component.html.erb, app/components/works/description_component.html.erb, app/components/works/embargo_component.html.erb, app/components/works/license_component.html.erb, app/components/works/title_component.html.erb, spec/components/works/agreement_component_spec.rb, spec/support/capybara_actions.rb
Refs #3170 
This moves the `<header>` components on the deposit form to actual `h2` and `h3` values to support the proper hierarchy for accessibility. 
Note from SODA recommendation:
```
Including the text in a <header> element does not make the text a heading.  
```
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility …
=> Make form headings fit h1/h2/h3 hierarchy for accessibility

app/assets/stylesheets/editor.scss, app/components/works/description_component.html.erb
Refs #3170 - this adds a visual indication when a button has gained focus using tab navigation.
WGAG Recommendation:
```
Ensure that when actionable elements receive focus, that it appears on screen and that a visible focus
indicator is present. Focus can be indicated in different ways, including change of background, lightness,
border, outline, underline, and other visual methods. Avoid the use of the "outline: none" CSS property.
As of WCAG 2.1, a custom focus indicator should have a minimum contrast ratio of 3:1 against the background.
```
⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test create_object_h2_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test manually in [stage|qa] …
=> Visually indicate when the form buttons get focus

app/components/works/contributor_row_component.html.erb, app/components/works/form_component.html.erb, app/components/works/publication_date_component.html.erb
Refs #3170 - I believe this is the final PR I can do against 3170 before a re-review. This adds the proper grouping and headings to improve the screen reader experience.
CI
Si/Wave tooling.
=> Labels and cleanup for the deposit form accessibility

app/views/shared/_terms_of_deposit.html.erb
This reformats the terms of use modal link at the top to use a list for assisting screen readers. The visual representation did not change:
before:
after:
=> Use list types when presenting content as a list

app/components/works/work_type_modal_component.html.erb
Fixes the heading classes used on the work type modal to improve the screen reader experience.
Fixes the heading organization - tested with the SiteImprove extension.
=> Fix work-type-modal heading classes for accessibility

app/components/works/add_files_component.html.erb, app/components/works/title_component.html.erb
The diff looks larger than it is below as the only change is wrapping the 2 sections with a fieldset and indenting,. This improves the screen reader experience on the deposit form so that users know how many check boxes are presented for file upload for instance.
CI
Manual screen reader review
=> Add missing fieldsets on deposit form

app/components/collections/works_component.html.erb, app/javascript/controllers/datatable_works_controller.js
This fixes 3 accessibility issues reported by SODA:
1 - This add the `aria-sort` value to the sorted column of the table and removes it from any other column (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort)
2 - Sets the document focus to the table when sort is clicked as it currently loses focus to somewhere else on the screen confusing screen reader users
3 - It sets `aria-label` properties on the paging buttons when the page is loaded or refreshed (needed if the number of objects per page or search changes the number of pages in the table) so that screen readers get meaningful information such as "go to next page"
Manually using a screen reader
No - it improves three major issues reported by SODA
=> Improve accessibility of simpledatatable display(s)

app/components/works/license_component.html.erb
Fixes #3348 
Reverts wording change that resulted from a conflict between the existing form and the mock up.
=> Revert wording on deposit for license and terms

app/assets/stylesheets/dashboard.scss, app/components/works/link_to_show_component.rb
This is a small PR to add a high contrast ratio border to improve visibility of targets when using keyboard navigation. This addresses a few of the color contrast "major" issues reported by soda.
While not obtrusive, this improves the ratio that is currently in place:
No.
=> Accessibility: Improve color contrast for focused objects

app/components/citation_component.rb
Fixes #3350 
The citation (`cite`) links were initially button types but were switched to anchors for accessibility, this changed the method of disabling.
=> Disable cite link when not deposited

config/initializers/byebug.rb
This commit tweaks the byebug initializer which allows using the byebug gem as a remote debugger, which is how we use byebug in H2 in development, by fixing the logging already in place and adding more helpful logging. This is a "quality of life" change for developers only.
CI, local
No
=> Improve dev server logging around the debugger

app/services/work_version_event_description_builder.rb, spec/requests/create_work_spec.rb
closes #3355
Avoid spurious event messages.
Local, Amy
=> Do not add spurious file event messages.

app/components/works/add_files_component.html.erb, app/components/works/add_files_component.rb, spec/components/works/add_files_component_spec.rb
closes #3352
The browser upload section does not function well with too many files.
Local, unit
Tested with SiteImprove plugin.
=> Do not provide file upload option when too many files.

app/controllers/application_controller.rb
To investigate #3377
While we currently log roles coming from the header, it's at the "debug" level, which means it will never log in production/stage/QA.  This may help figure out what's going on.
QA
=> add some info the logs on groups passed in via headers for debugging

Gemfile, Gemfile.lock, app/services/deposit_complete_auditor.rb, config/schedule.rb, config/settings.yml, spec/factories/work_versions.rb, spec/services/deposit_complete_auditor_spec.rb
To address cases in which a work/collection is not correctly updated when accessioning is completed.
refs #3371
Unit, QA
=> Adds deposit complete auditor

app/components/works/add_files_component.html.erb, app/components/works/add_files_component.rb, app/forms/base_work_form.rb, config/settings.yml, spec/features/update_existing_work_spec.rb
closes #3392
Per ticket.
Local, stage
=> Preserve files when creating / updating a work version with > 250 files.

Gemfile.lock, app/jobs/globus_setup_job.rb, spec/jobs/globus_setup_job_spec.rb
We already send the user an email when we create a new Globus endpoint for them - and the email they get from Globus is not as helpful.  The Globus API allows us to skip sending this email and the new globus_client (0.14.0) enables this functionality.  This PR should stop the globus email from being sent (by Globus) when we create a new endpoint.
~~HOLD to test and verify with PO~~
Verified with PO
Updated specs, tested on QA
=> ask globus to NOT send the user an email when creating new globus endpoint

app/services/deposit_complete_auditor.rb, spec/services/deposit_complete_auditor_spec.rb
On hold 'til J-Litt has time to do some analysis to determine if this is a legit situation or a weird data corner case. I'm throwing up a quick HOLD PR at the end of my day so J-Litt can take a gander in the morning. Yay timezones.
They are waiting on a druid assignment and we cannot ask the Workflow service if they are accessioned or not until they have a druid. This bug was revealed in a cronjob today.
CI
=> Skip deposit completion for objects lacking druids

app/services/deposit_complete_auditor.rb, spec/services/deposit_complete_auditor_spec.rb
This commit fixes a bug in the DepositCompleteAuditor where the auditor will mark an object as deposited when in fact it is only `Registered` in SDR. The change made: instead of checking if an object is in accessioning, check that is has not yet been accessioned.
=> Fix bug in DepositCompleteAuditor

app/controllers/preservation_controller.rb, config/routes.rb, spec/requests/preservation_spec.rb
This commit resolves an outstanding issue between Devise/Warden and ActionController::Live where unauthenticated users wind up raising an UncaughtThrowError exception.
=> Handle unauthenticated access in `PreservationController#show`

app/forms/work_form.rb, spec/features/update_existing_work_spec.rb
=> Allow metadata-only deposits without draft-saving

app/components/collections/terms_of_use_component.html.erb, app/components/works/detail_component.html.erb, app/components/works/license_component.html.erb
Resolves #3417 to support terms formatting that also displays in Purl. 
Local dev. Deployed to QA and reviewed by Amy. Added `simple_format` to an additional view as a result.
No new accessibility issues.
=> Allow linebreaks and display them in custom terms of use

public/robots.txt
Bots have no purpose on H2, which is all behind auth, but can cause problems (like this: https://app.honeybadger.io/projects/77112/faults/100514724)
We still allow the homepage though since that is open to the world and useful to have in search engines.
=> block all bots except on homepage

app/jobs/assign_pid_job.rb
refs #3297
To attempt to troubleshoot probable race condition between assigning druid and completing deposit.
=> Additional logging for assign_pid_job.

app/jobs/unzip_job.rb, spec/jobs/unzip_job_spec.rb
Fixes #3454 -- the Unzip job should not do anything unless the last uploaded file is actually a ZIP file and is on the file system (i.e. not from Globus)
~~Hold for PO verification~~
Localhost, stage and new spec
=> prevent zip job from getting stuck

app/controllers/work_move_controller.rb, config/locales/en.yml
Fixes #3462:
- The locale file was missing a description of the collection moved event, I set it to "Changed collection".  This will fix all history event displays once deployed.
- The name of the collection moved to in the event description was set to use the collection "description" field instead of the "name" (which is the title).  I changed it to use "name" going forward.  This will **not** fix previous entries unless we change them in the database manually for each event.
The reason it appeared to work OK for others is simply because the name and the description are sometimes very similar, e.g. 
"Undergraduate Theses, Materials Science and Engineering" == name/title
"Honors theses for undergraduates majoring in Materials Science and Engineering." == description
When done, go onto …
=> Fix display of collection move event

app/components/works/add_files_component.html.erb
Fixes #3465 
When a user uploads more than the max number of files in the browser (currently 250), we do not allow them to add more or show the list in the edit page.  We currently hide the entire browser upload panel, including the radio button.  This means if the user selects the zip upload option radio button (maybe by mistake), they cannot unselect it, which means they are stuck.  
This PR shows the radio button in this scenario with a different message, but without the ability to upload more files or show the file list (see below).  This makes it clear this is the default/current option, allows the user to change to globus or zip but also allows them to return to the "keep my lottsa files" option before saving.
~~HOLD for PO Testing~~
Localhost, stage
=> show the browser upload radio even when more than max files uploaded

.circleci/config.yml, app/jobs/deposit_complete_job.rb, spec/jobs/deposit_complete_job_spec.rb
refs #3297
Handle race condition between assigning a druid and marking a deposit as complete.
Unit
=> Adds retries to deposit complete job.

app/jobs/deposit_complete_job.rb
closes #3489
To avoid holding onto db connections and exhausting connection pool.
Unit, integration
=> Adjust retry strategy deposit complete job.

bin/test-files
This commit slightly tweaks the progress bar style when running the test-files script.
See https://github.com/sul-dlss/sdr-deploy/pull/260
CI
=> Tweak the progress bar style

app/services/ignore_file_service.rb, spec/jobs/fetch_globus_job_spec.rb
closes #3477
Files are not necessary and clutter things up.
Unit, Andrew.
=> Ignore mac Icon files.

app/controllers/works_controller.rb, app/services/new_version_service.rb, spec/factories/work_versions.rb, spec/features/revert_work_to_previous_version_spec.rb, spec/requests/create_work_spec.rb, spec/requests/dashboard_collection_spec.rb, spec/requests/dashboards_spec.rb, spec/requests/delete_work_version_spec.rb, spec/requests/edit_collection_spec.rb
Fixes #3512
Avoids unique constraint exceptions for user_version
=> Move the user version to the new WorkVersion

db/migrate/20240502142444_add_not_null_constraints_to_booleans.rb
To resolve prod db migration error when not null constraint added. 
Local and stage deploy
=> Provide non-null value with column change

.rubocop.yml, app/components/works/buttons_component.html.erb, app/components/works/buttons_component.rb, app/components/works/form_component.html.erb, app/components/works/form_component.rb, app/components/works/version_description_component.html.erb, app/controllers/works_controller.rb, app/forms/base_work_form.rb, app/javascript/controllers/new_user_version_controller.js, config/settings.yml, spec/components/works/version_description_component_spec.rb, spec/forms/work_form_spec.rb
Resolves #3504 to show a new user version section under a feature flag. 
Note this PR does not implement:
- Saving whether or not the version is a new user version
- When re-opening the draft, putting a previously provided version description in the correct version description box (requires above)
- Scrolling up to error when client-side validation detects that a description has not been provided.
Locally and specs 
Used aXe chrome extension to assess form labels. No new violations.
=> Implement user version selection

app/components/works/buttons_component.html.erb, app/components/works/buttons_component.rb, app/components/works/detail_component.rb, app/components/works/version_description_component.html.erb, app/components/works/version_description_component.rb, app/controllers/works_controller.rb, app/forms/base_work_form.rb, app/forms/work_form.rb, app/javascript/controllers/new_user_version_controller.js, app/services/new_version_service.rb, db/migrate/20240510172252_remove_unique_from_work_version.rb, db/structure.sql, spec/components/works/detail_component_spec.rb, spec/forms/work_form_spec.rb, spec/requests/create_work_spec.rb, spec/requests/edit_work_spec.rb
closes #3506
* Make it easier to manage user versions.
* Allow user versions to be persisted and synced with form.
Unit, Amy
=> Change approach to persisting user_versions.

app/javascript/controllers/auto_citation_controller.js
Quick fix for #3529 - there is a bug in the citation code that adds a space to the string if the dot is empty and therefore the values no longer match and the autogen button is disabled incorrectly.
Verified in stage and prod (using the item in the ticket)
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-pra …
=> Fix autogen citation disabled bug

app/forms/base_work_form.rb, app/models/work_version.rb, app/services/deposit_completer.rb, spec/services/deposit_completer_spec.rb
closes #3531
Per ticket
Unit, Amy
=> Adds user version to work history.

app/controllers/works_controller.rb, app/forms/base_work_form.rb
Fixes bug when submitting version 2 with a new user version, so that user_version can be calculated. 
Run locally and stage
=> Allow for original work form being validated when setting user_version param

Gemfile
```
warning: /usr/local/rvm/rubies/ruby-3.3.1/lib/ruby/3.3.0/csv.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec.
```
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) for more …
=> Move csv in Gemfile.

app/services/admin/collections_csv_generator.rb, app/services/admin/work_csv_generator.rb, lib/tasks/lock.rake, lib/tasks/version.rake
This dependency is moving out of stdlib in Ruby 3.4 so it must be managed by bundler.
CI
=> Add csv dependency to bundler

app/views/works/_delete_button.html.erb
Fixes #3566 
With just `data->confirm` the cancel button still performs the action, this needs to be `data->turbo_confirm` in order to actually cancel the delete action.
=> Small fix to a bug when canceling the delete of a draft work

app/components/works/detail_component.html.erb, app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb
Resolves #3582 to show links to purls for previous versions. Does not change the current prod view where user versions are not enabled. HOLD for PO review.
When there is only one user version, no Previous versions row displays:
When previous user versions exist: 
Unit and testing on QA.
=> Show previous user version purl links

app/controllers/fast_controller.rb, spec/requests/fast_spec.rb
Connects to #3581
So we know when the keywords typeahead API goes down or is decommissioned.
CI
=> Alert Honeybadger when OCLC FAST API service returns errors

app/components/works/detail_component.rb, app/javascript/controllers/auto_citation_controller.js, spec/components/works/detail_component_spec.rb
Resolves #3594 to use new version URL pattern in purl links and auto-citation.  Because the citation is saved to the database, it's possible that there may be old saved version URLs in citations where the auto-generated citation wasn't being used. I think this is OK though, since it's just stage and QA?
Will also be updating H2 version integration test.
Unit and stage.
=> Update purl version links to new pattern

app/components/works/detail_component.rb, spec/components/works/detail_component_spec.rb
A version 1 user version may not have a version description. Instead of showing a dash next to empty space, hide the dash. (I know this wasn't ticketed, @amyehodge, but it's been bugging me while we've been working on versions and is easy to fix.) 
Before:
After:
If a work version and description created later:
=> Don't show dash when no version description

app/javascript/controllers/dropzone_controller.js, spec/features/create_new_work_spec.rb
fixes #3602
- augmented feature spec (commented out fix temporarily on localhost and confirmed the test failed because it couldn't find the expected success indicator when trying to re-add the same file after removal)
- manual testing in firefox and chrome, on localhost and stage
n/a
it shouldn't
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility …
=> work edit, file upload via browser: allow a user to re-add a file of the same name as one that was removed from the list

.rubocop.yml, app/javascript/controllers/dropzone_controller.js
* @mjgiarlo made a good suggestion for refining the check after the PR was merged: https://github.com/sul-dlss/happy-heron/pull/3603#discussion_r1718543042
* i noticed a small rubocop touchup
* existing feature test from #3603
* browser testing using chrome and FF, on dev laptop and stage
https://github.com/user-attachments/assets/0e3f0bc5-6e34-422d-b784-c7bcd72d09a1
n/a
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a …
=> Refine allow readd file same name

app/components/works/version_description_component.rb, spec/components/works/version_description_component_spec.rb
closes #3606
Per @amyehodge 
Unit, Amy
=> Do not show version description form when rejected.

app/javascript/controllers/new_user_version_controller.js, spec/features/update_existing_work_spec.rb
Resolves #3612 to keep files upload section disabled until user makes a version selection. 
Unit and PO. 
=> File uploads should be disabled until version selection made

app/services/admin/work_csv_generator.rb, spec/services/admin/work_csv_generator_spec.rb
=> Add work type and subtypes to the admin item report

Gemfile.lock
Small dependency update for CVE-2025-24928 and CVE-2024-56171
=> Update nokogiri to address CVE-2025-24928 and CVE-2024-56171

.erb-lint.yml
I'm not sure if this line has always been broken or not, but I found we wanted this change in H3 so I'm porting it to H2.
CI is now linting ~920 fewer ERBs (all from dependencies, none that we want to lint)
=> Exclude `vendor/*` from erb_lint runs

Gemfile.lock, lib/tasks/reports.rake
Fixes #3689 - create a csv file with work types/subtypes
Rails console on the server
=> add rake task to produce csv report on work types/subtypes

app/services/account_service.rb
Why? Because sometimes the account API inexplicably returns 500 error responses with an XML string body instead of a JSON body. I have seen both of these behaviors occur regularly over the past two days. Instead of handling them separately, rely on the response status which is 500 in both cases.
CI
=> Check account service response status instead of parsing it from the response body

app/controllers/fast_controller.rb, spec/requests/fast_spec.rb
So we can figure out why this FAST API endpoint is so flaky.
CI
=> Include more honeybadger context when FAST API response is not valid JSON

app/controllers/fast_controller.rb
=> Serialize response object as hash for easier inspection in HB UI

app/controllers/fast_controller.rb
Do this because it is a best practice and because it eliminates HB exceptions about unhelpful 400 Bad Request responses from the FAST API when we send it improperly escaped query strings.
CI, prod
=> Encode user-provided keyword strings before sending to FAST API

app/models/attached_file.rb, app/services/cocina_generator/structural/file_generator.rb, app/services/cocina_generator/structural/generator.rb, spec/services/cocina_generator/dro_generator_spec.rb
closes #3718
H2 gets confused when the cocina has files with duplicate filenames.
Unit
=> Handle files with dupe names.

app/services/cocina_generator/description/generator.rb
H3 doesn't allow dupes, so this will help with roundtripping.
Unit
=> Dedupe access contacts when mapping to cocina.

app/services/cocina_generator/description/contributors_generator.rb, app/services/cocina_generator/description/events_generator.rb, spec/services/cocina_generator/description/contributors_generator_spec.rb, spec/services/cocina_generator/description/events_generator_spec.rb
Publishers are deprecated in H3. This helps with roundtripping.
Unit
=> Remove publisher from publication events.

app/services/cocina_generator/description/events_generator.rb, spec/services/cocina_generator/description/events_generator_spec.rb
refs https://github.com/sul-dlss/hungry-hungry-hippo/issues/533'
These events are deprecated. Getting rid of them will simplify H3 migration.
Unit
=> Stop mapping deposit modification events.

app/services/cocina_generator/access_generator.rb, spec/services/cocina_generator/access_generator_spec.rb
closes #3741
Expired embargoes shouldn't be in the cocina. This will cause problems for migration roundtripping.
Unit
=> Only add unexpired embargoes.

app/models/work_version.rb, app/services/cocina_generator/access_generator.rb, app/services/cocina_generator/structural/file_generator.rb, spec/services/cocina_generator/structural/file_generator_spec.rb
refs #3741
I missed that file access should also be correctly set when an embargo is expired.
Unit
=> Set correct file access when embargo is expired.

config/schedule.rb
Prevent crontab spam from H2, especially prod. We don't want email about sidekiq successfully connecting to redis every day, and we don't want developers ignoring crontab email lest something actually interesting come across the wire.
Ran `bin/rails r -e p "puts Rails.logger.level"` before and after the change.
=> Stop cron emails for info-level messages

app/services/cocina_generator/description/contributors_generator.rb, spec/services/cocina_generator/description/contributors_generator_spec.rb, spec/services/cocina_generator/description/generator_spec.rb
In recent changes to the mapping of publisher, uncited publishers were dropped from the mapping. This puts them back.
Unit
=> Map uncited publisher to contributor.

app/services/cocina_generator/description/contributors_generator.rb, config/settings.yml, spec/services/cocina_generator/description/contributors_generator_spec.rb
closes #3752
Citation status note is being deprecated.
Unit
=> Do not add citation status note when feature enabled.
